### ISSUE TITLE
Support gpg commit signing

### ISSUE THREAD

**Issue by matthauck** [nodegit/nodegit#1018]
nodegit does not appear to have support yet for gpg commit signing. Perhaps I have missed it in the documentation, but there does not appear to be support for this quite yet. Do you have plans to support it some time soon? If not, would you be willing to specify the API you would like to see so others could contribute? 

Thanks.

**Comment by matthauck** [comment]
Started taking a look at libgit2, and it looks like they have only [recently](https://github.com/libgit2/libgit2/commit/02d61a3) added support for this...

**Comment by johnhaley81** [comment]
Looks like libgit2 is starting to work in support for commit signing. https://github.com/libgit2/libgit2/pull/3673

It looks like [that function](https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_create_with_signature) is enabled in `master` right now so feel free to poke around and see how it works. 

We could probably write a helper method in `lib/commit.js` to make the API a little better but we definitely want some tests to confirm our bindings work so that's the best place to start IMO.

**Comment by matthauck** [comment]
I had found the commit, but didn't notice that PR with the discussion, which was helpful, thanks. I hope they may reconsider their API to be a bit easier to use... 

How frequently does nodegit take in new versions of libgit2?

**Comment by matthauck** [comment]
Second question: would nodegit also be averse to having the ability to support *gpg* signing? Or would you be inclined to stick closer with being javascript bindings for libgit2 and just expose the same API they do?

**Comment by johnhaley81** [comment]
> How frequently does nodegit take in new versions of libgit2?

HIstorically we've been slow to update libgit2 but hopefully with #1017 it'll make it a bit easier to handle that.

> Second question: would nodegit also be averse to having the ability to support gpg signing? Or would you be inclined to stick closer with being javascript bindings for libgit2 and just expose the same API they do?

Normally what we do in this situation is to do both. We automatically generate the wrappers for the public libgit2 functions and if we need to provide a better API or some other convenience function we'll throw that into `lib/<whatever>.js`.

For more complicated things that are out of scope there is always making a new repo that leverages NodeGit to do what you need (i.e. https://github.com/smith-kyle/nodegit-flow). 

I think that something like gpg signing is out of scope for this repo but would be ideal for something like a `nodegit-gpg-signing` repo/package.

**Comment by johnhaley81** [comment]
This is closer now with #1041

**Comment by andrewrynhard** [comment]
@johnhaley81 could you provide an example for `Commit.createWithSignature` and how to commit to  `HEAD` with it?

**Comment by andrewrynhard** [comment]
Where can I find the source code?

**Comment by oscar-b** [comment]
@johnhaley81 Any updates on gpg signing?

**Comment by johnhaley81** [comment]
@oscar-b I haven't been doing much with NodeGit lately. /cc @implausible @Mr-Wallet are you guys bringing in gpg signing?

**Comment by Mr-Wallet** [comment]
We're not... _not_ bringing in gpg signing... 😅

**Comment by oscar-b** [comment]
@Mr-Wallet looking forward to it 👏🏻

**Comment by Mr-Wallet** [comment]
<_< >_> 😅 💦

**Comment by Thatkookooguy** [comment]
was this implemented? if not, are there any updates on when is this planned?

**Comment by Mr-Wallet** [comment]
I'm not making any promises, but my team has scheduled time for this - we would like this done before the end of Winter.

**Comment by Thatkookooguy** [comment]
thanks for the update, Dark Sonic! uhhhhhh... I mean @Mr-Wallet :-)
That would be awesome

**Comment by getify** [comment]
I see `Commit.createWithSignature(..)`, but there's no tests for it, so I'm not sure if it's real or just a stub. Also, I don't see any way to work with it as designed.

I very much need to be able to sign my commits.

**Comment by rcjsuen** [comment]
libgit2 has a [test for `git_commit_create_with_signature`](https://github.com/nodegit/libgit2/blob/8d89e409616831b7b30a5ca7b89354957137b65e/tests/commit/write.c#L335-L400). Perhaps someone with GPG setup can write a NodeGit version and try it out.

**Comment by getify** [comment]
I could port that kind of code to nodegit to try, except I don't know how to generate the PGP **signature**... I have the keys, but I don't know what string to sign -- is it the commit hash or the entire commit contents? I am familiar with [using the `node-rsa` package for creating RSA signatures](https://github.com/rzcoder/node-rsa), but I don't know how to do that with PGP?

**Comment by saper** [comment]
Instead of reinventing PGP (which is quite complex) a separate module could be used. Maybe it could be integrated in a way that doesn't make Utah a hard dependency.

**Comment by Thatkookooguy** [comment]
this looks like a pretty solid library for handling `gpg`: https://www.npmjs.com/package/openpgp

**Comment by getify** [comment]
The question I still have is, which cleartext does git expect you to sign? Is it the commit hash? Or is there a specific way to format the text of a commit to use as the cleartext?

I don't mind using the external PGP library... clearly makes more sense than having nodegit invent its own PGP. What we need though is clear documentation on what git is expecting.

**Comment by getify** [comment]
I ask these questions because git's expectations here can inform the API design.

I'm imagining for example that the commit function can expect a callback (similar to the authorization callbacks when you push). This pgp-signature function would be passed a correct cleartext string, and must return the pgp signature.

**Comment by dabutvin** [comment]
@getify I have the same question.

I am working on adding signatures to commits with libgit and I'm not sure what cleartext is supposed to be signed

**Comment by getify** [comment]
Simple, clear example of creating a detached PGP signature from cleartext, from the docs at the "openpgpjs" project:

https://github.com/openpgpjs/openpgpjs#create-and-verify-detached-signatures

I think that would be more than sufficient, if we could just get verification of which cleartext to use.

**Comment by pmalouin** [comment]
Maybe we can take inspiration from git source?
https://github.com/git/git/blob/5be1f00a9a701532232f57958efab4be8c959a29/commit.c#L1566

It seems the `do_sign_commit()` method receives a buffer with the commit's content:
- All headers (tree, parents, author, committer, encoding, extra headers).
- The commit message.

From looking at libgit2's [changelog](https://github.com/libgit2/libgit2/releases/tag/v0.25.0), we have this explanation that seems to hint at how to sign commits:

> git_commit_create_buffer() creates a commit and writes it into a
user-provided buffer instead of writing it into the object db. Combine it with
git_commit_create_with_signature() in order to create a commit with a
cryptographic signature.

My interpretation is that the in-memory buffer returned from `git_commit_create_buffer()` contains the commit's content (headers and message) and it's the text that needs to be signed. Once the signature has been generated by an external tool, we call `git_commit_create_with_signature()` to combine both the commit's content and the signature and save the resulting object.

Hope this helps, I'm a newcomer here but I'm eager to see commit signing added to this library.

**Comment by dabutvin** [comment]
I got a working signature by signing the data in this format

```
"tree ${treeSha}\n" +
"parent ${parentSha}\n" +
"author ${authorData} {ticks} +0000\n" +
"committer ${authorData} ${ticks} +0000\n" +
"\n" +
"${commitMessage}\n";
```

I could tell it was working by using git on the command line and the `--show-signature` option of `log`

The problem I am having now is getting GitHub to verify this

![image](https://user-images.githubusercontent.com/5168796/36135273-f55f2be2-103e-11e8-8920-7d74dff202f3.png)

The key whose key-id is in the signature did not sign this commit. Someone may be trying to trick you.

I don't really understand how my key-id can be in the signature, but I did not sign the commit ???
stumped

**Comment by getify** [comment]
Is this line missing a `$`?

> "author ${authorData} {ticks} +0000\n" +

**Comment by getify** [comment]
And has that GPG key been added to your repo's settings?

**Comment by dabutvin** [comment]
I added the GPG public key to the commit author's GitHub account.

Do I have to add the key to the repo settings somewhere too?

**Comment by dabutvin** [comment]
I'm trying to wrap my head around the fact that the key-id is in the signature, but github doesn't think that key was used to sign the commit.

**Comment by getify** [comment]
> Do I have to add the key to the repo settings somewhere too?

No, sorry, I meant the user's settings.

**Comment by dabutvin** [comment]
I got a thread going in a GitHub forum on this: https://platform.github.community/t/signing-app-commits/3420/13

Verified that I am signing the right input data so that's cool!  

Currently I am struggling through figuring out the correct combination of newlines to make it all just work.

**Comment by dabutvin** [comment]
I set up a wrapper in `repository.js` to call `Commit.createWithSignature` and set the signature field to `gpgsig` and got a test passing. https://github.com/nodegit/nodegit/pull/1448
 It's hard to verify signature beyong expectedCommitId until `git_commit_extract_signature` becomes available [(v0.24)](https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_extract_signature)

For this issue would we want to bring in actual signing support into nodegit to make an API that looks like this?

```
Repository.prototype.createCommitWithSignature = function(
    updateRef, author, committer, message, tree, parents, privateKey, password, callback)
```

Or would you rather put the burden of actual signing a commit on another package?

**Comment by getify** [comment]
For consideration: I was envisioning an API similar to how you provide credentials for a push: a callback that you provide to the commit method, named `onSignature` or something like that, which is invoked with the string to sign (which would be the fully assembled commit text), and should simply return the appropriate signature. The user would then be responsible to make the appropriate call to a PGP library or whatever.

NOTE: we might want to anticipate that signing process might, for some libraries, need to be asynchronous, and so we might want to assume the callback in question might return a promise for the signature instead of the signature itself immediately. In this way, someone could provide an `async function` as the callback, and the promise wrapping of the return value will automatically be handled for them.

**Comment by implausible** [comment]
@dabutvin You can enable `git_commit_extract_signature` by heading into the `descriptor.json` file: https://github.com/nodegit/nodegit/blob/master/generate/input/descriptor.json#L525 and updating that entry to not be ignored.

**Comment by dabutvin** [comment]
woohoo this just landed in #1448 !!

I've got an implementation for signing commits using openpgp setup as a separate library for reference if anyone on this thread is interested.

https://github.com/dabutvin/pgp-commit

After the next nodegit release I can push to npm

**Comment by implausible** [comment]
We are missing rebase support for commit signing still. So I am going to re-open this as it's Almost There™

**Comment by jarrodek** [comment]
Hi, is this still active?

**Comment by implausible** [comment]
Rebase commit signing is available in the 0.25.0 alpha.

**Comment by jarrodek** [comment]
I recently tried to use `createCommitWithSignature` but I am getting this error:

> Error: Repository.prototype.createCommitWithSignature threw with error code undefined
      at /home/pawel/workspace/arc/api-components-apps/ci-app/node_modules/nodegit/dist/repository.js:597:23
      at async GitSourceControl.createCommit (github/git-source-control.js:252:12)

The implementation is like this:

```javascript
const author = this._createSignature();
const committer = this._createSignature();
return await repo.createCommitWithSignature(branch, author, committer, message, oid,
        parents, this._onSignature.bind(this));
```
where `_createSignature()` is something like `return Git.Signature.now(name, email);` with existing values. The `_onSignature`: generates (I think) valid signature that looks like this:

```javascript
'-----BEGIN PGP SIGNATURE-----\r\n' +
    'Version: OpenPGP.js v4.6.2\r\n' +
    'Comment: https://openpgpjs.org\r\n' +
    '\r\n' +
    'wsFcBAABCgAGBQJdxR12AAoJEK4/n/A8X2x7mfwP/R8n9cgyh2yKCpMoXrpO\r\n' +
    ... (removed)
    'yRj2\r\n' +
    '=K/v+\r\n' +
    '-----END PGP SIGNATURE-----\r\n'
```

I am not sure how to debug this to produce more information. Any help? :)

**Comment by dabutvin** [comment]
@jarrodek the first thing that jumps out to me about your signature is the `\r\n` line breaks
I am pretty sure they have to be `\n`

Can you share your `_onSignature` implementation?

I've got a reference implementation using openpgp over here if you want to check it out: https://github.com/dabutvin/pgp-commit/blob/master/index.js

**Comment by jarrodek** [comment]
So the implementation is here: https://github.com/advanced-rest-client/api-components-apps/blob/818c19ecf2e99ddaad813d85d7341be2aac30d56/ci-app/github/git-source-control.js#L192

I will take a look into your reference @dabutvin and will see if it helps

**Comment by dabutvin** [comment]
I think the return value of your method should be an object, not just the signature

```
return {
      code: Git.Error.CODE.OK,
      field: 'gpgsig',
      signedData: signed.signature
    }
```

**Comment by saper** [comment]
> Error: Repository.prototype.createCommitWithSignature threw with error code undefined
> at /home/pawel/workspace/arc/api-components-apps/ci-app/node_modules/nodegit/dist/repository.js:597:23

Which version exactly are you using?

**Comment by jarrodek** [comment]
I am using nodegit version 0.26.2 and openpgp version  4.6.2 @saper 
I will try this @dabutvin

**Comment by jarrodek** [comment]
@dabutvin this seems to work. Thank you.

**Comment by jarrodek** [comment]
I took a liberty of creating this [PR](https://github.com/nodegit/nodegit/pull/1740) that adds an example of how to create signed commits.
I have also added this gist which is basically the same: https://gist.github.com/jarrodek/218f0469691ab12b4254db2ff191c9f5
