### ISSUE TITLE
Heroku Build fails

### ISSUE THREAD

**Issue by benmarten** [nodegit/nodegit#1028]
2016-05-11T07:10:07.084938+00:00 app[web.1]: Express server listening on 53045, in production mode
	2016-05-11T07:10:07.143555+00:00 app[web.1]: /app/node_modules/nodegit/dist/nodegit.js:15
	2016-05-11T07:10:07.143575+00:00 app[web.1]:     throw ex;
	2016-05-11T07:10:07.143579+00:00 app[web.1]:     ^
	2016-05-11T07:10:07.143580+00:00 app[web.1]: 
	2016-05-11T07:10:07.143587+00:00 app[web.1]: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /app/node_modules/nodegit/build/Release/nodegit.node)
	2016-05-11T07:10:07.143594+00:00 app[web.1]:     at Error (native)
	2016-05-11T07:10:07.143603+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:434:18)
	2016-05-11T07:10:07.143604+00:00 app[web.1]:     at Module.load (module.js:343:32)
	2016-05-11T07:10:07.143605+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
	2016-05-11T07:10:07.143605+00:00 app[web.1]:     at Module.require (module.js:353:17)
	2016-05-11T07:10:07.143606+00:00 app[web.1]:     at require (internal/module.js:12:17)
	2016-05-11T07:10:07.143613+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/nodegit/dist/nodegit.js:11:12)
	2016-05-11T07:10:07.143614+00:00 app[web.1]:     at Module._compile (module.js:409:26)
	2016-05-11T07:10:07.143614+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
	2016-05-11T07:10:07.143615+00:00 app[web.1]:     at Module.load (module.js:343:32)
	2016-05-11T07:10:07.143615+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
	2016-05-11T07:10:07.143616+00:00 app[web.1]:     at Module.require (module.js:353:17)
	2016-05-11T07:10:07.143616+00:00 app[web.1]:     at require (internal/module.js:12:17)
	2016-05-11T07:10:07.143617+00:00 app[web.1]:     at Object.<anonymous> (/app/server/config/mocha.js:40:11)
	2016-05-11T07:10:07.143617+00:00 app[web.1]:     at Module._compile (module.js:409:26)
	2016-05-11T07:10:07.143618+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
	2016-05-11T07:10:07.143618+00:00 app[web.1]:     at Module.load (module.js:343:32)
	2016-05-11T07:10:07.143619+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
	2016-05-11T07:10:07.143620+00:00 app[web.1]:     at Module.require (module.js:353:17)
	2016-05-11T07:10:07.143620+00:00 app[web.1]:     at require (internal/module.js:12:17)
	2016-05-11T07:10:07.143621+00:00 app[web.1]:     at Object.exports.default (/app/server/config/schedule.js:36:5)
	2016-05-11T07:10:07.143626+00:00 app[web.1]:     at Server.<anonymous> (/app/server/app.js:56:41)
	2016-05-11T07:10:08.337827+00:00 heroku[web.1]: Process exited with status 1
	2016-05-11T07:10:08.353332+00:00 heroku[web.1]: State changed from starting to crashed

Seems its using some fancy library? Any ideas how to resolve?

**Comment by tbranyen** [comment]
The reason for this is documented in the README under Getting Started, outdated libstdc++ dependency. I'm not sure without Googling around how to resolve in Heroku.

**Comment by benmarten** [comment]
I tried your solution on a brand new Ubuntu 14.04LTS, same error!

**Comment by tbranyen** [comment]
What did you try? Did you try this on Heroku or locally? How did you confirm the fix didn't work?

**Comment by benmarten** [comment]
I setup a new Ubuntu 14.04LTS instance on Google Cloud, then installed dokku, then pushed my app to it, when the app launches it fails with the error:

         Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /app/node_modules/nodegit/build/Release/nodegit.node)
             
  =====> end status web container output

for some reason the library is present on my system though!
  ben@box1:~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 |grep 'GLIBCXX_3.4.20'
  GLIBCXX_3.4.20

any ideas?

**Comment by tbranyen** [comment]
I didn't see the README suggestion in your comment:

``` sh
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install libstdc++-4.9-dev
```

Even if you see it on your box, did you run the above commands so we can eliminate that being the issue?

**Comment by benmarten** [comment]
yes i did run this!

**Comment by tbranyen** [comment]
Probably. I don't know how Google Cloud handles installing Ubuntu, and I didn't see that command in your comment (or even referenced), but I know 14.04 doesn't ship with it.

That's very strange, I'm not entirely sure why it's happening. I'll need to spin up a VM later and confirm. Maybe @johnhaley81 can beat me to that.

**Comment by benmarten** [comment]
Thanks for your help, so far...

It might be related to dokku/docker, as it seems the incorrect lib version is included in the docker image?

	ben@box1 ~> sudo find / -name 'libstdc++.so.6.*'
	/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21-gdb.py
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
	/var/lib/docker/aufs/mnt/3d8a87af0a330227065dafd57a7eaacad0d99f9d6c5a3b2d9c082c47e34366bc/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17

**Comment by tbranyen** [comment]
Yeah, to be honest I don't know if anyone has successfully installed NodeGit within Docker. I had bugged someone I knew at Docker ages ago to assist, but we never found time.

Unfortunately it seems you're paying the pioneer tax.

**Comment by benmarten** [comment]
Ok, i just confirmed, that it must be related to dokku/docker, because its working on the same instance, as just a plain install...
