### ISSUE TITLE
Failed to install prebuilt binary

### ISSUE THREAD

**Issue by zhangyihua** [nodegit/nodegit#1029]
I'm get this error on:
  windows 7
  node v4.3.2

And aslo on: 
  ubuntu 14.04.1
  gcc version 4.8.4 
  node v4.4.3

-----

```bash

> nodegit@0.12.2 install C:\Program Files\nodejs\node_modules\fiss\node_modules\fiss-command-version\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""C:\Program Files\nodejs\node_modules\fiss\node_modules\fiss-command-version\node_modules\nodegit\node_modules\.bin\node-pre-gyp.cmd" install --fallback-to-build=false"
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: connect ETIMEDOUT 54.231.0.129:443
node-pre-gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
node-pre-gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
node-pre-gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\fiss\\node_modules\\fiss-command-version\\node_modules\\nodegit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Program Files\nodejs\node_modules\fiss\node_modules\fiss-command-version\node_modules\nodegit
node-pre-gyp ERR! node -v v4.3.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c ""C:\\Program Files\\nodejs\\node_modules\\fiss\\node_modules\\fiss-command-version\\node_modules\\nodegit\\node_modules\\.bin\\node-pre-gyp.cmd" install --fallback-to-build=false"' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
nodegit@0.12.2 C:\Program Files\nodejs\node_modules\nodegit
├── promisify-node@0.3.0 (nodegit-promise@4.0.0)
└── fs-extra@0.26.7 (jsonfile@2.3.0, graceful-fs@4.1.4, klaw@1.2.0, path-is-absolute@1.0.0, rimraf@2.5.2)


> nodegit@0.12.2 postinstall C:\Program Files\nodejs\node_modules\fiss\node_modules\fiss-command-version\node_modules\nodegit
> node postinstall.js

```

I don't know what lead to that. Someone can thell me the why?

**Comment by tbranyen** [comment]
Pretty sure you need GCC 4.9 if you want to compile from source. You should have gotten the prebuilt binary though... Here's our build matrix: https://github.com/nodegit/nodegit/blob/master/.travis.yml#L16-L19

Maybe try 4.1 or 6? See if that helps.

**Comment by johnhaley81** [comment]
FWIW I just did it with node v 4.4.3

**Comment by zhangyihua** [comment]
Ok, thx. I try later.

**Comment by johnhaley81** [comment]
@zhangyihua is this still broken for you?

**Comment by zhangyihua** [comment]
Thx @johnhaley81. Due to my network fail to connect S3.

**Comment by zhangyihua** [comment]
And the solution of @tbranyen had worked on UNIX.
