### ISSUE TITLE
Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.13.1-electron-v0.37-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by li-cn** [nodegit/nodegit#1046]
I got a 403 error from S3 while building an Electron project depending on the nodegit prebuilt binaries targeting Electron v0.37.8 on x64 architecture. I think this was working last week, so my best guess right now is that the prebuilt binaries for that target got unpublished or the S3 permissions were changed.

I can't seem to find a list of published prebuilt binaries for nodegit anywhere, despite seeing tons of references to them in the issues. Is there some way to find out which prebuilt binaries have been published?

Relevant output:

```
> nodegit@0.13.1 install /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ Error: Command failed: "/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.13.1-electron-v0.37-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/node_modules/request/request.js:977:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:359:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/Users/leonli/.nvm/versions/node/v6.2.0/bin/node" "/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false' }
nodegit@0.13.1 /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit
├─┬ fs-extra@0.26.7 
│ ├── jsonfile@2.3.1 
│ └── klaw@1.2.0 
└─┬ promisify-node@0.3.0 
  └─┬ nodegit-promise@4.0.0 
    └── asap@2.0.4 


[nodegit] Configuring libssh2.
ERROR - Could not generate native code
TypeError: _(...).forEach(...).value is not a function
    at Object.Helpers.decorateFunction (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/scripts/helpers.js:348:8)
    at /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/scripts/helpers.js:209:15
    at Array.forEach (native)
    at Object.Helpers.decoratePrimaryType (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/scripts/helpers.js:208:23)
    at /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/scripts/generateJson.js:117:13
    at Array.forEach (native)
    at generateJson (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/scripts/generateJson.js:109:9)
    at /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit/generate/index.js:24:7
    at tryCallOne (/Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit-promise/lib/core.js:37:12)
    at /Users/leonli/Documents/repos/electron-git-test/build/node_modules/nodegit-promise/lib/core.js:103:15
```

**Comment by li-cn** [comment]
Fixed it: The nodegit dependency in my package.json was set to `^0.13.0`, and nodegit 0.13.1 was released 4 days ago. Since that release, running `npm install` requests the prebuilt binaries for version 0.13.1 instead of 0.13.0, causing the 403 error from S3.

I guess the 0.13.1 binaries targeting Electron 0.37 haven't been published yet. Changing the nodegit dependency to `0.13.0` fixed this issue for me. **Is there any way to see which prebuilts have been published?**

**Comment by johnhaley81** [comment]
The system we have in place for prebuilts is pretty crazy. Any time we push a tag, all of the entries in our CI matrix will build and publish a binary to S3. You can see what versions are published for node here:

Linux/OSX:
https://travis-ci.org/nodegit/nodegit/builds

Windows:
https://ci.appveyor.com/project/timbranyen/nodegit/history

Electron binaries are built from the tags that are pushed to https://github.com/nodegit/electron-npg-automator. Any tag that's pushed to this repository is parsed and then we grab the version of NodeGit and the version of Electron we're targeting and build them on CI.
