### ISSUE TITLE
0.13.2 broken npm install

### ISSUE THREAD

**Issue by get-trucked** [nodegit/nodegit#1052]
So using 4.4.5 lts node js the npm install for 13.2 appears to be a little broken.

It fails to download due to missing deps, as I can only assume npm 2.15 which comes with lts node is installing these later not part of the pre build steps with node-pre-gyp

It then rolls back to building from source which is as expected in a failed binary download attempt but not ideal as it takes a long time to do.

I had also tried on node v6 and this was ok with downloading the binary from s3.

Output of node 4.4.5:

```
npm install nodegit@0.13.2
/
> nodegit@0.13.2 install /home//[redacted]/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: /bin/sh -c "/home/[redacted]/node_modules/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false
module.js:327
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home//[redacted]/node_modules/nodegit/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c "/home//[redacted]/node_modules/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
```

**Comment by leo** [comment]
Same for me! All Travis CI builds broken because of this...

**Comment by qops1981** [comment]
Posted on the second link above; using: `npm install -g npm`
Solved my problem.

**Comment by get-trucked** [comment]
@qops1981 That may be helpful for some users, but I'm not sure why that works for you. I can only guess/assume you are using npm3+ globally or already have those dependencies installed globally from something else?

**Comment by tbranyen** [comment]
It looks like @johnhaley81 is working on real fixes here: https://github.com/nodegit/nodegit/pull/1055

Globally installing `npm` might work like @get-trucked said, but it's definitely not the end-all true solution.

**Comment by Daniel15** [comment]
I'm seeing this too:
```
λ npm install --save-dev nodegit
|
> nodegit@0.13.2 install C:\src\test\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: C:\windows\system32\cmd.exe /s /c ""C:\src\test\node_modules\nodegit\node_modules\.bin\node-pre-gyp.cmd" install --fallback-to-build=false"
module.js:327
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\src\test\node_modules\nodegit\node_modules\node-pre-gyp\lib\node-pre-gyp.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\windows\\system32\\cmd.exe /s /c ""C:\\src\\test\\node_modules\\nodegit\\node_modules\\.bin\\node-pre-gyp.cmd" install --fallback-to-build=false"' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
```

**Comment by johnhaley81** [comment]
I just published NodeGit 0.14.0. Feel free to try that to see if your problems are fixed now :)

**Comment by aoffpo** [comment]
I am seeing the exact same problem on 0.14.0 as Daniel15 reported.

**Comment by maxkorp** [comment]
Marking this fixed until we hear otherwise :+1:

**Comment by Daniel15** [comment]
Looks good to me now. Thanks!
