### ISSUE TITLE
Electron Builder asar error

### ISSUE THREAD

**Issue by jojobyte** [nodegit/nodegit#1066]
Been spawning child processes for git and wanted to switch to nodegit, but keep getting this error after installing then trying to build the Dist.

```sh
Packaging for platform mac x64 using electron 1.2.6 to dist/mac

Error: File "~/workspace/repos/electron-app/dist/mac/electron_app.app/Contents/Resources/app.asar" is corrupted: SyntaxError: Unexpected end of JSON input
    at Object.<anonymous> (~/workspace/repos/electron-app/node_modules/electron-builder/src/asarUtil.ts:66:13)
From previous event:
    at tsAwaiter (~/workspace/repos/electron-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (~/workspace/repos/electron-app/node_modules/electron-builder/src/builder.ts:190:52)
    at Object.<anonymous> (~/workspace/repos/electron-app/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "~/.npm-global/bin/npm" "run" "dist"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! electron_app@0.0.1 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the electron_app@0.0.1 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron_app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron_app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron_app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/workspace/repos/electron-app/npm-debug.log
```

If I remove nodegit it builds correctly. If I disable asar it also builds correctly.

```sh
# .npmrc
runtime = electron
target = 1.2.6
target_arch = x64
disturl = https://atom.io/download/atom-shell
progress = true
build_from_source = true
```

While this log is from OSX, this same error happens on Windows 10.

Any ideas? Need more info?

**Comment by maxkorp** [comment]
I wonder what json it's dying on. 

It's dying here: `electron-builder/src/asarUtil.ts:66:13`
any chance you get get in there to the compiled js and just sneak in a console log to discover what output it's parsing perhaps?

**Comment by jojobyte** [comment]
Not even sure where to look to add a console log. That error is literally just from npm installing nodegit, not even requiring it in my code.

Manually building the asar via cmd line seemed to work (as in I received no errors when compiling), although I wasn't able to get it to run.

**Comment by maxkorp** [comment]
Not especially familiar with electron-builder, does npm build cause it to do an npm install?

**Comment by jojobyte** [comment]
Not sure.

This is what I get in windows without build_from_source enabled.

```sh
npm run dist

> electron-app@0.0.1 dist C:\dev\electron-app
> build

Rebuilding app dependencies for arch x64 to C:\dev\electron-app\app

Warning: Application icon is not set, default Electron icon will be used

> electron-prebuilt@1.2.6 postinstall C:\dev\electron-app\app\node_modules\electron-prebuilt
> node install.js


> nodegit@0.15.1 preinstall C:\dev\electron-app\app\node_modules\nodegit
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script

> nodegit@0.15.1 install C:\dev\electron-app\app\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Running install script
[nodegit] Success: "C:\dev\electron-app\app\node_modules\nodegit\build\Release\nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.15.1 postinstall C:\dev\electron-app\app\node_modules\nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node C:\dev\electron-app\app\node_modules\nodegit\dist\nodegit.js
C:\dev\electron-app\app\node_modules\nodegit\dist\nodegit.js:15
    throw ex;
    ^

Error: The specified module could not be found.
\\?\C:\dev\electron-app\app\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\electron-app\app\node_modules\nodegit\dist\nodegit.js:11:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\dev\\electron-app\\app\\node_modules\\nodegit\\dist\\nodegit.js' }
```

This is the error with build_from_source enabled

```sh
ERR! build error
gyp
ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\electron-app\app\node_modules\node-gyp\lib\build.js:276:23)
gyp
ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14385
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\electron-app\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\dev\\electron-app\\app\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\dev\\electron-app\\app\\node_modules\\nodegit\\build\\Release"
gyp ERR! cwd C:\dev\electron-app\app\node_modules\nodegit
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v
v3.4.0
gyp ERR! not ok
node-pre-gyp

ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\electron-app\app\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\dev\electron-app\app\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\dev\electron-app\app\node_modules\nodegit\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\dev\electron-app\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.14385
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\electron-app\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\dev\electron-app\app\node_modules\nodegit
node-pre-gyp ERR! node -v v6.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\electron-app\app\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\dev\electron-app\app\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\dev\electron-app\app\node_modules\nodegit\build\Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by maxkorp** [comment]
So it fails to actually compile, but thats not really unexpected, it's grabbing from aws anyways. 
Just weird that it says it cant find it, which to me sounds an awful lot like it's not actually properly built for electron. 

Is npm vacuuming nodegit out? After the error, does `C:\dev\electron-app\app\node_modules\nodegit` still exist?

**Comment by jojobyte** [comment]
Yes, it exists. Even has nodegit.node that it complains doesnt exist.

**Comment by maxkorp** [comment]
So, if you cd into that folder, and just run `node` in your terminal, and in the console try `require('./build\Release\nodegit.node')` does that work?

**Comment by jojobyte** [comment]
`var nodegit = require('./build/Release/nodegit.node')` does. Even CDing into the folder `C:\dev\electron-app\dist\win-unpacked\resources\app\node_modules\nodegit` then running `node` and doing that does. But when I try to start the EXE I get:

![image 2016-07-15 at 12 57 15 pm](https://cloud.githubusercontent.com/assets/184880/16885452/dcfd1822-4a8b-11e6-9c25-973cfd2a127a.png)

**Comment by maxkorp** [comment]
Yeah, so somehow, you're getting a prebuilt for node, instead of for electron. 
Are you still using the npmrc (just minus the `build_from_source`) when you're not building from source?

**Comment by jojobyte** [comment]
Yup!

```sh
# .npmrc
runtime = electron
target = 1.2.7
target_arch = x64
disturl = https://atom.io/download/atom-shell
progress = true
```

Is there a way I can manually download the prebuilt and copy and paste it to see if it resolves the issue?

**Comment by maxkorp** [comment]
Well, loading it in node pretty well confirms the  Can you link me to a project (either yours if it's open, or an almost barebones project using nodegit) using electron-builder?

**Comment by jojobyte** [comment]
https://github.com/jojobyte/git-electron

Thats a stripped down version. Basically Electron & Nodegit.

Run `npm install` then `npm start` to open in electron or `npm run dist` or `npm run pack` to build the installers.

This is actually starting and packaging for me but nodegit does not seem to clone anything.

**Comment by maxkorp** [comment]
Awesome dude, I'll take a look. Thanks for putting so much time in to reporting this.

**Comment by maxkorp** [comment]
So, your example works fine for me locally, i can install, and run via npm start, and i can run the dist script, and then i can open the app thats placed in the dist folder and the app when i extract it from the zip. I'm able to do stuff with nodegit in the dev console as well.

**Comment by jojobyte** [comment]
I'll try it on my laptop and see. Maybe I need to reinstall node-gyp windows stuff or something.

**Comment by jojobyte** [comment]
Okay, it worked on my windows laptop as is, but if you set `build.asar` to `true` in package.json in the project root you get the original error I was reporting.

**Comment by maxkorp** [comment]
Hrm, lemme dig a little further

**Comment by maxkorp** [comment]
Looked at this a bit more, I honestly have no idea man :/

**Comment by maxkorp** [comment]
Well, when i get the json contents of the asar and try parsing them I get the same error, but adding 2 closing braces seems to fix it? 
http://www.jsoneditoronline.org/?id=a6ac96d57bbfd93575b3e92d0566bf1f

I'm going to have to chalk this up to an electron-builder bug, I'd log something over there. I'm able to pack nodegit into an asar manually (omitting the .node, clearly) without trouble  :/
