### ISSUE TITLE
cant install nodegit if the directive name in the path has space

### ISSUE THREAD

**Issue by luffyzc** [nodegit/nodegit#1082]
when i try to install nodegit i get this error:

`{ Error: Command failed: /Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/openssl/openssl
/bin/sh: /Users/luffyzc/My: No such file or directory

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:492:12)
```

  killed: false,
  code: 127,
  signal: null,
  cmd: '/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/openssl/openssl' }
/bin/sh: /Users/luffyzc/My: No such file or directory

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/openssl/openssl
/bin/sh: /Users/luffyzc/My: No such file or directory

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:492:12)
```

  killed: false,
  code: 127,
  signal: null,
  cmd: '/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/luffyzc/My Program/Nodejs/API Documentation/nodegit/vendor/openssl/openssl' }`

According to this error message`/bin/sh: /Users/luffyzc/My: No such file or directory` I think it get failed when it process the path which has directive "My Program".  So i tried to install at other path, it works, and i went back to change the directive name to remove the space in the directive name , it works this time. 

So I guess this preinstall has some problem when it process path with complicate directive name with space like"My Program". Hope this can be fixed.

**Comment by johnhaley81** [comment]
Should be fixed on master.
