### ISSUE TITLE
how to change the library path that nodegit compiles against?

### ISSUE THREAD

**Issue by calvinmwhu** [nodegit/nodegit#1100]
So when I run npm install on nodegit it gives me:

```
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/mhu/app/mailman_portal_v1_server/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mhu/app/mailman_portal_v1_server/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node /home/mhu/app/mailman_portal_v1_server/node_modules/nodegit/dist/nodegit.js' }

```
My libc.so.6 only has GLIBC_2.12 so I install glibc-2.14 from source but the new library has a different name: libc-2.14.so . How do I configure the nodegit installation so that it compiles against /lib64/libc-2.14.so instead of /lib64/libc.so.6 ?

**Comment by saper** [comment]
I am sorry, but for the older glibc you will need to compile from source (I can see from other issues that you are trying this at the moment).

**Comment by calvinmwhu** [comment]
You mean I need to compile nodegit from source by doing a npm install inside the nodegit repo ?

**Comment by saper** [comment]
Yes.

**Comment by maxkorp** [comment]
Alternatively, you can set BUILD_ONLY=1 when you run `npm install nodegit`
