### ISSUE TITLE
Failed to install 0.15.1 with 'stderr maxBuffer exceeded' error

### ISSUE THREAD

**Issue by azotova** [nodegit/nodegit#1103]
Hi, I experienced the following issue on Mac OS 10.11.6 (and 10.11.5). Node v. 4.4.3.

```
npm info preinstall nodegit@0.15.1

> nodegit@0.15.1 preinstall /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] ERROR - Could not finish preinstall
{ [Error: stderr maxBuffer exceeded] cmd: '/bin/sh -c npm install --ignore-scripts' }
npm verb unsafe-perm in lifecycle true
npm info nodegit@0.15.1 Failed to exec preinstall script
npm verb unlock done using /Users/anastasiazotova/.npm/_locks/nodegit-a5f407442d9071bb.lock for /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
npm verb stack Error: nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:827:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid nodegit@0.15.1
npm verb cwd /Users/anastasiazotova/lampa-docker/lampa-root/lada
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
```

Update: upgrading to node v.6.2.2 seems to have solved the issue.

**Comment by saper** [comment]
Also reported against npm: https://github.com/npm/npm/issues/11670

**Comment by saper** [comment]
Would that be possible to try that with an older node and npm 3.9.0? It would be good to check if this is really an npm issue. What version of npm did you have before with node v4?

**Comment by azotova** [comment]
I had npm v2.15.1 with node v. 4.4.3. I'll try to test it with the combination of node v.4.4.7 and npm 3.9.0 this weekend.

**Comment by azotova** [comment]
I tested it with node v. 4.5.0 and npm v. 3.10.6 (is this ok or should it be npm 3.9.0 specifically?) I installed nodegit successfully. These are nodegit-related messages that I see in the terminal:
```
> nodegit@0.15.1 preinstall /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/.staging/nodegit-1a22ffce
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> nodegit@0.15.1 install /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Running install script
[nodegit] Success: "/Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.15.1 postinstall /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
> node lifecycleScripts/postinstall
```

**Comment by saper** [comment]
This seems to be an npm bug then. According to https://github.com/npm/npm/issues/11670 it was broken with npm v3.7.3 and worked after upgrade to v3.9.0, I don't know when and how exactly this got fixed.

**Comment by withinboredom** [comment]
It was crashing for me due to running `npm install --save nodegit` while having an `npm-shrinkwrap.json` file... I deleted the shrinkwrap and it installed fine.

**Comment by maxkorp** [comment]
Closing this as an npm bug.
