### ISSUE TITLE
ReferenceError: Promise is not defined on Debian

### ISSUE THREAD

**Issue by strugee** [nodegit/nodegit#1118]
Installing NodeGit on Debian 8 gives:

```
% npm install nodegit

> nodegit@0.14.1 preinstall /home/alex/node_modules/.staging/nodegit-7fe5623e
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script

/home/alex/node_modules/.staging/nodegit-7fe5623e/utils/execPromise.js:7
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at module.exports (/home/alex/node_modules/.staging/nodegit-7fe5623e/utils/execPromise.js:7:14)
    at Module.prepareForBuild [as exports] (/home/alex/node_modules/.staging/nodegit-7fe5623e/lifecycleScripts/preinstall.js:11:10)
    at Object.<anonymous> (/home/alex/node_modules/.staging/nodegit-7fe5623e/lifecycleScripts/preinstall.js:37:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
/home/alex
└─┬ d@0.1.1
  └─┬ es5-ext@0.10.12
    ├── es6-iterator@2.0.0
    └── es6-symbol@3.1.0

npm WARN enoent ENOENT, open '/home/alex/package.json'
npm WARN alex No description
npm WARN alex No repository field.
npm WARN alex No README data
npm WARN alex No license field.
npm ERR! Linux 4.6.0-0.bpo.1-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "nodegit"
npm ERR! node v0.10.29
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.14.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the nodegit@0.14.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/npm-debug.log
```

I'm on Node.js version `v0.10.29`, npm version `3.10.6`. My `npm-debug.log` is at http://sprunge.us/XbBP.

**Comment by maxkorp** [comment]
FYI, we've completely dropped node 0.10 support a while ago. We should however still be using a promise library I thought.

**Comment by strugee** [comment]
That's unfortunate, as most Linux distributions ship 0.10. I get it, though. :(

**Comment by maxkorp** [comment]
Honestly, we're most likely going to end up dropping 0.12 soon as well. We'll maintain through LTS (and longer if theres no reason to drop), but even 0.12 is going to have some issues that arent worth coding around at link time pretty soon. That's not to say it won't work with 10,  just not officially supported.

Edit: That's in the build scripts? I'll take a look around, if we're using a promise lib elsewhere in the build I don't see why we wouldn't here, and I can get it patched up.

**Comment by strugee** [comment]
OK. In any case I ended up must writing the same thing, based on spawning Git subprocesses. So no worries :)

**Comment by strugee** [comment]
Do we want to close this? Most major Linux distributions have Node >4 available in some form: https://nodecompat.com/

Plus you guys have already officially dropped support, anyway.
