### ISSUE TITLE
postinstall fails on Windows

### ISSUE THREAD

**Issue by dwelle** [nodegit/nodegit#1132]
windows 7, node v6

```
> nodegit@0.16.0 postinstall C:\<path>\node_modules\nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node C:\<path>\node_modules\nodegit\dist\nodegit.js

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 3228369023,
  signal: null,
  cmd: 'node C:\\<path>\\node_modules\\nodegit\\dist\\nodegit.js' }
```

**Comment by aspirisen** [comment]
Have the same on windows

**Comment by PatrickWalker** [comment]
Worked for me on windows 10 btw specifically installing v0.16.0 from npm cli but that was node v4.5.0 but I retried with 6.9.1 and also got a success

> [nodegit] Completed installation successfully.
> 
> nodegit@0.16.0 postinstall D:\OpenSource\js\testProj\node_modules\nodegit
> node lifecycleScripts/postinstall
> 
> testproj@1.0.0 D:\OpenSource\js\testProj
> `-- nodegit@0.16.0  extraneous
> 
> npm WARN testproj@1.0.0 No description
> npm WARN testproj@1.0.0 No repository field.

**Comment by PatrickWalker** [comment]
https://github.com/sass/node-sass/issues/1371#issuecomment-181830972
references potential permissions error. Is this a package install or a local build/install?

**Comment by Glowyrm** [comment]
installing latest 0.16 fails

windows 8.1, node v6.2.1

> nodegit@0.16.0 postinstall C:\Users\b\Documents\des_projects\web_dev\tim\tsampi_fcommit\node_modules\nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node C:\Users\b\Documents\des_projects\web_dev\tim\tsampi_fcommit\node_modules\nodegit\dist\nodegit.js

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 3228369023,
  signal: null,
  cmd: 'node C:\\Users\\b\\Documents\\des_projects\\web_dev\\tim\\tsampi_fcommit\\node_modules\\nodegit\\dist\\nodegit.js' }
tsampi-fcommit@1.0.0 C:\Users\b\Documents\des_projects\web_dev\tim\tsampi_fcommit
`-- nodegit@0.16.0 extraneous

npm WARN tsampi-fcommit@1.0.0 No description
npm WARN tsampi-fcommit@1.0.0 No repository field.
