### ISSUE TITLE
npm install -g fails on preinstall with project where nodegit is a dependency. 

### ISSUE THREAD

**Issue by alantrrs** [nodegit/nodegit#1142]
Tested on macOS Sierra and OS X El Capitan.

I get the following error when doing ``npm install -g`` on Mac. It looks like it's failing on the preinstall script 
```
$npm install -g empiricalci/emp#node-git-upgrade
-
> nodegit@0.16.0 install /Users/empirical/.node_modules/lib/node_modules/empirical-cli/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
[nodegit] Running install script
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-pre-gyp ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "empiricalci/emp#node-git-upgrade"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
```

It doesn't fail however when I do ``npm install`` within the project's directory. This works fine:
```
git clone https://github.com/empiricalci/emp#node-git-upgrade
cd emp
npm install
-
> spawn-sync@1.0.15 postinstall /Users/empirical/workspace/emp/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/npm-run/node_modules/spawn-sync
> node postinstall

-
> fsevents@1.0.14 install /Users/empirical/workspace/emp/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/empirical/workspace/emp/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
\
> nodegit@0.16.0 install /Users/empirical/workspace/emp/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/Users/empirical/workspace/emp/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.16.0 postinstall /Users/empirical/workspace/emp/node_modules/nodegit
> node lifecycleScripts/postinstall

```

Any thoughts?

**Comment by alantrrs** [comment]
Never mind, my bin path was not set properly so node-pre-gyp wasn't being found.
