### ISSUE TITLE
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 

### ISSUE THREAD

**Issue by kauegimenes** [nodegit/nodegit#1150]
Hello, 

I am trying to publish my application that uses nodegit to Openshift, but i am getting this error:

```
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/lib/openshift/*/app-root/runtime/repo/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/openshift/*/app-root/runtime/repo/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by saper** [comment]
Your deployment environment used a different (probably lodem) runtime C++ library `libstdc++`. The easiest way to fix this is to build node-git on your target environment from source, capture and deploy the `binding.node` file as a binary. Please note it might be incompatible with the environment your are deploying from.

**Comment by jordonbiondo** [comment]
For others: I've been using this in my `package.json` to make it work for now, it's not ideal but it works for my production and dev environments.
``` json
...
"scripts": {
    "preinstall": "npm install nodegit --build-from-source"
}
...
```
