### ISSUE TITLE
Tests fail on MacOS Sierra

### ISSUE THREAD

**Issue by DinkDonk** [nodegit/nodegit#1168]
Master branch fails testing on MacOS Sierra:

2 failing:

```bash
1) Clone can clone with ssh:
    Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

2) Remote can reject fetching from private repository without valid credentials:
    
    AssertionError: Should not be able to find repository.
      + expected - actual

    -Callback failed to initialize SSH credentials
    +ERROR: Repository not found.

    at test/tests/remote.js:245:18
    at tryCallOne (node_modules/nodegit-promise/lib/core.js:37:12)
    at node_modules/nodegit-promise/lib/core.js:103:15
    at flush (node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by czerwonkabartosz** [comment]
I have the same problem.

```
  288 passing (3m)
  4 pending
  2 failing

  1) Clone can clone with ssh:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Remote can reject fetching from private repository without valid credentials:

      AssertionError: Should not be able to find repository.
      + expected - actual

      -Callback failed to initialize SSH credentials
      +ERROR: Repository not found.
      
      at test/tests/remote.js:245:18
      at tryCallOne (node_modules/nodegit-promise/lib/core.js:37:12)
      at node_modules/nodegit-promise/lib/core.js:103:15
      at flush (node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by czerwonkabartosz** [comment]
@DinkDonk I found the solution. For me, enough to run the command `ssh-add` to add the SSH key to the ssh-agent.

**Comment by zaak** [comment]
I had the same result on Linux. For me it started working after I added private and pub key under `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub` respectively.

**Comment by johnhaley81** [comment]
Closing this as resolved.
