### ISSUE TITLE
Fails to install on Ubuntu 16.04 xenial

### ISSUE THREAD

**Issue by ibc** [nodegit/nodegit#1175]
I've seen #1088. I've already installed `libssl-dev`.

```bash
ibc@www:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```bash
ibc@www:~$ dpkg -l | grep ssl
ii  libgnutls-openssl27:amd64        3.4.10-4ubuntu1.1                  amd64        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:amd64                 1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                       1.0.2g-1ubuntu4.5                  all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                          1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                   0.15.1-2build1                     all          Python 2 wrapper around the OpenSSL library
```

`npm install nodegit` still fails:

<details>
```
ibc@www:~$ npm i nodegit

> nodegit@0.16.0 install /home/ibc/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl
/home/ibc/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/ibc/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/ibc/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl' }
/home/ibc/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/ibc/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/ibc/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl
/home/ibc/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/ibc/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/ibc/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl' }
/home/ibc
└─┬ d@0.1.1
  └─┬ es5-ext@0.10.12
    ├── es6-iterator@2.0.0
    └── es6-symbol@3.1.0

npm WARN enoent ENOENT: no such file or directory, open '/home/ibc/package.json'
npm WARN ibc No description
npm WARN ibc No repository field.
npm WARN ibc No README data
npm WARN ibc No license field.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "nodegit"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
```
</details>

**Comment by ibc** [comment]
Ok, `g++` was missing.
