### ISSUE TITLE
I can't install this module in Windows 7 

### ISSUE THREAD

**Issue by liuyutao** [nodegit/nodegit#1222]
I encouter this error 
E:\workSpaces\pageConfigManage\app>npm i nodegit
\
> nodegit@0.17.0 install E:\workSpaces\pageConfigManage\app\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(undefined): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.17.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.17.0 and node@4.6.0 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp

ERR!
clean error
gyp
ERR! stack Error: EPERM: operation not permitted, unlink 'E:\workSpaces\pageConfigManage\app\node_modules\nodegit\build\Release\nodegit.node'
gyp ERR! stack     at Error (native)
gyp
ERR! System Windows_NT 6.1.7601
gyp
ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\workSpaces\\pageConfigManage\\app\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "clean"
gyp ERR!
cwd E:\workSpaces\pageConfigManage\app\node_modules\nodegit
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\workSpaces\pageConfigManage\app\node_modules\nodegit\node_modules\node-gyp\bin\node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\workSpaces\pageConfigManage\app\node_modules\nodegit\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack
at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp
ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\workSpaces\\pageConfigManage\\app\\node_modules\\nodegit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\workSpaces\pageConfigManage\app\node_modules\nodegit
node-pre-gyp ERR! node -v v4.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp
ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\workSpaces\pageConfigManage\app\node_modules\nodegit\node_modules\node-gyp\bin\node-gyp.js clean' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "nodegit"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.17.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.17.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\workSpaces\pageConfigManage\app\npm-debug.log

**Comment by liuyutao** [comment]
node version v4.6.0
npm version 2.15.9

**Comment by liuyutao** [comment]
npm -debug.log
[npm-debug.txt](https://github.com/nodegit/nodegit/files/772936/npm-debug.txt)

**Comment by maxkorp** [comment]
node-pre-gyp clean is dying due to a permissions error somehow? I've never seen that.

**Comment by ajayshankarr1** [comment]
Any update on this issue? I am also facing the same error

**Comment by maxkorp** [comment]
Are you guys running this in an admin cmd? Or maybe have you tried at least once in an admin cmd? or maybe installed node in an admin cmd? 

This is definitely a strange issue, but it's also def perms. 

I would try deleting `E:\workSpaces\pageConfigManage\app\node_modules` (or whatever the path to the parent of nodegit) and maybe an `npm cache clean`? See if that works?

**Comment by saper** [comment]
Well, what kind of file system is E: ? Something remote, virtualized?

**Comment by liuyutao** [comment]
@saper windows.7

**Comment by saper** [comment]
Which filesystem (https://zh.m.wikipedia.org/wiki/文件系统)?

**Comment by winys** [comment]
Same error.

**Comment by jaden** [comment]
Just another data point, nodegit works without errors on Windows 7 using node v7.10.0 and npm v4.2.0.
