### ISSUE TITLE
Can't install on macOS sierra

### ISSUE THREAD

**Issue by s3131212** [nodegit/nodegit#1248]
I can't install NodeGit on macOS sierra. Used to work on El Capitan.

Here's the error message
```
AlleniMac:example allen$ npm install nodegit

> nodegit@0.18.0 install /Users/allen/Desktop/example/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/allen/Desktop/example/node_modules/nodegit/vendor/openssl/openssl
/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/allen/Desktop/example/node_modules/nodegit/vendor/openssl/openssl' }
/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/allen/Desktop/example/node_modules/nodegit/vendor/openssl/openssl
/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/allen/Desktop/example/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/allen/Desktop/example/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN enoent ENOENT: no such file or directory, open '/Users/allen/Desktop/example/package.json'
npm WARN example No description
npm WARN example No repository field.
npm WARN example No README data
npm WARN example No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "nodegit"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.18.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.18.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/allen/Desktop/example/npm-debug.log
AlleniMac:example allen$
```

Version Info:
```
AlleniMac:example allen$ node -v
v7.2.1
AlleniMac:example allen$ npm -v
3.10.9
AlleniMac:example allen$ node-gyp -v
v3.4.0
```

Since I haven't seen any similar issue, am I the only one who have problem installing NodeGit ? Any help is appreciated.

**Comment by rcjsuen** [comment]
Maybe try a `brew install libgcrypt`?

**Comment by s3131212** [comment]
It's working now. Thanks a lot!

**Comment by rcjsuen** [comment]
Sounds good! Please follow #1200 if you would like further updates on this issue, thanks.
