### ISSUE TITLE
Won't install on Amazon Linux

### ISSUE THREAD

**Issue by clearly** [nodegit/nodegit#1285]
Please advise what might be the issue?

-----------
````
> nodegit@0.18.3 install /home/me/projects/project/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /home/me/projects/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/me/projects/project/node_modules/nodegit/vendor/openssl/openssl
/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/me/projects/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/me/projects/project/node_modules/nodegit/vendor/openssl/openssl' }
/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /home/me/projects/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/me/projects/project/node_modules/nodegit/vendor/openssl/openssl
/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/me/projects/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/me/projects/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/me/projects/project/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN project@0.0.1 No repository field.
npm ERR! Linux 4.4.23-31.54.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.18.3 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/projects/project/npm-debug.log
````

**Comment by rcjsuen** [comment]
Maybe check #1134?
