### ISSUE TITLE
Building nodegit fails

### ISSUE THREAD

**Issue by anonrig** [nodegit/nodegit#1306]
I've tried to add globally eslint using `yarn global add eslint`.

My NPM version is 5.0.0
My node version is 8.0.0
This is the error message i get

```
../vendor/libssh2/src/misc.c:205:19: warning: unused variable 'base64_table' [-Wunused-const-variable]
static const char base64_table[] =
                  ^
../vendor/libssh2/src/misc.c:214:19: warning: unused variable 'base64_pad' [-Wunused-const-variable]
static const char base64_pad = '=';
                  ^
2 warnings generated.
  CC(target) Release/obj.target/libssh2/vendor/libssh2/src/pem.o
  CC(target) Release/obj.target/libssh2/vendor/libssh2/src/session.o
  CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
  LIBTOOL-STATIC Release/ssh2.a
  CXX(target) Release/obj.target/nodegit/src/lock_master.o
  CXX(target) Release/obj.target/nodegit/src/nodegit.o
  CXX(target) Release/obj.target/nodegit/src/init_ssh2.o
  CXX(target) Release/obj.target/nodegit/src/promise_completion.o
  CXX(target) Release/obj.target/nodegit/src/wrapper.o
  CXX(target) Release/obj.target/nodegit/src/functions/copy.o
  CXX(target) Release/obj.target/nodegit/src/functions/sleep_for_ms.o
  CXX(target) Release/obj.target/nodegit/src/convenient_patch.o
  CXX(target) Release/obj.target/nodegit/src/convenient_hunk.o
  CXX(target) Release/obj.target/nodegit/src/str_array_converter.o
  CXX(target) Release/obj.target/nodegit/src/thread_pool.o
  CXX(target) Release/obj.target/nodegit/src/annotated_commit.o
../src/annotated_commit.cc:262:48: error: no member named 'GetHiddenValue' in 'v8::Object'
        Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                      ~~~~~~~  ^
../src/annotated_commit.cc:424:48: error: no member named 'GetHiddenValue' in 'v8::Object'
        Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                      ~~~~~~~  ^
../src/annotated_commit.cc:591:48: error: no member named 'GetHiddenValue' in 'v8::Object'
        Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                      ~~~~~~~  ^
../src/annotated_commit.cc:806:48: error: no member named 'GetHiddenValue' in 'v8::Object'
        Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                      ~~~~~~~  ^
4 errors generated.
make: *** [Release/obj.target/nodegit/src/annotated_commit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/anonrig/.config/yarn/global/node_modules/nodegit/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/anonrig/.nvm/versions/node/v8.0.0/bin/node" "/Users/anonrig/.config/yarn/global/node_modules/nodegit/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/anonrig/.config/yarn/global/node_modules/nodegit
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
1
1
```

**Comment by rcjsuen** [comment]
NodeGit does not currently build on Node 8. See #1295 and #1298.
