### ISSUE TITLE
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-darwin-x64.tar.gz 

### ISSUE THREAD

**Issue by schester44** [nodegit/nodegit#1310]
Getting this error while trying to install via npm:
npm version: 5.0.0
node version: 8.0.0

[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.18.3 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by schester44** [comment]
```
72 silly lifecycle nodegit@0.18.3~install: Args: [ '-c',
72 silly lifecycle   'node lifecycleScripts/preinstall && node lifecycleScripts/install' ]
73 silly lifecycle nodegit@0.18.3~install: Returned: code: 1  signal: null
74 info lifecycle nodegit@0.18.3~install: Failed to exec install script
75 verbose unlock done using /Users/schester/.npm/_locks/staging-27648e488feb0422.lock for /Applications/MAMP/htdocs/template_manager/node_modules/.staging
76 verbose stack Error: nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
76 verbose stack Exit status 1
76 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
76 verbose stack     at emitTwo (events.js:125:13)
76 verbose stack     at EventEmitter.emit (events.js:213:7)
76 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
76 verbose stack     at emitTwo (events.js:125:13)
76 verbose stack     at ChildProcess.emit (events.js:213:7)
76 verbose stack     at maybeClose (internal/child_process.js:887:16)
76 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
77 verbose pkgid nodegit@0.18.3
78 verbose cwd /Applications/MAMP/htdocs/template_manager
79 verbose Darwin 16.4.0
80 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "nodegit"
81 verbose node v8.0.0
82 verbose npm  v5.0.0
83 error code ELIFECYCLE
84 error errno 1
85 error nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
85 error Exit status 1
86 error Failed at the nodegit@0.18.3 install script.
```

**Comment by rcjsuen** [comment]
Please see #1295 and #1298.

**Comment by rfay** [comment]
@rcjsuen I'm assuming the reference to #1298 must not have been intentional as it's a long discussion about a feature improvement. Is this solved? Can you point me to it?

**Comment by rcjsuen** [comment]
@rfay It was intentional as it was related to getting NodeGit to build on Node 8.x. It was originally thought that #1298 was blocking #1295 but #1295 has been resolved recently so it seems it's actually possible to build NodeGit on 8.x.
