### ISSUE TITLE
installation Error under Ubuntu Bash -  Windows 10

### ISSUE THREAD

**Issue by stillday** [nodegit/nodegit#1316]
Hello, i have a installation problem with ubuntu bash under windows 10.
by the insallation runs all good, but by the end i get this error:
`> nodegit@0.19.0 install /mnt/d/adapt/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/mnt/d/adapt/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.19.0 postinstall /mnt/d/adapt/node_modules/nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ [Error: Command failed: /bin/sh -c node "/mnt/d/adapt/node_modules/nodegit/dist/nodegit.js"
/mnt/d/adapt/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: /mnt/d/adapt/node_modules/nodegit/build/Release/nodegit.node: cannot enable executable stack as shared object requires: Invalid argument
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/d/adapt/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/mnt/d/adapt/node_modules/nodegit/dist/nodegit.js"' }
npm WARN saveError ENOENT: no such file or directory, open '/mnt/d/adapt/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/mnt/d/adapt/package.json'
npm WARN adapt No description
npm WARN adapt No repository field.
npm WARN adapt No README data
npm WARN adapt No license field.

+ nodegit@0.19.0
added 124 packages in 268.772s`

How i can fix it?

**Comment by MartinMuzatko** [comment]
I can't install nodegit under WSL (ubuntu on windows) as well.
I get the following error: 

```bash
> nodegit@0.20.2 install /mnt/c/Users/Martin Muzatko/dev/bitbucket/sicon/server/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     '/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/openssl/openssl' ],
  cmd: '/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/openssl/openssl' }

[nodegit] ERROR - Could not finish preinstall
{ Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     '/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/openssl/openssl' ],
  cmd: '/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/github/nodegit/vendor/openssl/openssl' }
```

**Comment by MartinMuzatko** [comment]
The paths are wrong.
If I do `vendor/libssh2/configure --with-libssl-prefix=vendor/openssl/openssl` locally within `node_modules/nodegit` there is no problem

**Comment by spences10** [comment]
I also have this issue trying to install GitHub spellcheck https://github.com/tbroadley/github-spellcheck-cli/issues/36#issuecomment-355559149
