### ISSUE TITLE
Precompiled binaries not found & Compilation failing

### ISSUE THREAD

**Issue by gamelaster** [nodegit/nodegit#1334]
Why?
```bash
λ npm install nodegit --save

> nodegit@0.18.3 install C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-win32-x64.tar.gz node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.18.3 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\undefined'
gyp ERR! stack     at Object.fs.openSync (fs.js:652:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:553:33)
gyp ERR! stack     at readCAFile (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\nodegit\\build\\Release" "--python=python2.7" "--msvs_version=2015"
gyp ERR! cwd C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release --python=python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR!
stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp
ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release --python=python2.7 --msvs_version=2015' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.18.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamel\AppData\Roaming\npm-cache\_logs\2017-07-26T21_35_03_966Z-debug.log
```
With `--msvs_version=2017`:
```
λ npm install nodegit --msvs_version=2017 --save

> nodegit@0.18.3 install C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-win32-x64.tar.gz node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.18.3 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\undefined'
gyp ERR! stack     at Object.fs.openSync (fs.js:652:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:553:33)
gyp ERR! stack     at readCAFile (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\nodegit\\build\\Release" "--python=python2.7" "--msvs_version=2017"
gyp ERR! cwd C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release --python=python2.7 --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack
at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gamel\\Desktop\\codeplex-migration-tool\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\gamel\Desktop\codeplex-migration-tool\node_modules\nodegit\build\Release --python=python2.7 --msvs_version=2017' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.18.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamel\AppData\Roaming\npm-cache\_logs\2017-07-26T21_39_45_318Z-debug.log
```

**Comment by rcjsuen** [comment]
> Why?
Because you're on Node 8. See #1295 and #1298.
