### ISSUE TITLE
Installing nodegit via npm fails at Configuring libssh2.

### ISSUE THREAD

**Issue by timeo-schmidt** [nodegit/nodegit#1347]
When I try installing nodegit via npm it keeps throwing the following error. I tried the following:

`brew reinstall gcc`
I tried reinstalling node via brew and also via the node installer
`sudo xcode-select --install`

Is there anything else I can do? - Having the same issue even on other machines, all running MacOS Sierra.

My Node Version is: v6.11.2
My NPM Version is: 3.10.10

Console Output after `npm install nodegit`:

`[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: 
   [ '-c',
     '/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/openssl/openssl' }

[nodegit] ERROR - Could not finish preinstall
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: 
   [ '-c',
     '/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/timeoschmidt/Desktop/Freiheit\\ Praktikum/Node\\ Upload\\ Repo/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nodegit"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.18.3 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timeoschmidt/Desktop/Freiheit Praktikum/Node Upload Repo/npm-debug.log`

( If I am running the same command with global -g argument, it seems to install without errors, but my scripts using nodegit still throw the error: `Error: Cannot find module 'nodegit'` ).

I would really appreciate help or references to other issues with things I can try.

**Comment by SarahAlphaSoftware** [comment]
I am trying to install nodegit via npm and get the same error:

```
$ npm install nodegit
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
\
> nodegit@0.20.1 install C:\dev\AlphaHelp\helpserver\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.1-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.20.1 and node@4.4.2 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp

ERR! configure error
gyp
ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-gyp\lib\configure.js:508:16)
gyp
ERR! stack     at C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\AlphaHelp\\helpserver\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\dev\\AlphaHelp\\helpserver\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\dev\\AlphaHelp\\helpserver\\node_modules\\nodegit\\build\\Release"
gyp ERR!
cwd C:\dev\AlphaHelp\helpserver\node_modules\nodegit
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\dev\AlphaHelp\helpserver\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\dev\AlphaHelp\helpserver\node_modules\nodegit\build\Release' (1)
node-pre-gyp
ERR! stack     at ChildProcess.<anonymous> (C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp
ERR! System Windows_NT 10.0.15063
node-pre-gyp
ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\AlphaHelp\\helpserver\\node_modules\\nodegit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\dev\AlphaHelp\helpserver\node_modules\nodegit
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp
ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\AlphaHelp\helpserver\node_modules\nodegit\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\dev\AlphaHelp\helpserver\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\dev\AlphaHelp\helpserver\node_modules\nodegit\build\Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodegit"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.20.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.20.1 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\AlphaHelp\helpserver\npm-debug.log
```

**Comment by MartinMuzatko** [comment]
no. Doing --save does not fix it for me. I still get 
```js
[nodegit] Configuring libssh2.
{ Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     'server/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/bitbucket/sic
on/server/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: 'server/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/bitbucket/s
icon/server/node_modules/nodegit/vendor/openssl/openssl' }

[nodegit] ERROR - Could not finish preinstall
{ Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     'server/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/bitbucket/sic
on/server/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: 'server/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/mnt/c/Users/Martin\\ Muzatko/dev/bitbucket/s
icon/server/node_modules/nodegit/vendor/openssl/openssl' }
```

**Comment by ThiagoDallacqua** [comment]
```sh
> nodegit@0.20.1 install /path_of_my_project/node_modules/nodegit                              

> node lifecycleScripts/preinstall && node lifecycleScripts/install                                                                                                                                                                             

[nodegit] Running pre-install script                                                                                    

[nodegit] Configuring libssh2.                                                                                         

{ Error: Command failed: /path_of_my_project/node_modules/nodegit/vendor

/libssh2/configure 

--with-libssl-prefix=/path_of_my_project/node_modules/nodegit/vendor/openssl/openssl               

/path_of_my_project/node_modules/nodegit/vendor/libssh2/missing: 

Unknown `--is-lightweight' option                                                                                                                     

Try `/path_of_my_project/node_modules/nodegit/vendor

/libssh2/missing --

help' for more information                                                                                                                      

configure: WARNING: 'missing' script is too old or missing  rm: 

cannot remove 'conftest': Input/output error configure: 

error: No crypto library found!  

Try --with-libssl-prefix=PATH  or --with-libgcrypt-prefix=PATH or --with-wincng on Windows                                                                                                                                                                                                                        

at ChildProcess.exithandler (child_process.js:275:12) 

at emitTwo (events.js:126:13)  

at ChildProcess.emit (events.js:214:7)                                                                                 

at maybeClose (internal/child_process.js:925:16)                                                                       

at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)                                              

killed: false,                                                                                                          

code: 1,                                                                                                                

signal: null,                                                                                                           

cmd: '/path_of_my_project/node_modules/nodegit/vendor

/libssh2/configure 

--with-libssl-prefix=/path_of_my_project/node_modules/nodegit/vendor/openssl/openssl' 

}/path_of_my_project/nodegit/vendor/libssh2/missing: 

Unknown `--is-lightweight' option                                                                                                                     

Try `/path_of_my_project/node_modules/nodegit/vendor

/libssh2/missing --

help' for more information                                                                                                                      

configure: WARNING: 'missing' script is too old or missing                                                              

rm: cannot remove 'conftest': Input/output error                                                                        

configure: error: No crypto library found!                                                                              

Try --with-libssl-prefix=PATH                                                                                            

or --with-libgcrypt-prefix=PATH                                                                                         

or --with-wincng on Windows                                                                                                                                                                                                                    

[nodegit] ERROR - Could not finish preinstall                                                                           

{ Error: Command failed: /path_of_my_project/node_modules/nodegit/vendor/libssh2/configure 

--with-libssl-prefix=/path_of_my_project/node_modules/nodegit/vendor

/openssl/openssl               

/path_of_my_project/node_modules/nodegit/vendor/libssh2/missing: 

Unknown `--is-lightweight' option                                                                                                                     

Try `/path_of_my_project/node_modules/nodegit/vendor

/libssh2/missing --

help' for more information                                                                                                                      

configure: WARNING: 'missing' script is too old or missing                                                              

rm: cannot remove 'conftest': Input/output error                                                                       

configure: error: No crypto library found!                                                                           

Try --with-libssl-prefix=PATH                                                                                            

or --with-libgcrypt-prefix=PATH                                                                                         

or --with-wincng on Windows                                                                                                                                                                                                                        

at ChildProcess.exithandler (child_process.js:275:12)                                                                   

at emitTwo (events.js:126:13)                                                                                           

at ChildProcess.emit (events.js:214:7)                                                                                  

at maybeClose (internal/child_process.js:925:16)                                                                        

at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)                                              

killed: false,                                                                                                          

code: 1,                                                                                                                

signal: null,                                                                                                           

cmd: '/path_of_my_project/node_modules/nodegit/vendor

/libssh2/configure 

--with-libssl-prefix=/path_of_my_project/node_modules/nodegit/vendor/openssl/openssl' }

```

**Comment by rcjsuen** [comment]
@ThiagoDallacqua Are you on macOS Sierra?

**Comment by ThiagoDallacqua** [comment]
nope Ubuntu

**Comment by rcjsuen** [comment]
@ThiagoDallacqua Try `sudo apt-get install libssl-dev libcurl4-openssl-dev`.

If not, you could also try `sudo apt-get install curl libcurl3`.

**Comment by ThiagoDallacqua** [comment]
@rcjsuen it worked, but now the problem comes from `post-install`

```sh
[nodegit] WARN - Could not finish postinstall

{ Error: Command failed: node "/path_of_my_project/node_modules/nodegit/dist/nodegit.js"

/path_of_my_project/node_modules/nodegit/dist/nodegit.js:15

throw ex;

^

Error: /path_of_my_project/node_modules/nodegit/build/Release/nodegit.node: cannot enable

executable stack as shared object requires: Invalid argument 

at Object.Module._extensions..node (module.js:664:18)

at Module.load (module.js:554:32)

at tryModuleLoad (module.js:497:12)

at Function.Module._load (module.js:489:3)

at Module.require (module.js:579:17)

at require (internal/module.js:11:18)

at Object.<anonymous> (/path_of_my_project/node_modules/nodegit/dist/nodegit.js:11:12)

at Module._compile (module.js:635:30)

at Object.Module._extensions..js (module.js:646:10)

at Module.load (module.js:554:32)

at ChildProcess.exithandler (child_process.js:275:12)

at emitTwo (events.js:126:13)

at ChildProcess.emit (events.js:214:7)

at maybeClose (internal/child_process.js:925:16)

at Socket.stream.socket.on (internal/child_process.js:346:11)

at emitOne (events.js:116:13)

at Socket.emit (events.js:211:7)

at Pipe._handle.close [as _onclose] (net.js:554:12)

killed: false,

code: 1,

signal: null,

cmd: 'node "/path_of_my_project/node_modules/nodegit/dist/nodegit.js"' }
```

**Comment by rcjsuen** [comment]
@ThiagoDallacqua #1282 and Microsoft/WSL#916 looks related but not sure if they will be of any help to you.

**Comment by tamastimar** [comment]
Having the same (pre-install configuring of libssh2) issue in the following env:
- macOS Sierra 10.12.6
- node.js 6.11.1
- npm 3.10.10
- nodegit 0.20.3

Also tried with latest node 6.x and with installing libgcrypt package (as mentioned in other nodegit issues).

No luck yet.

**Comment by tamastimar** [comment]
After some debugging I've figured out that the problem occurs if there's space in the cwd path.

@timeo-schmidt: /Users/timeoschmidt/Desktop/**Freiheit Praktikum/Node Upload Repo**/(...)
@MartinMuzatko: /mnt/c/Users/**Martin Muzatko**/(...)

So I think the escaping [here](https://github.com/nodegit/nodegit/blob/master/lifecycleScripts/configureLibssh2.js#L5) maybe not perfect.

/cc @rcjsuen

**Comment by asfor** [comment]
I solved it on my computer, please try installing openssl.

**Comment by bjwyse** [comment]
Similar issue on Amazon Linux solved with:
`sudo yum install libgcrypt-devel`

**Comment by dylantmarsh** [comment]
@tamastimar This resolved the issue for me on macOS High Sierra 10.13.1

Thank you!

**Comment by arrra** [comment]
Running: macOS Sierra 

Ran `brew doctor` and got a warning saying to update xcode command line tools.
Worked after updating.

**Comment by laurentlouk** [comment]
There is a problem with spaces into the Path "\\ " and then the error appears.

**Comment by MartinMuzatko** [comment]
> Remove the spaces into your folder and it will work.

This is easily said but not easily done, especially when your path is relative to a given server hostname that decided that it needed spaces.

What is the proper way to escape that in the script?

**Comment by rlamb2** [comment]
@tamastimar solve worked for me on High Sierra, though I did run through all the libgcrypt and openssl reinstall steps first without success. So it's possible both fixes are required.

**Comment by eadz** [comment]
`brew install libgcrypt` was the fix for me

**Comment by gmwingard** [comment]
This error has come back in an update to Mac OS High Sierra 10.13.5. Using ```brew install libgcrypt``` no longer works as a fix. I've tried everything. Including installing xcode beta 10_2. The issue arose after an update to xcode command line tools that I've been unable to revert for some reason.

**Comment by MartinMuzatko** [comment]
I'm done with this shit. I will just use docker to deliver the environment nodegit needs.
That nobody took the time and fixed the script by escaping the path shows me how less the team cares about cross-platform adaptability.

I'm not the best with bash either, but this should suffice: https://apple.stackexchange.com/a/52485

**Comment by dvakatsiienko** [comment]
`sudo xcode-select --install` does not fix this any more on macOS Mojave

**Comment by biohazard999** [comment]
@dvakatsiienko I've the same issue, but I get all kind of weird permission denied errors, and brew cannot be run as sudo anymore. Ideas?

**Comment by dvakatsiienko** [comment]
@biohazard999 try to run `brew doctor` it will tell you issues and possible solutions.
Do you have `npm`-related permission issues? 
If so, it will also break nodegit. I mean `sudo npm install nodegit` will not work.
It will work only without `sudo`. If so, try [this guide](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to fix npm permissions

**Comment by biohazard999** [comment]
@dvakatsiienko Thanks, worked for me!

**Comment by maxkorp** [comment]
This _should_ be fixed in latest. Can someone try installing at `0.23.0-alpha.1`?

**Comment by Leekao** [comment]
I solved this issue by running "sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /" on my macOS.
