### ISSUE TITLE
building from source node 8.2.1 on a mac

### ISSUE THREAD

**Issue by shaunc** [nodegit/nodegit#1351]
I'm getting an error when running `node lifecycleScripts/install`:

```
CXX(target) Release/obj.target/nodegit/src/async_baton.o
c++: error: unrecognized command line option ‘-Wint-conversions’
c++: error: unrecognized command line option ‘-stdlib=libc++’
make: *** [Release/obj.target/nodegit/src/async_baton.o] Error 1

gyp

ERR!
build error
gyp
ERR! stack Error: `make` failed with exit code: 2
gyp ERR!
stack     at ChildProcess.onExit (/Volumes/Macintosh_HD/Users/shauncutts/.config/yarn/global/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR!
stack     at emitTwo (events.js:125:13)
gyp ERR!
stack
at ChildProcess.emit (events.js:213:7)
gyp
ERR!
stack
at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR!
System Darwin 16.7.0
gyp
ERR! command
"/usr/local/bin/node" "/Volumes/Macintosh_HD/Users/shauncutts/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--module=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release"
gyp
ERR!
cwd /Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit
gyp
ERR!
node -v v8.2.1
gyp
ERR!
node-gyp -v v3.6.2
gyp ERR!
not ok

node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/usr/local/bin/node /Volumes/Macintosh_HD/Users/shauncutts/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release' (1)
node-pre-gyp ERR! stack
at ChildProcess.<anonymous> (/Volumes/Macintosh_HD/Users/shauncutts/.config/yarn/global/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp
ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp
ERR!
stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp
ERR! stack
at maybeClose (internal/child_process.js:921:16)
node-pre-gyp
ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp
ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp
ERR! cwd
/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit
node-pre-gyp
ERR! node -v v8.2.1
node-pre-gyp
ERR! node-pre-gyp -v
v0.6.36
node-pre-gyp
ERR! not ok
Failed to execute '/usr/local/bin/node /Volumes/Macintosh_HD/Users/shauncutts/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Volumes/Macintosh_HD/Users/shauncutts/src/other/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by dolanmiu** [comment]
Read this:

https://github.com/nodegit/nodegit/issues/1334

**Comment by shaunc** [comment]
hmm... but https://github.com/nodegit/nodegit/issues/1295 at least reports that it does compile from source, it seems? ... (and that issue is closed)... just I haven't got my mind around how they do it. I don't know what "N-API" is ... ? Maybe I'll have to do some reading.
