### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by CrixuAMG** [nodegit/nodegit#1356]
```
bash-3.2$ npm install nodegit

> nodegit@0.20.1 install /Users/christian/Desktop/projects/FreshProject/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/openssl/openssl
/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/openssl/openssl' }
/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/openssl/openssl
/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/christian/Desktop/projects/FreshProject/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN freshproject@1.0.0 No description
npm WARN freshproject@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.20.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.20.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christian/.npm/_logs/2017-08-17T07_41_22_716Z-debug.log
```

Using latest stable version of Mac OS and latest versions of NPM&nodejs

**Comment by exPHAT** [comment]
I solved from following the answer in https://github.com/nodegit/nodegit/issues/1248#issuecomment-285484545

**Comment by CrixuAMG** [comment]
Thanks! That solved it!
Maybe the README.md file should be updated for this?  Seems like a issue that is going to happen again and again.
