### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by manoj451** [nodegit/nodegit#1360]
i am trying to build a vscode extension the code is like this

```
var v= require('nodegit')
var vscode = require('vscode');
function activate() {
    console.log('Congratulations, your extension "gitn" is now active!');
    vscode.window.showInformationMessage('extensions')
}
exports.activate = activate;
function deactivate() {
}
exports.deactivate = deactivate;
```

the stacktrace on running is

`Here is the error stack:  Error: A dynamic link library (DLL) initialization routine failed.
\\?\c:\Users\manojkumar.veeranala\Desktop\newExtension\gitn\node_modules\nodegit\build\Release\nodegit.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.K.G.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:404827)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\manojkumar.veeranala\Desktop\newExtension\gitn\node_modules\nodegit\dist\nodegit.js:11:12)`

if I remove the 1st line i get no error, I think there is a bug with nodegit can any one help me out with this

**Comment by saper** [comment]
What happens probably is that you have built your extension with a different version of node and VS is using some version of elderly trim when running.

**Comment by manoj451** [comment]
I have this problem when using nodegit in extension. But, when i used it in a normal .js application it is working fine. i donot know what the problem is.........
vs code: 1.15.1
npm : 5.3.0
Thanks sapper....

**Comment by joshsten** [comment]
Same here.
