### ISSUE TITLE
Building from npm fails at current Ubuntu

### ISSUE THREAD

**Issue by Fohlen** [nodegit/nodegit#1385]
Building from npm fails with the following configuration

- Ubuntu 16.04.03
- Node v8.6.0
- npm 5.4.2
- `build-essential` and `libssl-dev` installed

The error message is:
```
> nodegit@0.17.0 install /usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/openssl/openssl' }
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/@inexorgame/inexor-flex/node_modules/nodegit/vendor/openssl/openssl' }
```

**Comment by Fohlen** [comment]
Just found in the commit log that `8.4.0` is currently broken.
You should use the `engines` tag to indicate this, and also add it to the documentation.

**Comment by cold-logic** [comment]
Seeing this error on macOS as well. Running High Sierra with Node v8.7.0

**Comment by opeltre** [comment]
Hi I have exactly the same error on arch linux, node 9.2.0 / npm 5.6.0 when I run:
 `# npm i -g nodegit`

But I tried a local install as well and it's quite more verbose without the `-g` tag:

I first had complains about the absence of a suitable C compiler, so installed `gcc`,
and referring to #1166 I installed `libgcrypt` and reinstalled `openssl` 

I get:

```
> nodegit@0.20.3 install /home/shevket/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp

ERR!

Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-linux-x64.tar.gz

node-pre-gyp

ERR!

Pre-built binaries not found for nodegit@0.20.3 and node@9.2.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)

gyp

ERR!

build error
...
```
[Full error message here](https://github.com/nodegit/nodegit/files/1524316/log.txt)

**Comment by opeltre** [comment]
Hum the local install is probably not linked actually...it seems libssh2 configures properly and the error comes later... :)  
I confirm I have the same with `-g` though

**Comment by jmatsushita** [comment]
The permission denied error seems to be linked to npm running as user `nobody` which is discussed in this article: https://medium.com/@aguidrevitch/when-installation-of-global-package-using-npm-inside-docker-fails-b551b5dda389
