### ISSUE TITLE
Install failure on node 9.2.0

### ISSUE THREAD

**Issue by reggi** [nodegit/nodegit#1408]
```
➜  npm i nodegit --save

> nodegit@0.20.3 install /Users/thomas/Desktop/project/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/thomas/Desktop/project/node_modules/nodegit/vendor/openssl/openssl
/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/thomas/Desktop/project/node_modules/nodegit/vendor/openssl/openssl' }
/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/thomas/Desktop/project/node_modules/nodegit/vendor/openssl/openssl
/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/thomas/Desktop/project/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/thomas/Desktop/project/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN enoent ENOENT: no such file or directory, open '/Users/thomas/Desktop/project/package.json'
npm WARN project No description
npm WARN project No repository field.
npm WARN project No README data
npm WARN project No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.20.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.20.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2017-12-07T05_13_08_386Z-debug.log
```

**Comment by reggi** [comment]
Seems connected to https://github.com/nodegit/nodegit/issues/1134
