### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jpatters** [nodegit/nodegit#1410]
```
TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
      
      at processExports (node_modules/promisify-node/index.js:44:16)
      at Object.<anonymous>.module.exports (node_modules/promisify-node/index.js:112:10)
      at Object.<anonymous> (node_modules/nodegit/dist/nodegit.js:131:26)
```

Getting this error if I import the package but it's only happening when running tests. I know this isn't much information to go on but I really don't know what the issue could be. Happy to answer questions.

**Comment by jpatters** [comment]
This is actually caused by an issue in jest
For reference: https://github.com/facebook/jest/issues/3552

**Comment by securelyshare-madhura-b** [comment]
UserActivitiesListingComponent.html:237 ERROR TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at DynamicListingComponent.push../src/app/shared/dynamic-listing/dynamic-listing.component.ts
