### ISSUE TITLE
Segmentation fault errno 139

### ISSUE THREAD

**Issue by Foxhunt** [nodegit/nodegit#1435]
Hi,

running into a 139 error when using nodegit. 

Not sure if this is a problem with nan or nodegit.

In our app nodegit is the only module that has a dependency on nan.
The app is running in a docker container based on the Dockerfile in  https://github.com/artcom/git-json-api.

npm start logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle git-json-api@0.1.0~prestart: git-json-api@0.1.0
6 silly lifecycle git-json-api@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle git-json-api@0.1.0~start: git-json-api@0.1.0
8 verbose lifecycle git-json-api@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle git-json-api@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle git-json-api@0.1.0~start: CWD: /app
11 silly lifecycle git-json-api@0.1.0~start: Args: [ '-c', 'node src/main.js' ]
12 silly lifecycle git-json-api@0.1.0~start: Returned: code: 139  signal: null
13 info lifecycle git-json-api@0.1.0~start: Failed to exec start script
14 verbose stack Error: git-json-api@0.1.0 start: `node src/main.js`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid git-json-api@0.1.0
16 verbose cwd /app
17 verbose Linux 4.9.60-linuxkit-aufs
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 139
23 error git-json-api@0.1.0 start: `node src/main.js`
23 error Exit status 139
24 error Failed at the git-json-api@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 139, true ]
```
Running `node src/main.js` instead of `npm start` shows:

``` bash
node: ../node_modules/nan/nan_object_wrap.h:33: static T *Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [T = GitOid]: Assertion `object->InternalFieldCount() > 0' failed.
```

**Comment by rcjsuen** [comment]
I take it that this bug is easily reproducible?

**Comment by Foxhunt** [comment]
Not quite, took me a day to find a way to reproduce the bug with only the api.
The api is intended to run in a CMS Environment.

You need a local git repo with some content.

For example: https://github.com/artcom/eppsa-mobile-game-cms-content

**steps to reproduce:**

start the api with a pointer to the content repo

```
REPO_URI=file://<path-to-repo> node src/main.js
```

get the content via http from 

```
http://localhost:3000/master/content/
```
The response will be a JSON object representing the current content state.
The response also contains a custom "git-commit-hash" header with the latest commit hash.
Use it to post the altered content back to the api.

```
http://localhost:3000/<latest-commit-hash>/content
```

Normally this should create a commit and write the altered content to the filesystem.

The segmentation fault should happen in _src/lock.js_ -> objectToTree()
There is no stack trace. The process just exits with "Segmentation fault: 11".
From this i can't tell if this is a bug with nodegit or if we are using it wrong.
Updating nodegit to 0.20.3 and node to 8.9.4 did not help.

Running this on macOS with `npm start` sometimes shows:
```
Assertion failed: (data), function git_buf_put, file ../vendor/libgit2/src/buffer.c, line 213.
```

I hope all this is useful Information.

Note that we rolled master on https://github.com/artcom/git-json-api back to the last known working commit.

The broken version was moved to the "feature/fix-issue-1" branch.

**Comment by rcjsuen** [comment]
@Foxhunt What I meant was are you able to reproduce it 100% of the time?

**Comment by Foxhunt** [comment]
Now i am yes.

**Comment by vipi040480** [comment]
#1485 I am also getting the same error consistently in docker container.

**Comment by DavidIAm** [comment]
Reliable way to recreate this kind of error.  Yes, this code is fairly nonsensical - you can't nameToId on a repo that is fresh inited meaningfully - but the right answer here is null, not cored dump.

const Git = require('nodegit');
Git.Reference.nameToId(Git.Repository.init(uuid(), 0), 'HEAD');

I had discovered this when writing some code that auto-creates a repo if it doesn't exist, and was attempting to do a lookup in another context and fail over to no parent ref when there is none returned from the lookup.  But, Alas, doing a lookup in that situation causes the core dump.

**Comment by implausible** [comment]
@DavidIAm You're passing a promise into an function that expects a Repository as the first argument.

You will want to:
```javascript
const Git = require('nodegit')
async function getOidOfHead() {
  const repo = await Git.Repository.init(uuid(), 0);
  return Git.Reference.nameToId(repo, 'HEAD');
}
```

Though I suspect this will not work as an empty repo will not have a valid HEAD reference.

**Comment by DavidIAm** [comment]
its not SUPPOSED to work.  What its *not* supposed to do (EVER) is core dump. If I pass not-a-repo its supposed to throw some error, not throw a core dump, crashing everything. I have a .catch there for a reason, right? 

You're right though, it works better with the repo properly there.  I wonder why my code was failing... as it wasn't the minimal case I exampled with.

**Comment by implausible** [comment]
I see. It would be nice if it acted like a typical javascript error; however, I don't think it is my immediate concern to improve the incorrect use of our library. If you feel like this issue in particular is _completely unacceptable_, I would advise starting in https://github.com/nodegit/nodegit/blob/master/generate/templates/partials/guard_arguments.cc
