### ISSUE TITLE
nodegit does not work as service using node-windows with windows

### ISSUE THREAD

**Issue by mfechner** [nodegit/nodegit#1437]
Dear all,

I addressed this problem also here: coreybutler/node-windows#202 to make sure it is not a bug in node-windows.
The problem is if nodegit is started as a service on windows it gives the following error:

```
C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\nodegit.js:825
      throw unhandledException;
      ^

TypeError: Cannot read property '1' of null
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\utils\args.js:9:63)
    at C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:79:29
    at Array.filter (<anonymous>)
    at processExports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:60:6)
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:112:10)
    at Object.<anonymous> (C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\repository.js:6:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\nodegit.js:825
      throw unhandledException;
      ^

TypeError: Cannot read property '1' of null
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\utils\args.js:9:63)
    at C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:79:29
    at Array.filter (<anonymous>)
    at processExports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:60:6)
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:112:10)
    at Object.<anonymous> (C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\repository.js:6:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\nodegit.js:825
      throw unhandledException;
      ^

TypeError: Cannot read property '1' of null
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\utils\args.js:9:63)
    at C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:79:29
    at Array.filter (<anonymous>)
    at processExports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:60:6)
    at module.exports (C:\Applications\nodegit_node-windows\node_modules\promisify-node\index.js:112:10)
    at Object.<anonymous> (C:\Applications\nodegit_node-windows\node_modules\nodegit\dist\repository.js:6:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
C:\Applications\nodegit_node-windows\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Applications\nodegit_node-windows\node_modules\node-windows\lib\wrapper.js:177:11)
    at process.emit (events.js:160:13)
    at process.exit (internal/process.js:147:15)
    at monitor (C:\Applications\nodegit_node-windows\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\Applications\nodegit_node-windows\node_modules\node-windows\lib\wrapper.js:170:5)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

You can find a minimum example and detailed steps to reproduce it here:
https://gitlab.fechner.net/mfechner/nodegit_node-windows

Is this a bug that is related to nodegit?

**Comment by mfechner** [comment]
Fixed by: https://github.com/coreybutler/node-windows/issues/202
