### ISSUE TITLE
preinstall fails on osx 10.12.6 in subdirectory path with spaces

### ISSUE THREAD

**Issue by skokenes** [nodegit/nodegit#1440]
Hi, on OSX 10.12.6, if you try to run `npm i nodegit` in a directory that has spaces in its path name, the preinstall fails.

```
Speros:create-axis-app skokenes$ npm i nodegit -S

> nodegit@0.20.3 install /Users/skokenes/Documents/Client/Axis Group/create-axis-app/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: 
   [ '-c',
     '/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/openssl/openssl' }

[nodegit] ERROR - Could not finish preinstall
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: 
   [ '-c',
     '/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/skokenes/Documents/Client/Axis\\ Group/create-axis-app/node_modules/nodegit/vendor/openssl/openssl' }
```

**Comment by skhrolenok** [comment]
Try to install `libgcrypt`, worked for me on macOS
`brew install libgcrypt`

https://github.com/nodegit/nodegit/issues/1037

**Comment by rmccue** [comment]
Also experiencing this, and installing `libgcrypt` does not work.

The issue in my case appears to be that the path is double escaped:
```
cmd: '/Users/rmccue/My\\\\ Directory/...'
```
