### ISSUE TITLE
Error: spawn git-upload-pack ENOENT running command git-upload-pack

### ISSUE THREAD

**Issue by netlander** [nodegit/nodegit#1451]
When running a fresh install on Win 10, the commit goes well but I get the above error after trying to access the repo:
```
$ git clone http://localhost:7005/repo-test master
Cloning into 'master'...
fatal: unable to access 'http://localhost:7005/repo-test/': Recv failure: Connection was reset
```

The error coming from the server:

```
fetch repo-test
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn git-upload-pack ENOENT running command git-upload-pack --stateless-rpc --advertise-refs G:\src\web\portal-development\demos\node-git-server-master\example\tmp\repo-test
    at ChildProcess.ps.on (G:\src\web\portal-development\demos\node-git-server-master\lib\util.js:90:29)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

Any pointers as to what is going wrong?

Thanks

**Comment by rcjsuen** [comment]
@netlander How is this error related to NodeGit? It sounds to me like you are using [node-git-server](https://github.com/gabrielcsapo/node-git-server)?

**Comment by netlander** [comment]
Indeed, apologies for the confusion ;-)
