### ISSUE TITLE
NodeGit cannot be mocked in Jest

### ISSUE THREAD

**Issue by axiac** [nodegit/nodegit#1514]
Trying to mock NodeGit in Jest fails with the following error message:

>     TypeError: Cannot set property 'lookupWrapper' of undefined

The code of the test:

    var nodegit = require('nodegit');
    jest.mock('nodegit');

    describe('mocking nodegit', () => {
        it("doesn't work", () => {
            console.log('it never reaches this point.');
        });
    });

Its output is:

    $ jest nodegit-mock.spec.js
     FAIL  ./nodegit-mock.spec.js
      ● Test suite failed to run
    
        TypeError: Cannot set property 'lookupWrapper' of undefined

        > 1 | var nodegit = require('nodegit');
            |               ^
          2 | jest.mock('nodegit');
          3 |
          4 | describe('mocking nodegit', () => {

          at Object.<anonymous> (node_modules/nodegit/dist/utils/lookup_wrapper.js:41:29)
          at Object.<anonymous> (nodegit-mock.spec.js:1:15)

    Test Suites: 1 failed, 1 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        0.812s
    Ran all test suites matching /nodegit-mock.spec.js/i.

**Comment by axiac** [comment]
@prashant-andani Just Jest and Node (version 8), no React, nothing else. All the dependencies declared in `package.json` are listed in my post above.

**Comment by sparcs360** [comment]
Instead of...

```
var nodegit = require('nodegit');
jest.mock('nodegit');
```
try...
```
var mock = jest.genMockFromModule('nodegit');
mock.Utils = {};
var nodegit = require('nodegit');
```

**Comment by bratter** [comment]
@axiac I know its a bit late, but I was having the same issue and solved it using a [manual mock](https://jestjs.io/docs/en/manual-mocks).

```js
const nodegit = jest.genMockFromModule('nodegit');

// Implement custom mock logic here

module.exports = nodegit;
```

I also added some custom mock logic so that the static methods `Repository.init` and `Repository.open` returned instances of the mocked class.

```js
import { Repository } from 'nodegit';
nodegit.Repository.init.mockImplementation(() => Promise.resolve(new Repository()));
```

**Comment by ashblue** [comment]
I tried to fix this with a manual mock and it still crashes with the `lookupWrapper` error.

**Comment by nossbigg** [comment]
Alternatively, you can:
1. Create a `./nodegit-import.js` and re-export `nodegit` as a `default` export
2. Replace all imports of `nodegit` with `./nodegit-import`
3. During test, apply a `jest.mock` on `./nodegit-import.js` to mock it away
4. Apply your own desired mock behaviors with `jest.spyOn()`

`nodegit-import.js`

```javascript
// to overcome issues with mocking nodegit directly
// https://github.com/nodegit/nodegit/issues/1514
import Git from "nodegit";
export default Git;
```

`your-own-file.js`

```javascript
import Git from "./nodegit-import";
```

`your-own-file.test.js`

```javascript
import Git from "./nodegit-import";
jest.mock('./nodegit-import');

jest.spyOn(Git, 'Repository');
```
