### ISSUE TITLE
Nodegit doesn't work in electron

### ISSUE THREAD

**Issue by IdkGoodName** [nodegit/nodegit#1518]
```js
Git.Clone('https://github.com/CreatorVilius/testmodule', 'testmodule')
```
When i do this in example.js and i do `node example.js` it works fine

But when i use `example.js` in electron it says

```js
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\MyDir\node_modules\nodegit\build\Release\nodegit.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (MyDir\node_modules\nodegit\dist\nodegit.js:12:12)
    at Object.<anonymous> (MyDir\node_modules\nodegit\dist\nodegit.js:1145:3)
```

**Comment by mathe42** [comment]
When __dirname points to a folder in a .asar file it might not work... (maybe?). Try an absolut path...

**Comment by CreatorVilius** [comment]
It isn't in `.asar` archive tho...

**Comment by maxkorp** [comment]
Did you compile nodegit for electron? That seems like the error you get when it's compiled for node. It's a native module, and requires either preconfiguring an npmrc or using https://github.com/electron/electron-rebuild.

**Comment by maxime1992** [comment]
Just encountered the exact same issue.
Can't run nodegit inside electron.
Has anyone found a solution?
@maxkorp I tried electron-rebuild but it throws an error...

**Comment by Bear1110** [comment]
I have same issue recently.
Node : 11.12.0
nodegit : 0.24.1
electron : 4.0.7
OS:windows 10

Maybe some error in "zlib" when running "electron-rebuild -f -w nodegit".

**Comment by implausible** [comment]
@Bear1110 That is an unrelated manner from this issue.

**Comment by Bear1110** [comment]
I delete my comment.
