### ISSUE TITLE
Electron Cannot install on win10 node 8.11.3

### ISSUE THREAD

**Issue by Bear1110** [nodegit/nodegit#1528]
Today, I install my electron project by `npm install` .

```
An unhandled error occurred inside electron-rebuild
Warning: Missing input files:
E:\electron\GeekNote\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\bswap.h
E:\electron\GeekNote\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\merge_file.h
�b�o�Ӥ�פ��@���ظm�@�ӱM�סC�Y�n�ҥΥ���իءA�Х[�J "/m" �ѼơC
E:\electron\GeekNote\node_modules\nodegit\build\vendor\http_parser\http_parser.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��Ϻ
ФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\libgit2.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\libssh2.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\openssl\openssl.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\zlib.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\electron\GeekNote\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\electron\\GeekNote\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=nodegit" "--module_path=E:\\electron\\GeekNote\\node_modules\\nodegit\\build\\Release" "--host=https://nodegit.s3.amazonaws.com/nodegit/nodegit/"
gyp ERR! cwd E:\electron\GeekNote\node_modules\nodegit
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: Warning: Missing input files:
E:\electron\GeekNote\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\bswap.h
E:\electron\GeekNote\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\merge_file.h
�b�o�Ӥ�פ��@���ظm�@�ӱM�סC�Y�n�ҥΥ���իءA�Х[�J "/m" �ѼơC
E:\electron\GeekNote\node_modules\nodegit\build\vendor\http_parser\http_parser.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��Ϻ
ФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\libgit2.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\libssh2.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\openssl\openssl.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
E:\electron\GeekNote\node_modules\nodegit\build\vendor\zlib.vcxproj(20,3): error MSB4019: �䤣��פJ���M�� "E:\Microsoft.Cpp.Default.props"�C�нT�{ <Import> �ŧi������|���T�A�ӥB�ɮצs�b��ϺФW�C
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\electron\GeekNote\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\electron\\GeekNote\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=nodegit" "--module_path=E:\\electron\\GeekNote\\node_modules\\nodegit\\build\\Release" "--host=https://nodegit.s3.amazonaws.com/nodegit/nodegit/"
gyp ERR! cwd E:\electron\GeekNote\node_modules\nodegit
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\electron\GeekNote\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (E:\electron\GeekNote\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (E:\electron\GeekNote\node_modules\rxjs\Subscriber.js:189:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! GeekNote@1.0.0 postinstall: `electron-rebuild -f -w nodegit`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the GeekNote@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bear\AppData\Roaming\npm-cache\_logs\2018-07-25T16_00_59_662Z-debug.log


```
npm 5.2.0
node  v8.11.3
win 10 

If I excute 'npm install nodegit' , it was fine.
However, when I start eletron.
![image](https://user-images.githubusercontent.com/14165451/43212889-c2ab10d6-9067-11e8-9c93-801cfff78f32.png)

It show error like the image.

How can I resolve it ?
Thanks

**Comment by Bear1110** [comment]
I suddenly build successfully. I don't know why..... So weird
