### ISSUE TITLE
Error when installating in a Docker container

### ISSUE THREAD

**Issue by VictorQueiroz** [nodegit/nodegit#1533]
I tried a fresh install of the library in `node:8.11.3`, `node` and `debian:sid` containers. but I get the same error in all of them, all dependencies were installed correctly, not sure if this is a bug in the library:

```
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/crypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/keepalive.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/libgcrypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/openssl.o
../vendor/libssh2/src/openssl.c: In function '_libssh2_rsa_new':
../vendor/libssh2/src/openssl.c:71:11: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
     (*rsa)->e = BN_new();
           ^~
../vendor/libssh2/src/openssl.c: In function '_libssh2_dsa_new':
../vendor/libssh2/src/openssl.c:130:14: error: dereferencing pointer to incomplete type 'DSA {aka struct dsa_st}'
     (*dsactx)->p = BN_new();
              ^~
../vendor/libssh2/src/openssl.c: In function '_libssh2_dsa_sha1_verify':
../vendor/libssh2/src/openssl.c:156:13: error: storage size of 'dsasig' isn't known
     DSA_SIG dsasig;
             ^~~~~~
../vendor/libssh2/src/openssl.c:156:13: warning: unused variable 'dsasig' [-Wunused-variable]
In file included from /root/.node-gyp/10.8.0/include/node/openssl/asn1.h:24:0,
                 from /root/.node-gyp/10.8.0/include/node/openssl/rsa.h:16,
                 from ../vendor/libssh2/src/openssl.h:42,
                 from ../vendor/libssh2/src/crypto.h:42,
                 from ../vendor/libssh2/src/libssh2_priv.h:140,
                 from ../vendor/libssh2/src/openssl.c:41:
../vendor/libssh2/src/openssl.c: In function '_libssh2_dsa_sha1_sign':
../vendor/libssh2/src/openssl.c:597:29: error: dereferencing pointer to incomplete type 'DSA_SIG {aka struct DSA_SIG_st}'
     r_len = BN_num_bytes(sig->r);
                             ^
/root/.node-gyp/10.8.0/include/node/openssl/bn.h:142:40: note: in definition of macro 'BN_num_bytes'
 # define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
                                        ^
In file included from /root/.node-gyp/10.8.0/include/node/openssl/asn1.h:16:0,
                 from /root/.node-gyp/10.8.0/include/node/openssl/rsa.h:16,
                 from ../vendor/libssh2/src/openssl.h:42,
                 from ../vendor/libssh2/src/crypto.h:42,
                 from ../vendor/libssh2/src/libssh2_priv.h:140,
                 from ../vendor/libssh2/src/openssl.c:41:
../vendor/libssh2/src/openssl.c: In function '_libssh2_pub_priv_keyfile':
/root/.node-gyp/10.8.0/include/node/openssl/bio.h:467:34: warning: value computed is not used [-Wunused-value]
 # define BIO_reset(b)            (int)BIO_ctrl(b,BIO_CTRL_RESET,0,NULL)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/libssh2/src/openssl.c:983:5: note: in expansion of macro 'BIO_reset'
     BIO_reset(bp);
     ^~~~~~~~~
../vendor/libssh2/src/openssl.c: In function '_libssh2_pub_priv_keyfilememory':
/root/.node-gyp/10.8.0/include/node/openssl/bio.h:467:34: warning: value computed is not used [-Wunused-value]
 # define BIO_reset(b)            (int)BIO_ctrl(b,BIO_CTRL_RESET,0,NULL)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/libssh2/src/openssl.c:1059:5: note: in expansion of macro 'BIO_reset'
     BIO_reset(bp);
     ^~~~~~~~~
vendor/libssh2.target.mk:126: recipe for target 'Release/obj.target/libssh2/vendor/libssh2/src/openssl.o' failed
make: Leaving directory '/opt/server/node_modules/nodegit/build'
make: *** [Release/obj.target/libssh2/vendor/libssh2/src/openssl.o] Error 1
gyp ERR!
build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/server/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Linux 4.17.11-arch1
gyp ERR! command
"/usr/local/bin/node" "/opt/server/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/server/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/opt/server/node_modules/nodegit/build/Release"
gyp ERR! cwd
/opt/server/node_modules/nodegit
gyp ERR! node -v
v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by VictorQueiroz** [comment]
It works if I install Node.JS v8.11.3 and don't install `libssl-dev` but `libssh-2-1-dev` instead
