### ISSUE TITLE
When I install a npm library which uses nodegit globally fails

### ISSUE THREAD

**Issue by kushwahashiv** [nodegit/nodegit#1537]
When I try to install @sample/abc globally in my macbook pro I get following error
```cmd
sudo npm install @sample/abc -g
```

above module I have written uses nodegit as a dependency.

# error log
 
```log
/usr/local/bin/myexe -> /usr/local/lib/node_modules/@sample/abc/build/bin/index.js

> nodegit@0.22.2 install /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl' }
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.22.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shiv/.npm/_logs/2018-08-17T16_30_57_898Z-debug.log
Shivs-MacBook-Pro:~ shiv$ sudo npm install @sample/abc -g
/usr/local/bin/myexe -> /usr/local/lib/node_modules/@sample/abc/build/bin/index.js

> nodegit@0.22.2 install /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl' }
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/@sample/abc/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.22.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shiv/.npm/_logs/2018-08-17T16_33_40_921Z-debug.log
```

**Comment by kushwahashiv** [comment]
any update on this please

**Comment by tagazok** [comment]
Would like an update on this also please

**Comment by kushwahashiv** [comment]
here is the workaround : Try running below command and update the xcode CLT
    ```cmd
    $ sudo xcode-select --install
    ```
Open xcode if installed just to configure setup above.
    
Permission issues on carol install command above in installation step
    1. Check User 
      ```cmd
      $ id -un
      $ <username>
      ```
    2 Give user directory `/usr/local/lib/node_modules` read/write access
      ```
      $ sudo chown -R <username> /usr/local/lib/node_modules
      ```
then you don't need sudo prefix

**Comment by maxkorp** [comment]
Yeah, node best practices are to not use sudo for global modules. 

I suspect this will still fail though. Can you try installing nodegit@0.23.0-alpha.1?
