### ISSUE TITLE
Installing another package often results in "Error: Cannot find module '../build/Debug/nodegit.node'"

### ISSUE THREAD

**Issue by garyking** [nodegit/nodegit#1550]
When I have `nodegit` as a package in one project, and I add another package to that project, about half the time, I'll get the following error when I try to run my project:

```
module.js:549
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/nodegit/dist/nodegit.js:19:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

To fix this, I delete `node_modules` dir and just re-install with Yarn using `yarn`.

**Comment by tilersmyth** [comment]
@garyking I'm noticing the same issue. Did you happen to figure out why this occurs?

When I install a new package I get the error that you indicated above. However, when I then delete that new package and reinstall a second time the error goes away. So basically, every other time I install the new package it prompts the error. 

I'm hoping for a better fix then the one you mentioned or the one I found as my project will often have users installing subsequent packages with Nodegit previously installed.

**Comment by kevsersrca** [comment]
I'm getting the same error while running it with node **v13.14.0**, npm **6.14.4** and yarn **1.22.4**  on was Ubuntu 18.04.3. 

Do you have any ideas how to solve this? Thank you!

**Comment by rcjsuen** [comment]
> I'm getting the same error while running it with node **v13.14.0**, npm **6.14.4** and yarn **1.22.4** on was Ubuntu 18.04.3.

@kevsersrca If you're using Node.js v13.x, you may want to take a look at #1753.

**Comment by kevsersrca** [comment]
> > I'm getting the same error while running it with node **v13.14.0**, npm **6.14.4** and yarn **1.22.4** on was Ubuntu 18.04.3.
> 
> @kevsersrca If you're using Node.js v13.x, you may want to take a look at #1753.

Thank you @rcjsuen but i already have this krb5-config. If I explain my problem in more detail, my problem is caused by the **node-gyp** package.

**Comment by rcjsuen** [comment]
@kevsersrca I guess my point was more that Node.js 13.x and 14.x is going to require some tinkering and you may be better off trying with Node.js 12.x.
