### ISSUE TITLE
crash during install leaves module in bad state that crashes node when required

### ISSUE THREAD

**Issue by michael-ts** [nodegit/nodegit#1573]
## System information
  - node version: 8.10.0
  - npm version: 6.2.0
  - OS/version/architechture: Linux 4.15.0-33-generic x64
  - Applicable nodegit version: 0.22.2

I'm unable to install, even to a virgin directory with an empty node_modules directory.   There is an error message about not being able to finish postinstall, followed by a segfault.  The install process then *claims* nodegit is installed, but any attempt to require it causes an immediate crash of node itself.

```
$ npm install nodegit

> nodegit@0.22.2 install /home/michael/tmp/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/home/michael/tmp/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.22.2 postinstall /home/michael/tmp/node_modules/nodegit
> node lifecycleScripts/postinstall

[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node "/home/michael/tmp/node_modules/nodegit/dist/nodegit.js"
Segmentation fault (core dumped)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 139,
  signal: null,
  cmd: 'node "/home/michael/tmp/node_modules/nodegit/dist/nodegit.js"' }
npm WARN saveError ENOENT: no such file or directory, open '/home/michael/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/michael/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ nodegit@0.22.2
added 138 packages from 98 contributors and audited 478 packages in 21.749s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
$ ls
node_modules  package-lock.json
$ node
> require("nodegit")
Segmentation fault (core dumped)

```

**Comment by michael-ts** [comment]
libssl-dev is already installed.

libcurl4-openssl-dev is installed.

**Comment by michael-ts** [comment]
I tried to [build from source](https://www.nodegit.org/guides/install/from-source/) and the build process completed with no errors.  However, I do not see mentioned in that document and it is not immediately obvious to me what to do once the build is complete to use nodegit.  I cannot require "nodegit" and there is no nodegit directory under node_modules.

**Comment by michael-ts** [comment]
when i try to run `npm test` I get this error, which seems like it might be a clue:

```
...
> jshint lib test/tests test/utils examples lifecycleScripts

/usr/bin/node: symbol lookup error: /tmp/nodegit/build/Release/nodegit.node: undefined symbol: CRYPTO_num_locks
npm ERR! Test failed.  See above for more details.

```

**Comment by maxkorp** [comment]
What linux are you on, more specifically?

**Comment by michael-ts** [comment]
@maxkorp LUbuntu 18.04.1

**Comment by michael-ts** [comment]
Anyone?

**Comment by michael-ts** [comment]
This was a cockpit problem, there were some updates which had tried to install but left the system in a bad state.  After a reboot and reinstall of the remaining updates nodegit now properly installs and I can use it in my module.
