### ISSUE TITLE
build nodegit failed with electron in windows 10

### ISSUE THREAD

**Issue by TerryChan** [nodegit/nodegit#1595]
## System information
  - node version: v10.13.0
  - npm version: 6.4.1
  - electron version: 3.0.10
  - OS/version/architecture: windows 10 1703
  - Applicable nodegit version: 0.23.0
  - visual studio version: 2017

It's 2018/12/7, I tried many times to install nodegit in my electron application, but all failed.
1. When I install nodegit without the .npmrc file mentioned [here](https://www.nodegit.org/guides/install/electron/), I can install successfully, and can use it in nodejs application. But if I run in electron application, I will got this crash #1034 
2. After I added the .npmrc in my root folder, then install the nodegit again, the nodegit build failed:

WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.23.0 and electron@3.0.10 (electron-v3.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 52.216.137.124:443
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error
gyp
ERR! stack Error: 404 response downloading http://npm.oa.com/mirrors/node/v3.0.10/iojs-v3.0.10-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\terry\AppData\Roaming\npm\node_modules\@tencent\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:214:14)
gyp ERR! stack     at Request.emit (events.js:187:15)
gyp ERR!
....
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.23.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Since this issue, I can't use nodegit in electron application. Does anyone know how to fix this issue? Or is there any method that I don't need to build nodegit, just use the pre-built nodegit?

**Comment by implausible** [comment]
Can you try this file?
```
