### ISSUE TITLE
nodegit fails to build if python version is >= 3

### ISSUE THREAD

**Issue by xobs** [nodegit/nodegit#1608]
## System information
  - node version: v11.6.0n
  - npm or yarn version: 6.5.0-next.0
  - OS/version/architecture: win32/10.0.16299/x64
  - Applicable nodegit version: 0.23.0

The `nodegit` package fails to build when trying to install using python3.  I'm using python 3.7.2:

```
[1:04:50 PM] ~/Code/Talks/reveal-serve> npm i nodegit

> nodegit@0.23.0 install C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.23.0-node-v67-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.23.0 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp
ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp
ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command
"C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\sean\\Code\\Talks\\reveal-serve\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\sean\\Code\\Talks\\reveal-serve\\node_modules\\nodegit\\build\\Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp
ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack
at ChildProcess.<anonymous> (C:\Users\sean\Code\Talks\reveal-serve\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sean\\Code\\Talks\\reveal-serve\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\sean\Code\Talks\reveal-serve\node_modules\nodegit
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN reveal-serve@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.23.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sean\AppData\Roaming\npm-cache\_logs\2019-01-11T05_07_30_900Z-debug.log
[1:07:30 PM] ~/Code/Talks/reveal-serve>
```

Replacing this with python2 (by manipulating $PATH to place a python2 varsion first) fixes the build problem.

This should be fixed, as Python 2 is officially being deprecated at the end of this year.

**Comment by implausible** [comment]
You'll need to take this upstream as we do not control whether we're building with python 2 or 3. See https://github.com/nodejs/node-gyp

**Comment by xobs** [comment]
Alright, I was confused that Python was a requirement.  The front page says that it can be installed by running `npm install nodegit`, and doesn't mention anything about Python.

Now that I dig into `Building from source`, I see that it mentions Python2.7.  Maybe that should be brought out to the README file, since it's also required when installing via npm?

**Comment by smithmr** [comment]
I ran into this issue.
`npm config set python {path to python2.7}`
on windows try
`npm install --global --production windows-build-tools`
