### ISSUE TITLE
NodeGit Installation Error with gyp

### ISSUE THREAD

**Issue by david-kuehn** [nodegit/nodegit#1620]
## System information
  - node version: v10.15.1
  - npm or yarn version: v6.4.1
  - OS/version/architecture: Raspbian 9.6 on Raspberry Pi 2 B (ARM6)
  - Applicable nodegit version: 0.24.0

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```

Error is thrown after `sudo npm install nodegit`

```
> nodegit@0.24.0 install /nize/nize/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN
Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.24.0 and node@10.15.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN
Hit error EACCES: permission denied, mkdir '/nize/nize/node_modules/nodegit/build'

gyp

WARN
EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.1"
gyp

WARN EACCES attempting to reinstall using temporary dev dir "/nize/nize/node_modules/nodegit/.node-gyp"
gyp

WARN install got an error, rolling back install
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error
gyp
ERR!
stack Error: EACCES: permission denied, mkdir '/nize/nize/node_modules/nodegit/.node-gyp'
gyp ERR! System Linux 4.14.79+
gyp
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/nize/nize/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/nize/nize/node_modules/nodegit/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /nize/nize/node_modules/nodegit
gyp

ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR!

not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/nize/nize/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/nize/nize/node_modules/nodegit/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/nize/nize/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack
at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp
ERR! System Linux 4.14.79+
node-pre-gyp ERR!
command
"/usr/local/bin/node" "/nize/nize/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /nize/nize/node_modules/nodegit
node-pre-gyp
ERR!
node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp
ERR!
not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/nize/nize/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/nize/nize/node_modules/nodegit/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN nize@1.0.0 No description
npm WARN nize@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.24.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.24.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-02T05_24_20_679Z-debug.log
```

Seems like it has something to do with `node-gyp` and/or `node-pre-gyp`.

**Comment by leedium** [comment]
Try node version 8.11.1

**Comment by balab2020** [comment]
@leedium our build servers uses Node Latest Stable version (10.15.0 as of now). It is difficult downgrade and use it.

Any other alternate?

**Comment by dzarezenko** [comment]
@balab2020 Hi, have you resolved this problem? I have the same issue.

**Comment by balab2020** [comment]
@dzarezenko, not solved I am planning to remove this dependency and use native git commands.

**Comment by david-kuehn** [comment]
@dzarezenko @balab2020 same here, looking at alternatives at this point

**Comment by SiRumCz** [comment]
Try python 2 instead of python 3 and see if it works.

**Comment by SiRumCz** [comment]
On my windows 10 I ran command ```npm install --global --production windows-build-tools``` to install the windows build tool and then switched to python2.7.16, these fixed my same issue.

**Comment by Maximebpro** [comment]
Thank you @SiRumCz. Saved my day!

**Comment by smithmr** [comment]
You need to make sure node knows where python 2.7 is.
`which python` - make sure its 2.7
`npm config set python {path to python2.7}`

**Comment by iandstanley** [comment]
same issue here in a DEBIAN  container on chromeos 


$ node -v
v10.16.3
$ npm -v
6.9.0
$ uname -a
Linux penguin 4.19.44-04937-gd773af751792 #1 SMP PREEMPT Thu Aug 8 21:43:29 PDT 2019 x86_64 GNU/Linux

installation attempted 
$ sudo npm  install nodegit


> nodegit@0.26.1 install /home/iandstanley/starlife-website/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.26.1 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/iandstanley/starlife-website/node_modules/nodegit/build'
gyp
WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/iandstanley/starlife-website/node_modules/nodegit/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/iandstanley/starlife-website/node_modules/nodegit/.node-gyp'
gyp ERR! System Linux 4.19.44-04937-gd773af751792
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/iandstanley/starlife-website/node_modules/nodegit
gyp
ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR!
build error
node-pre-gyp ERR!
stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR!
stack     at ChildProcess.<anonymous> (/home/iandstanley/starlife-website/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp
ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR!
stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp
ERR! System Linux 4.19.44-04937-gd773af751792
node-pre-gyp
ERR! command "/usr/bin/node" "/home/iandstanley/starlife-website/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/iandstanley/starlife-website/node_modules/nodegit
node-pre-gyp
ERR! node -v v10.16.3
node-pre-gyp
ERR! node-pre-gyp -v v0.13.0
node-pre-gyp
ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/iandstanley/starlife-website/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN vuepress-plugin-sitemap@2.1.2 requires a peer of esm@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.26.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.26.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-22T08_06_39_588Z-debug.log

**Comment by saitechnobrains** [comment]
+1

**Comment by saitechnobrains** [comment]
![Screenshot from 2019-09-28 13-47-19](https://user-images.githubusercontent.com/5346129/65813714-959fe800-e1f6-11e9-9db5-b3dfdf34633d.png)
Facing same issue while installing aws-amplify/cli. I am using node version v10.16.3 and npm version 
6.9.0. Any solution to fix this issue?

**Comment by kumarideepika** [comment]
> ![Screenshot from 2019-09-28 13-47-19](https://user-images.githubusercontent.com/5346129/65813714-959fe800-e1f6-11e9-9db5-b3dfdf34633d.png)
> Facing same issue while installing aws-amplify/cli. I am using node version v10.16.3 and npm version
> 6.9.0. Any solution to fix this issue?

same problem with me

**Comment by freesh** [comment]
Same issue.
Downgrade phyton to the stone age version shouldn't be the solution.
Wouldn't it be better to remove the unmaintained node-pre-gyp package and use @mapbox/node-pre-gyp instead?
