### ISSUE TITLE
electron-rebuild fail (zlib?) with nodegit 0.24.1 in Windows 10

### ISSUE THREAD

**Issue by Bear1110** [nodegit/nodegit#1665]
## System information
  - node version: 10.15.3
  - npm or yarn version: 6.5.0
  - OS/version/architecture: win10 / 17134.706 / x64
  - Applicable nodegit version: 0.24.1
 -  Electron : 4.0.7
---

The beginning of error message is below.
```
E:\electron\TESTFORBUILD>npm install

> tttt@1.0.0 postinstall E:\electron\TESTFORBUILD
> electron-rebuild -f -w nodegit

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
Warning: Missing input files:
E:\electron\TESTFORBUILD\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\bswap.h
E:\electron\TESTFORBUILD\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\merge_file.h
Warning: unrecognized tool include_dirs while converting to MSBuild.
Warning: unrecognized tool include_dirs while converting to MSBuild.
�b���ѨM��פ��@���ظm�@�ӱM�סC�Y�n�ҥΥ���ظm�A�зs�W "/m" �ѼơC
  Acquiring OpensSL binaries and headers
  { StatusCodeError: 404 - {"type":"Buffer","data":[84,104,101,32,114,101,113,117,101,115,116,101,100,32,112,97,116,104,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46]}
      at new StatusCodeError (E:\electron\TESTFORBUILD\node_modules\request-promise-core\lib\errors.js:32:15)
      at Request.plumbing.callback (E:\electron\TESTFORBUILD\node_modules\request-promise-core\lib\plumbing.js:104:33)
      at Request.RP$callback [as _callback] (E:\electron\TESTFORBUILD\node_modules\request-promise-core\lib\plumbing.js:46:31)
      at Request.self.callback (E:\electron\TESTFORBUILD\node_modules\request\request.js:185:22)
      at Request.emit (events.js:189:13)
      at Request.<anonymous> (E:\electron\TESTFORBUILD\node_modules\request\request.js:1161:10)
      at Request.emit (events.js:189:13)
      at Gunzip.<anonymous> (E:\electron\TESTFORBUILD\node_modules\request\request.js:1083:12)
      at Object.onceWrapper (events.js:277:13)
      at Gunzip.emit (events.js:194:15)
    name: 'StatusCodeError',
    statusCode: 404,
    message:
     '404 - {"type":"Buffer","data":[84,104,101,32,114,101,113,117,101,115,116,101,100,32,112,97,116,104,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46]}',
CUSTOMBUILD : error :  [E:\electron\TESTFORBUILD\node_modules\nodegit\build\acquireOpenSSL.vcxproj]
     <Buffer 54 68 65 20 72 65 71 75 65 73 74 65 64 20 70 61 74 68 20 77 61 73 20 6e 6f 74 20 66 6f 75 6e 64 2e>,
```
I skip some message in the middle.
The end of error message.

```
  trees.c
  zutil.c
  win_delay_load_hook.cc
  zlib.vcxproj -> E:\electron\TESTFORBUILD\node_modules\nodegit\build\Release\\zlib.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\electron\TESTFORBUILD\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\electron\\TESTFORBUILD\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.1.4" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=nodegit" "--module_path=E:\\electron\\TESTFORBUILD\\node_modules\\nodegit\\build\\Release" "--host=https://axonodegit.s3.amazonaws.com/nodegit/nodegit/" "--msvs_version=2015"
gyp ERR! cwd E:\electron\TESTFORBUILD\node_modules\nodegit
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\electron\TESTFORBUILD\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (E:\electron\TESTFORBUILD\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (E:\electron\TESTFORBUILD\node_modules\rxjs\internal\Subscriber.js:145:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! tttt@1.0.0 postinstall: `electron-rebuild -f -w nodegit`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the tttt@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bear\AppData\Roaming\npm-cache\_logs\2019-04-19T13_52_53_507Z-debug.log
```
Looks like "***zlib***" error ?

However, I can successfully build  it one mouth age.

If anyone can help me, I have been blocked for two days.

Thanks.

**Comment by implausible** [comment]
Conan moved the openssl binaries around. v0.24.2 is on the way with the corrected openssl binary locations.

**Comment by Bear1110** [comment]
By the way, I found that I also can't build sqlite3.And there is a same error.
So maybe , it is not problem with nodegit.
But I also hope some one can help me.
I ask this question to electron-rebuild.

**Comment by implausible** [comment]
Can you go ahead and update to 0.24.2 and see if that resolves your issues?

**Comment by Bear1110** [comment]
But I don't know how to use 0.24.2. Because ***npm*** only up to 0.24.1...

**Comment by implausible** [comment]
Conan moved the urls to the openssl binaries that we download and build against when building for electron. When those libraries didn't pull down, there must be some sort of bug in our build process that allowed the build to continue unabated. When the build tried to build something that actually used openssl (zlib), the symbols/headers were missing, so the build failed.

**Comment by Bear1110** [comment]
I appreciate your kind assistance.
