### ISSUE TITLE
Need to implement support for node 12

### ISSUE THREAD

**Issue by implausible** [nodegit/nodegit#1680]
We need to go through the deprecations list in the compilation phase of our node 10 builds and fix any and all deprecations so that we can update to node 12.

**Comment by HairyRabbit** [comment]
Any update here?

**Comment by implausible** [comment]
I don't have time to devote to moving on the node 12 update yet. My timeline is to get node 12 support before it enters active LTS.

**Comment by rickharris** [comment]
nodegit seems to be working in Abstract's electron app with node 12 / electron 5. Is there anything that isn't going to work that we should be concerned about?

Weirdly, although it compiles and runs on electron 5, it doesn't compile on electron 6, which also is on node 12.

**Comment by jclangst** [comment]
I am using node 12.4 and it appears to be failing from trying to build libssh2.

Here is a log of the relevant failure part: https://pastebin.com/mMbL9R3q

**Comment by implausible** [comment]
It gets through the libssh2 build correctly. It immediately fails after libssh2.a is generated. We have some compatibility issues to address with some API changes to node. These changes were recently made in another project of mine NSFW which covers node 12 support, so maybe that's all we're on the hook for in NodeGit as well:

https://github.com/Axosoft/nsfw/pull/76

**Comment by getify** [comment]
Would be really awesome for node 12 support to land. Hoping this happens soon.

**Comment by AddoSolutions** [comment]
Same issue here.  

```
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/knownhost.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/misc.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/pem.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/session.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
LIBTOOL-STATIC Release/ssh2.a
CXX(target) Release/obj.target/nodegit/src/async_baton.o
CXX(target) Release/obj.target/nodegit/src/lock_master.o
CXX(target) Release/obj.target/nodegit/src/reference_counter.o
CXX(target) Release/obj.target/nodegit/src/nodegit.o
../src/nodegit.cc:195:43: warning: 'ToInt32' is deprecated: Use maybe version [-Wdeprecated-declarations]
v8::Local<v8::Int32> value = info[0]->ToInt32(v8::Isolate::GetCurrent());
                                          ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2549:3: note: 'ToInt32' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/nodegit.cc:216:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
result->Set(Nan::New("storedMutexesCount").ToLocalChecked(), Nan::New(diagnostics.storedMutexesCount));
          ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/nodegit.cc:394:17: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  threadSafety->Set(Nan::New("DISABLED").ToLocalChecked(), Nan::New((int)LockMaster::Disabled));
                ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/nodegit.cc:395:17: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  threadSafety->Set(Nan::New("ENABLED_FOR_ASYNC_ONLY").ToLocalChecked(), Nan::New((int)LockMaster::EnabledForAsyncOnly));
                ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/nodegit.cc:396:17: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  threadSafety->Set(Nan::New("ENABLED").ToLocalChecked(), Nan::New((int)LockMaster::Enabled));
                ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/nodegit.cc:398:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  target->Set(Nan::New("THREAD_SAFETY").ToLocalChecked(), threadSafety);
          ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
6 warnings generated.
CXX(target) Release/obj.target/nodegit/src/init_ssh2.o
CXX(target) Release/obj.target/nodegit/src/promise_completion.o
../src/promise_completion.cc:12:40: error: too few arguments to function call, single argument 'context' was not specified
newFn.Reset(newTemplate->GetFunction());
              ~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/promise_completion.cc:14:88: error: too few arguments to function call, single argument 'context' was not specified
promiseFulfilled.Reset(Nan::New<v8::FunctionTemplate>(PromiseFulfilled)->GetFunction());
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/promise_completion.cc:15:86: error: too few arguments to function call, single argument 'context' was not specified
promiseRejected.Reset(Nan::New<v8::FunctionTemplate>(PromiseRejected)->GetFunction());
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/me/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/promise_completion.cc:24:65: error: no matching member function for call to 'ToObject'
    Nan::MaybeLocal<v8::Value> maybeThenProp = Nan::Get(result->ToObject(), Nan::New("then").ToLocalChecked());
                                                        ~~~~~~~~^~~~~~~~
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2546:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/promise_completion.cc:57:43: error: no matching member function for call to 'ToObject'
  v8::Local<v8::Object> promise = result->ToObject();
                                  ~~~~~~~~^~~~~~~~
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2546:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/promise_completion.cc:67:25: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  Nan::Callback(thenFn).Call(promise, 2, argv);
                        ^
../../nan/nan.h:1717:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/promise_completion.cc:81:29: error: too few arguments to function call, expected 4, have 3; did you mean 'Nan::Call'?
  return scope.Escape(bind->Call(Nan::New(function), 1, argv));
                            ^~~~
                            Nan::Call
../../nan/nan_maybe_43_inl.h:345:30: note: 'Nan::Call' declared here
inline MaybeLocal<v8::Value> Call(
                             ^
../src/promise_completion.cc:93:93: error: no matching member function for call to 'ToObject'
  PromiseCompletion *promiseCompletion = ObjectWrap::Unwrap<PromiseCompletion>(info.This()->ToObject());
                                                                               ~~~~~~~~~~~~~^~~~~~~~
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/me/.node-gyp/12.5.0/include/node/v8.h:2546:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
1 warning and 7 errors generated.
make: *** [Release/obj.target/nodegit/src/promise_completion.o] Error 1
gyp

ERR! build error
gyp ERR!
stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp
ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System
Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/me/Sites/lightspeed/crypto/node_modules/nodegit
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/Sites/lightspeed/crypto/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/me/Sites/lightspeed/crypto/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/me/Sites/lightspeed/crypto/node_modules/nodegit
node-pre-gyp ERR! node -v v12.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/me/Sites/lightspeed/crypto/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by tiggerite** [comment]
I've created a patch that can be run on the npm package and produces a working nodegit for at least Node 10.16 and 12.6 (all I've tested). However it patches the src folder which I can't find in GitHub anywhere. I guess it's generated from the generate folder somehow but I can't seem to figure out how? I'd like to make a PR for it..

**Comment by tiggerite** [comment]
@implausible there were a few more bits than NSFW had, but not many; ToObject, GetPropertyNames, BooleanValue and a couple of things in promise_completion only. There are still depreciation warnings with my PR but they don’t cause errors in the build, and everything seems to work.

**Comment by mittalyashu** [comment]
Not able install with node@12

```
$ yarn add nodegit
yarn add v1.16.0
warning package.json: License should be a valid SPDX license expression
warning thermal@0.0.4: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "nodegit > request-promise-native@1.0.7" has unmet peer dependency "request@^2.34".
warning "nodegit > request-promise-native > request-promise-core@1.1.2" has unmet peer dependency "request@^2.34".
[4/4] Building fresh packages...
error G:\thermal\thermal\node_modules\nodegit: Command failed.
Exit code: 1
Command: node lifecycleScripts/preinstall && node lifecycleScripts/install
Arguments:
Directory: G:\thermal\thermal\node_modules\nodegit
Output:
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp
info using node-pre-gyp@0.11.0
node-pre-gyp info
using node@11.10.1 | win32 | x64
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
info check checked for "G:\thermal\thermal\node_modules\nodegit\build\Release\nodegit.node" (not found)
node-pre-gyp
http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.3-node-v67-win32-x64.tar.gz
node-pre-gyp
http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.3-node-v67-win32-x64.tar.gz
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.3-node-v67-win32-x64.tar.gz
node-pre-gyp
WARN Pre-built binaries not found for nodegit@0.24.3 and node@11.10.1 (node-v67 ABI, unknown) (falling back to source compile
with node-gyp)
node-pre-gyp
http
404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.3-node-v67-win32-x64.tar
.gz
gyp

info it worked if it ends with ok
gyp

info

using
node-gyp@3.8.0
gyp

info

using
node@11.10.1 | win32 | x64
gyp
info ok
gyp

info
it worked if it ends with ok
gyp
info using node-gyp@3.8.0
gyp info
using node@11.10.1 | win32 | x64
gyp
info spawn C:\Users\YASHU\.windows-build-tools\python27\python.exe
gyp
info spawn args [ 'G:\\thermal\\thermal\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp
info spawn args   'binding.gyp',
gyp
info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args
'msvs_version=2015',
gyp info spawn args   '-I',
gyp
info spawn args   'G:\\thermal\\thermal\\node_modules\\nodegit\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info
spawn args   'G:\\thermal\\thermal\\node_modules\\node-gyp\\addon.gypi',
gyp
info spawn args   '-I',
gyp
info spawn args
'C:\\Users\\YASHU\\.node-gyp\\11.10.1\\include\\node\\common.gypi',
gyp info
spawn args   '-Dlibrary=shared_library',
gyp
info spawn args   '-Dvisibility=default',
gyp info spawn args
'-Dnode_root_dir=C:\\Users\\YASHU\\.node-gyp\\11.10.1',
gyp info
spawn args   '-Dnode_gyp_dir=G:\\thermal\\thermal\\node_modules\\node-gyp',
gyp
info spawn args   '-Dnode_lib_file=C:\\Users\\YASHU\\.node-gyp\\11.10.1\\<(target_arch)\\node.lib',
gyp
info spawn args   '-Dmodule_root_dir=G:\\thermal\\thermal\\node_modules\\nodegit',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args
'--depth=.',
gyp info
spawn args   '--no-parallel',
gyp info
spawn args   '--generator-output',
gyp
info spawn args   'G:\\thermal\\thermal\\node_modules\\nodegit\\build',
gyp info spawn args
'-Goutput_dir=.' ]
Warning: Missing input files:
G:\thermal\thermal\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\bswap.h
G:\thermal\thermal\node_modules\nodegit\build\vendor\..\..\vendor\libgit2\src\merge_file.h
gyp
info ok
gyp

info

it worked if it ends with
ok
gyp
info

using
node-gyp@3.8.0
gyp
info

using
node@11.10.1 | win32 | x64
gyp
info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args
'/clp:Verbosity=minimal',
gyp info
spawn args   '/nologo',
gyp info
spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\acquireOpenSSL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\configureLibssh2.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\vendor\http_parser\http_parser.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\vendor\libgit2.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\vendor\libssh2.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5)
: error MSB8036: The Windows SDK version 10.0.17763.0 was not found. Install the required version of Windows SDK or change the
 SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\thermal\th
ermal\node_modules\nodegit\build\vendor\zlib.vcxproj]
gyp
ERR! build error
gyp
ERR!
stack
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp

ERR! stack     at ChildProcess.onExit (G:\thermal\thermal\node_modules\node-gyp\lib\build.js:262:23)
gyp
ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp
ERR!
System Windows_NT 10.0.17134
gyp
ERR!
command
"C:\\Program Files\\nodejs\\node.exe" "G:\\thermal\\thermal\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-
build" "--module=G:\\thermal\\thermal\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_
path=G:\\thermal\\thermal\\node_modules\\nodegit\\build\\Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_vers
ion=0" "--node_napi_label=node-v67"
gyp
ERR!
cwd
G:\thermal\thermal\node_modules\nodegit
gyp ERR!
node -v v11.10.1
gyp ERR!
node-gyp -v v3.8.0
gyp ERR! not ok

node-pre-gyp

ERR!

build error

node-pre-gyp
ERR! stack
Error: Failed to execute 'C:\Program Files\nodejs\node.exe G:\thermal\thermal\node_modules\node-gyp\bin\node-gyp.js build --fa
llback-to-build --module=G:\thermal\thermal\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_pat
h=G:\thermal\thermal\node_modules\nodegit\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_na
pi_label=node-v67' (1)
node-pre-gyp
ERR!
stack
at ChildProcess.<anonymous> (G:\thermal\thermal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp

ERR!

stack
at ChildProcess.emit (events.js:197:13)
node-pre-gyp

ERR!
stack
at maybeClose (internal/child_process.js:984:16)
node-pre-gyp
ERR!
stack
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp

ERR!

System
Windows_NT 10.0.17134
node-pre-gyp

ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\thermal\\thermal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "inst
all" "--fallback-to-build"
node-pre-gyp

ERR!

cwd
G:\thermal\thermal\node_modules\nodegit
node-pre-gyp
ERR!
node -v
v11.10.1
node-pre-gyp
ERR!
node-pre-gyp -v
v0.11.0
node-pre-gyp
ERR!
not ok

Failed to execute 'C:\Program Files\nodejs\node.exe G:\thermal\thermal\node_modules\node-gyp\bin\node-gyp.js build --fallback-
to-build --module=G:\thermal\thermal\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=G:\th
ermal\thermal\node_modules\nodegit\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_labe
l=node-v67' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by tiggerite** [comment]
That’s nodegit 0.24.3 and you’re using Node 11, not 12.. and the PR isn’t even merged yet..

**Comment by chrisdothtml** [comment]
I would suggest adding ` <12` to `package.json` > `engines` for the time being so it's more obvious that v12 isn't supported yet
