### ISSUE TITLE
installation failing possibly from libssh

### ISSUE THREAD

**Issue by tristansokol** [nodegit/nodegit#1684]
## System information
  - node version: v12.3.1
  - npm or yarn version: 6.9.0
  - OS/version/architecture: darwin/18.5.0/x64
  - Applicable nodegit version:0.24.3

I've been trying to install nodegit without success. None of the issues I found seem to be exactly the same, but I have tried updating various things with no luck. Installation can't find a binary `nodegit-v0.24.3-node-v72-darwin-x64.tar.gz` which seems weird since I think I'm on a pretty up to date macbook. But during the backup build it seems to fail on `LIBTOOL-STATIC Release/ssh2.a`. This is also where I fail when following the build from source instructions. 

Thank you. 

```
$ npm install nodegit

> nodegit@0.24.3 install /Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp WARN
Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.3-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.24.3 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
SOLINK_MODULE(target) Release/acquireOpenSSL.node
ACTION binding_gyp_configureLibssh2_target_configure .
[nodegit] Configuring libssh2.
SOLINK_MODULE(target) Release/configureLibssh2.node
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buf_text.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/curl.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetchhead.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filebuf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fileops.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filter.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fnmatch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/global.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/graph.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1dc/sha1.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1dc/ubc_check.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hashsig.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ident.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/idxmap.o
../vendor/libgit2/src/idxmap.c:23:1: warning: unused function 'kh_destroy_idxicase' [-Wunused-function]
__KHASH_IMPL(idxicase, static kh_inline, const git_index_entry *, git_index_entry *, 1, idxentry_hash, idxentry_icase_equal)
^
../vendor/libgit2/src/khash.h:210:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_destroy_##name(kh_##name##_t *h)                                          \
                   ^
<scratch space>
:137:1: note: expanded from here
kh_destroy_idxicase
^
../vendor/libgit2/src/idxmap.c:23:1: warning: unused function 'kh_clear_idxicase' [-Wunused-function]
../vendor/libgit2/src/khash.h:218:13: note: expanded from macro '__KHASH_IMPL'
SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:140:1: note: expanded from here
kh_clear_idxicase
^
2 warnings generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ignore.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/index.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/indexer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
../vendor/libgit2/src/iterator.c:481:17: warning: unused function 'tree_iterator_entry_cmp' [-Wunused-function]
GIT_INLINE(int) tree_iterator_entry_cmp(const void *ptr_a, const void *ptr_b)
                ^
1 warning generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/message.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mwindow.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/netops.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/notes.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object_api.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_loose.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_mempack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb.o
../vendor/libgit2/src/odb.c:1389:11: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'git_off_t' (aka 'long long') [-Wformat]
action, stream->declared_size, stream->received_bytes);
                        ^~~~~~~~~~~~~~~~~~~~~
../vendor/libgit2/src/odb.c:1389:34: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'git_off_t' (aka 'long long') [-Wformat]
                action, stream->declared_size, stream->received_bytes);
                                               ^~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/offmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oid.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidarray.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
../vendor/libgit2/src/patch_parse.c:461:12: warning: unused function 'parse_number' [-Wunused-function]
static int parse_number(git_off_t *out, git_patch_parse_ctx *ctx)
           ^
1 warning generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/path.o
../vendor/libgit2/src/path.c:1875:12: warning: unused function 'verify_dotgit_generic' [-Wunused-function]
static int verify_dotgit_generic(const char *name, size_t len, const char *dotgit_name, size_t dotgit_len, const char *shortname_pfix)
           ^
1 warning generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pathspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pool.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/posix.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pqueue.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/proxy.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/push.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/rebase.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb_fs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reflog.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/remote.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/repository.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reset.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revert.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revparse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revwalk.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/settings.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sha1_lookup.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/signature.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/socket.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sortedcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/stash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/status.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/submodule.o
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_init_str' [-Wunused-function]
__KHASH_IMPL(
^
../vendor/libgit2/src/khash.h:207:23: note: expanded from macro '__KHASH_IMPL'
        SCOPE kh_##name##_t *kh_init_##name(void) {                                                     \
                             ^
<scratch space>:154:1: note: expanded from here
kh_init_str
^
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_destroy_str' [-Wunused-function]
../vendor/libgit2/src/khash.h:210:13: note: expanded from macro '__KHASH_IMPL'
SCOPE void kh_destroy_##name(kh_##name##_t *h)                                          \
                   ^
<scratch space>:159:1: note: expanded from here
kh_destroy_str
^
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_clear_str' [-Wunused-function]
../vendor/libgit2/src/khash.h:218:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:162:1
: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_get_str' [-Wunused-function]
../vendor/libgit2/src/khash.h:225:16: note: expanded from macro '__KHASH_IMPL'
SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key)        \
                      ^
<scratch space>:165:1: note: expanded from here
kh_get_str
^
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_put_str' [-Wunused-function]
../vendor/libgit2/src/khash.h:302:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_put_##name(kh_##name##_t *h, khkey_t key, int *ret) \
                      ^
<scratch space>:171:1: note: expanded from here
kh_put_str
^
../vendor/libgit2/src/submodule.c:88:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/khash.h:344:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:176:1: note
: expanded from here
kh_del_str
^
6 warnings generated.
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sysdir.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tag.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/thread-utils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trace.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trailer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transaction.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred_helpers.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/http.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/local.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_pkt.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_protocol.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/ssh.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree-cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tsort.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/util.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/varint.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/vector.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/worktree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xdiffi.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xemit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xhistogram.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xmerge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xpatience.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xprepare.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xutils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/zstream.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/stransport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/tls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/map.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/realpath.o
LIBTOOL-STATIC Release/git2.a
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/adler32.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/crc32.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/deflate.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inffast.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inflate.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inftrees.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/trees.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/zutil.o
LIBTOOL-STATIC Release/zlib.a
CC(target) Release/obj.target/http_parser/vendor/http_parser/http_parser.o
LIBTOOL-STATIC Release/http_parser.a
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/crypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/keepalive.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/libgcrypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/openssl.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/publickey.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/sftp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/version.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/channel.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/global.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/kex.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/mac.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/packet.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/scp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/transport.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/comp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/hostkey.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/knownhost.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/misc.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/pem.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/session.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
LIBTOOL-STATIC Release/ssh2.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/ssh2.a] Error 1
gyp

ERR! build error
gyp ERR!
stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:262:23)
gyp
ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp
ERR! System Darwin 18.5.0
gyp ERR!
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR!
cwd /Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit
gyp ERR!
node -v v12.3.1
gyp
ERR! node-gyp -v v3.8.0
gyp ERR! not ok

node-pre-gyp ERR!
build error
node-pre-gyp ERR!
stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR!
stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit
node-pre-gyp ERR! node -v v12.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/tsokol/Development/InvoiceQuail/functions/gitSync/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by Bear1110** [comment]
fail too.
when I run ```electron-rebuild -f -w nodegit```. I got error message below.

Thanks

```
E:\electron\GeekNote>npm install

> nodegit@0.24.3 install E:\electron\GeekNote\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
[nodegit] Success: "E:\electron\GeekNote\node_modules\nodegit\build\Release\nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> electron@4.2.0 postinstall E:\electron\GeekNote\node_modules\electron
> node install.js


> nodegit@0.24.3 postinstall E:\electron\GeekNote\node_modules\nodegit
> node lifecycleScripts/postinstall


> geeky-note@1.0.0 postinstall E:\electron\GeekNote
> electron-rebuild -f -w nodegit

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
Traceback (most recent call last):
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\electron\GeekNote\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\electron\\GeekNote\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.2.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=nodegit" "--module_path=E:\\electron\\GeekNote\\node_modules\\nodegit\\build\\Release" "--host=https://axonodegit.s3.amazonaws.com/nodegit/nodegit/"
gyp ERR! cwd E:\electron\GeekNote\node_modules\nodegit
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: Traceback (most recent call last):
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "E:\electron\GeekNote\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\electron\GeekNote\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\electron\\GeekNote\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.2.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=nodegit" "--module_path=E:\\electron\\GeekNote\\node_modules\\nodegit\\build\\Release" "--host=https://axonodegit.s3.amazonaws.com/nodegit/nodegit/"
gyp ERR! cwd E:\electron\GeekNote\node_modules\nodegit
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\electron\GeekNote\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (E:\electron\GeekNote\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (E:\electron\GeekNote\node_modules\rxjs\internal\Subscriber.js:145:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! geeky-note@1.0.0 postinstall: `electron-rebuild -f -w nodegit`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the geeky-note@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bear\AppData\Roaming\npm-cache\_logs\2019-06-15T10_41_34_088Z-debug.log
```

**Comment by Bear1110** [comment]
I can pass today, Thanks.

**Comment by mtysor** [comment]
Looks like it's your version of Node.  Doesn't look like they support Node 12 yet: https://github.com/nodegit/nodegit/issues/1680 I had the exact same issue, downgrading to 10 fixed it for me.

**Comment by AubreyHewes** [comment]
I use the alpha for node v12 support [v0.25.0-alpha.16](https://github.com/nodegit/nodegit/releases/tag/v0.25.0-alpha.16). Or you can downgrade to 10 and  wait for a release that supports 12 https://github.com/nodegit/nodegit/pull/1701#issuecomment-512528642. Will at the least be when v12 goes LTS https://github.com/nodegit/nodegit/issues/1680#issuecomment-501350629)
