### ISSUE TITLE
npm  install nodegit seems to be broken

### ISSUE THREAD

**Issue by kfanadka-salesforce** [nodegit/nodegit#1688]
## System information
  - node version: v10.16.0
  - npm or yarn version:6.9.0
  - OS/version/architecture: High Sierra 10.16

All packages looks OK, but the lifecycleScripts failed, any idea how to fix this issue?  

```
2002 silly saveTree │   ├── promise@8.0.3
2002 silly saveTree │   └── qs@6.7.0
2002 silly saveTree └── wrappy@1.0.2
2003 warn datadog-as-a-code@1.0.0 No repository field.
2004 verbose stack Error: nodegit@0.24.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
2004 verbose stack Exit status 1
2004 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2004 verbose stack     at EventEmitter.emit (events.js:198:13)
2004 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2004 verbose stack     at ChildProcess.emit (events.js:198:13)
2004 verbose stack     at maybeClose (internal/child_process.js:982:16)
2004 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2005 verbose pkgid nodegit@0.24.3
```

**Comment by kfanadka-salesforce** [comment]
I also tried to install nodegit from docker image name node: docker pull node
I get the same error.

**Comment by kfanadka-salesforce** [comment]
Step 1: $ npm cache clean --force

Step 2: Delete node_modules by $ rm -rf node_modules folder or delete it manually by going into the directory and right-click > delete. Delete package-lock.json file too.

Step 3: npm install
