### ISSUE TITLE
Install nodegit with node 10.x fails

### ISSUE THREAD

**Issue by betonetotbo** [nodegit/nodegit#1725]
## System information
  - node version: 10.16.3
  - npm or yarn version: 6.8.0
  - OS/version/architecture: Windows 10.0.18362 x64
  - Applicable nodegit version: 0.26.0

I'm trying to install and test nodegit following the get-started tutorial.

`npm install nodegit`

During the instalation I got this:

```
[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node "D:\JJW\srcBesser2\git\besser-core\besser-core-report-designer\node_modules\nodegit\dist\nodegit.js"

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 3221225477,
  signal: null,
  cmd:
   'node "D:\\JJW\\srcBesser2\\git\\besser-core\\besser-core-report-designer\\node_modules\\nodegit\\dist\\nodegit.js"' }
```

**Comment by Tamilarasu-DLT** [comment]
I'm also facing the same issue on executing ps1 file from node js script using execFile.

Can someone help with this?
