### ISSUE TITLE
Error while call getReferences

### ISSUE THREAD

**Issue by dramoturg** [nodegit/nodegit#1726]
## System information
  - node version:  10.15.3
  - npm or yarn version: 6.4.1
  - OS/version/architecture:  win 10.0.18362 x64
  - Applicable nodegit version:  "0.24.10"

```
const root = path.resolve(__dirname, '..', '..');
const localPath = path.resolve(root, 'tmp');
const repo: Repository = await nodegit.Repository.open(localPath);
const refs = await repo.getReferences(Reference.TYPE.LISTALL);
return JSON.stringify(refs);
```

Hello. I get the following error.
```
Error: Callback is required and must be a Function.
    at D:\Projects\vcs_chameleon\web-backend\node_modules\nodegit-promise\lib\node-extensions.js:24:20
    at tryCallTwo (D:\Projects\vcs_chameleon\web-backend\node_modules\nodegit-promise\lib\core.js:45:5)
    at doResolve (D:\Projects\vcs_chameleon\web-backend\node_modules\nodegit-promise\lib\core.js:173:13)
    at new Promise (D:\Projects\vcs_chameleon\web-backend\node_modules\nodegit-promise\lib\core.js:65:3)
    at Repository.getReferences (D:\Projects\vcs_chameleon\web-backend\node_modules\nodegit-promise\lib\node-extensions.js:19:12)
    at GitController.branches (D:\Projects\vcs_chameleon\web-backend\src\controllers\GitController.ts:28:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I tried changing the function call to getReferenceNames.  (their arguments are the same) and code performed without errors

**Comment by rcjsuen** [comment]
@dramoturg If you pass in a second argument into `getReferences(*)` does it help? You've got the `repo` and `type` from what I can tell. Can you also try providing `refNamesOnly`?

https://github.com/nodegit/nodegit/blob/ee7b26c06b8d86b719f264a361dc0d900905f796/lib/repository.js#L352-L366

**Comment by dramoturg** [comment]
Thanks. if use static method all ok. Problem with invalid typings in [@types/nodegit](https://www.npmjs.com/package/@types/nodegit) package. for last version missed static method ```getReferences```. method exists for only instance of repository
```
/**
 * Lookup the reference with the given name.
*/
getReference(name: string | Reference): Promise<Reference>;
```
