### ISSUE TITLE
getReferences Callback is required

### ISSUE THREAD

**Issue by jasonkuhrt** [nodegit/nodegit#1737]
## System information
  - node version:
  - npm or yarn version:
  - OS/version/architecture:
  - Applicable nodegit version:

```
v12.12.0
6.11.3
darwin
19.0.0
x64
```

This seems like a bug:

```
import * as Git from "nodegit"

Git.Repository.open(".")
  .then(async repo => {
    return repo.getReferences(Git.Reference.TYPE.OID)
  })
  .catch(console.error)
```
```
❯ yarn -s ts-node test.ts
Error: Callback is required and must be a Function.
    at /Users/jasonkuhrt/projects/prisma-labs/libre/node_modules/nodegit-promise/lib/node-extensions.js:24:20
    at tryCallTwo (/Users/jasonkuhrt/projects/prisma-labs/libre/node_modules/nodegit-promise/lib/core.js:45:5)
    at doResolve (/Users/jasonkuhrt/projects/prisma-labs/libre/node_modules/nodegit-promise/lib/core.js:173:13)
    at new Promise (/Users/jasonkuhrt/projects/prisma-labs/libre/node_modules/nodegit-promise/lib/core.js:65:3)
    at Repository.getReferences (/Users/jasonkuhrt/projects/prisma-labs/libre/node_modules/nodegit-promise/lib/node-extensions.js:19:12)
    at /Users/jasonkuhrt/projects/prisma-labs/libre/test.ts:6:17
    at Generator.next (<anonymous>)
    at /Users/jasonkuhrt/projects/prisma-labs/libre/test.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jasonkuhrt/projects/prisma-labs/libre/test.ts:4:12)
```

Maybe related https://github.com/nodegit/nodegit/issues/1726

**Comment by jasonkuhrt** [comment]
Hm, but this works:

```
import * as Git from "nodegit"

Git.Repository.open(".")
  .then(async repo => {
    // const c = await repo.getHeadCommit()
    const refs = await (repo.getReferences as any)()
    console.log(refs)
  })
  .catch(console.error)
```

Seems that maybe the bug is the types for `repo.getReferences`.

**Comment by rcjsuen** [comment]
@jasonkuhrt If you use the static function does it work

**Comment by jasonkuhrt** [comment]
@rcjsuen I don't see a static for `getReferences`? 

https://www.nodegit.org/api/repository/#getReferences

**Comment by rcjsuen** [comment]
@jasonkuhrt It was implied by https://github.com/nodegit/nodegit/issues/1726#issuecomment-533825533. Something like the following...?

```JavaScript
var Git = require(".");
var Repository = Git.Repository;
Git.Repository.open(".")
  .then(async repo => {
    return Repository.getReferences(repo, Git.Reference.TYPE.OID)
  })
  .then(result => {
    console.log(result);
  })
  .catch(console.error)
```

**Comment by jasonkuhrt** [comment]
![image](https://user-images.githubusercontent.com/284476/68212522-aedf4580-ffa7-11e9-8ada-c106bcfdad3c.png)

**Comment by rcjsuen** [comment]
@jasonkuhrt Try it anyway.

**Comment by jasonkuhrt** [comment]
```ts
  const repo = await Git.Repository.open(".")
  const refs: Git.Reference[] = await (repo.getReferences as any)()
  const refs2: Git.Reference[] = await (Git.Repository as any).getReferences(
    repo,
  )

  console.log("refs", refs.map(r => r.name()))
  console.log("refs2", refs2.map(r => r.name()))

```
```
refs [
  'refs/heads/feature/3/preview-command',
  'refs/heads/master',
  'refs/remotes/origin/feature/3/preview-command',
  'refs/remotes/origin/master',
  'refs/remotes/origin/master',
  'refs/tags/meek'
]
refs2 []
```

No runtime error but different results.

**Comment by rcjsuen** [comment]
@jasonkuhrt What about if you also provide it with a type like you did in the beginning with `Git.Reference.TYPE.OID`?

**Comment by jasonkuhrt** [comment]
```ts
  const repo = await Git.Repository.open(".")
  const refs: Git.Reference[] = await (repo.getReferences as any)()
  const refs2: Git.Reference[] = await (Git.Repository as any).getReferences(
    repo,
    Git.Reference.TYPE.OID
  )

```
```
refs [
  'refs/heads/feature/3/preview-command',
  'refs/heads/master',
  'refs/remotes/origin/feature/3/preview-command',
  'refs/remotes/origin/master',
  'refs/remotes/origin/master',
  'refs/tags/meek'
]
refs2 []
```

**Comment by rcjsuen** [comment]
Interestingly, looks like those enums are actually [deprecated](https://github.com/nodegit/libgit2/blob/eee2ed90eb4e32ab87eb7f178a7bde2af3593d38/include/git2/deprecated.h#L327-L344).

What are you trying to do actually? Get all branches and tags?

**Comment by jasonkuhrt** [comment]
I am trying to get the tags on a commit. I just opened an issue about the best way to do that, as my current solution seems absurd :) https://github.com/nodegit/nodegit/issues/1738
