### ISSUE TITLE
Cannot Install Nodegit

### ISSUE THREAD

**Issue by b15h0y** [nodegit/nodegit#1752]
## System information
  - node version: v12.4.0
  - npm or yarn version: 6.9.0
  - OS/version/architecture: Ubuntu 18.04 x64 bit
  - Applicable nodegit version: 0.25.1

Error while running `npm install nodegit`
```

> nodegit@0.25.1 install /home/bishoy/Desktop/ink-desktop/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.25.1 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build'

gyp

ERR! configure error
gyp
ERR! stack Error: EACCES: permission denied, mkdir '/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build'
gyp
ERR! System Linux 5.0.0-37-generic
gyp ERR! command
"/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd
/home/bishoy/Desktop/ink-desktop/node_modules/nodegit
gyp ERR! node -v
v12.4.0
gyp ERR!
node-gyp -v v3.8.0
gyp ERR!
not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR!
stack     at ChildProcess.<anonymous> (/home/bishoy/Desktop/ink-desktop/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp
ERR! System Linux 5.0.0-37-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/bishoy/Desktop/ink-desktop/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/bishoy/Desktop/ink-desktop/node_modules/nodegit
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.25.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.25.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bishoy/.npm/_logs/2020-01-21T04_03_49_833Z-debug.log


```

**Comment by koenmtb1** [comment]
ERR! stack Error: EACCES: permission denied, mkdir '/home/bishoy/Desktop/ink-desktop/node_modules/nodegit/build'

This seems to be the issue, make sure your permissions are set correctly.

**Comment by b15h0y** [comment]
solved using : `sudo npm install nodegit --unsafe-perm`
