### ISSUE TITLE
Cannot read property 'TYPE' of undefined

### ISSUE THREAD

**Issue by ArturKovacs** [nodegit/nodegit#1794]
## System information
  - node version: v12.18.3
  - yarn version: 1.21.1
  - OS/version/architecture: Windows 10.0.19041 x64
  - Applicable nodegit version: nodegit@0.27.0

I'm using electron and I have the following in my *main* process

```typescript
import * as Git from "nodegit";
console.log("Git version is:", Git.version);
console.log("The HARD reset type has the id", Git.Reset.TYPE.HARD);
```

When I `yarn start` as usual, I get the following output

```
Git version is: 0.27.0
App threw an error during load
TypeError: Cannot read property 'TYPE' of undefined
    at Object../src/main.ts ([redacted-project-dir]\.webpack\main\index.js:17543:57) 
    at __webpack_require__ ([redacted-project-dir]\.webpack\main\index.js:21:30)     
    at [redacted-project-dir]\.webpack\main\index.js:85:18
    at Object.<anonymous> ([redacted-project-dir]\.webpack\main\index.js:88:10)      
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)       
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```

Note that I get identical results when I do these in my renderer process using ipc.

**Comment by ArturKovacs** [comment]
I just realized that this is probably caused by the way my project is configured and I don't particularly like using the issue system for asking for help about usage so I created a stackoverflow post here: https://stackoverflow.com/questions/63844607/nodegit-cannot-read-property-type-of-undefined

Please consider helping me on stackoverflow. I'm closing this for now.

**Comment by ArturKovacs** [comment]
The reason for reopening this issue is that this is also the behaviour I get when doing this in a fresh project created with
```
yarn create electron-app my-electron-webpack-typescript-nodegit --template=typescript-webpack
```

**Comment by weedz** [comment]
I think this issue is not directly related to nodegit but instead to your webpack-config. And more precisely to the `webpack-asset-relocator-loader` plugin. Maybe look into another version of that plugin.

If you are not limited to using webpack, you might have more success using another build system. I'm using rollup with the following `rollup.config.js`:
```javascript 
import resolve from '@rollup/plugin-node-resolve';
import typescript from "@rollup/plugin-typescript";
import postcss from "rollup-plugin-postcss";
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

const extensions = [".tsx", ".ts"];

export default {
    external: [
        "nodegit",
        "path",
        "fs",
        "electron",
    ],
    input: ["src/renderer.tsx", "src/index.ts"],
    output: {
        sourcemap: !production,
        format: "cjs",
        dir: "dist",
    },
    plugins: [
        typescript(),
        resolve({
            extensions
        }),
        postcss(),
        production && terser(),
    ],
    watch: {
        clearScreen: false
    }
};
```
and `tsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ES2019",
    "strict": true,
    "jsx": "react",
    "jsxFactory": "h",
    "sourceMap": true,
    "baseUrl": ".",
    "moduleResolution": "node",
    "resolveJsonModule": true
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by ArturKovacs** [comment]
Thanks @weedz for your detailed answer! I since then moved on to using `simple-git` which of course is far behind nodegit in terms of its features and requires git to be installed or shipped with the application but it works.

Your suggestion seems very promising though but I don't quite know how dependent I am on webpack and I don't know if I'll have the time to try switching to rollup anytime soon.

But thanks again, I'm sure that your answer will help others stumbling upon this. 😊

**Comment by ArturKovacs** [comment]
Just an update on this. Now as I hit a very similar issue with `drivelist`, another native module, I replaced webpack with rollup which seemingly solved the issue. I haven't tried it with nodegit though.  It might be interesting to note that with webpack I spent a lot of time tweaking the config before every part of the app worked, but with rollup I just pretty much copy pasted the config from `git-good` and rollup just worked. At least that's how it seems so far.
