### ISSUE TITLE
error 404 when istalling with yarn

### ISSUE THREAD

**Issue by tiagobega** [nodegit/nodegit#1813]
## System information
  - node version: 15.5.0
  - npm or yarn version: 1.22.10
  - OS/version/architecture: wsl Ubuntu-20.04
  - Applicable nodegit version: any

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```
on run yarn global add nodegit this error appears:
```
yarn global add nodegit
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/tiago/.config/yarn/global/node_modules/nodegit: Command failed.
Exit code: 1
Command: node lifecycleScripts/preinstall && node lifecycleScripts/install
Arguments:
Directory: /home/tiago/.config/yarn/global/node_modules/nodegit
Output:
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp
info using node-pre-gyp@0.13.0
node-pre-gyp info
using node@15.5.0 | linux | x64
node-pre-gyp WARN
Using request for node-pre-gyp https download
node-pre-gyp
info check checked for "/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node" (not found)
node-pre-gyp
http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v88-linux-x64.tar.gz
node-pre-gyp http 404
https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v88-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v88-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@15.5.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v88-linux-x64.tar.gz
gyp
info it worked if it ends with ok
gyp
info using node-gyp@4.0.0
gyp
info using node@15.5.0 | linux | x64
gyp
info ok
gyp

info it worked if it ends with ok
gyp
info using node-gyp@4.0.0
gyp
info using node@15.5.0 | linux | x64
gyp info
spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/tiago/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp
info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp
info spawn args   '/home/tiago/.config/yarn/global/node_modules/nodegit/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tiago/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tiago/.node-gyp/15.5.0/include/node/common.gypi',
gyp
info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/tiago/.node-gyp/15.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/tiago/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args
'-Dnode_lib_file=/home/tiago/.node-gyp/15.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tiago/.config/yarn/global/node_modules/nodegit',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args
'--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp
ERR! configure error
gyp
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/tiago/.config/yarn/global/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp
ERR! System Linux 4.19.104-microsoft-standard
gyp ERR! command "/home/tiago/.nvm/versions/node/v15.5.0/bin/node" "/home/tiago/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd /home/tiago/.config/yarn/global/node_modules/nodegit
gyp ERR! node -v v15.5.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/home/tiago/.nvm/versions/node/v15.5.0/bin/node /home/tiago/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tiago/.config/yarn/global/node_modules/nodegit/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
node-pre-gyp
ERR! System Linux 4.19.104-microsoft-standard
node-pre-gyp ERR! command
"/home/tiago/.nvm/versions/node/v15.5.0/bin/node" "/home/tiago/.config/yarn/global/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/tiago/.config/yarn/global/node_modules/nodegit
node-pre-gyp ERR! node -v v15.5.0
node-pre-gyp
ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/home/tiago/.nvm/versions/node/v15.5.0/bin/node /home/tiago/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/tiago/.config/yarn/global/node_modules/nodegit/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by tiagobega** [comment]
already fixed it
just use a older version of node like 12.18.2
