### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [nodegit/nodegit#1847]
## System information
  - node version: `v16.3.0`
  - npm or yarn version: `npm(7.15.1)` `yarn(1.22.10)`
  - OS/version/architecture: `macOS Big Sur(11.4)`
  - Applicable nodegit version: `^0.27.0`
 
## More information
  - CPU chip: `Apple M1`

## Problem description

> This seems to be due to a build error caused by [node-gyp](https://github.com/nodejs/node-gyp)  

> Or because of brew? [Reference link: stackoverflow](https://stackoverflow.com/questions/66427623/error-installing-native-node-js-add-on-with-node-gyp-on-apple-m1-big-sur)

```
yarn add nodegit
```
<details>
<summary>Error</summary>
<pre><code>
error /Users/quanchuan/.config/yarn/global/node_modules/nodegit: Command failed.
Exit code: 1
Command: node lifecycleScripts/preinstall && node lifecycleScripts/install
Arguments: 
Directory: /Users/quanchuan/.config/yarn/global/node_modules/nodegit
Output:
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp info
using node-pre-gyp@0.13.0
node-pre-gyp info using node@16.3.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download

node-pre-gyp
info check checked for "/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node" (not found)
node-pre-gyp
http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-arm64.tar.gz
node-pre-gyp http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@16.3.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-arm64.tar.gz
gyp
info
it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@16.3.0 | darwin | arm64
gyp
info ok
gyp

info it worked if it ends with ok
gyp
info using node-gyp@4.0.0
gyp
info using node@16.3.0 | darwin | arm64
(node:57384) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp
info spawn /usr/bin/python
gyp
info spawn args [
gyp info spawn args
'/Users/quanchuan/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info
spawn args   'make',
gyp info spawn args   '-I',
gyp info
spawn args   '/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/config.gypi',
gyp info spawn args   '-I',
gyp
info spawn args   '/Users/quanchuan/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/quanchuan/.node-gyp/16.3.0/include/node/common.gypi',
gyp info
spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp
info spawn args   '-Dnode_root_dir=/Users/quanchuan/.node-gyp/16.3.0',
gyp info
spawn args   '-Dnode_gyp_dir=/Users/quanchuan/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/quanchuan/.node-gyp/16.3.0/<(target_arch)/node.lib',
gyp
info spawn args   '-Dmodule_root_dir=/Users/quanchuan/.config/yarn/global/node_modules/nodegit',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info
spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info
spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp
info ok
gyp
info
it worked if it ends with ok
gyp info using
node-gyp@4.0.0
gyp info
using node@16.3.0 | darwin | arm64
gyp
info spawn make
gyp
info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
SOLINK_MODULE(target) Release/acquireOpenSSL.node
ACTION binding_gyp_configureLibssh2_target_configure .
[nodegit] Configuring libssh2.
SOLINK_MODULE(target) Release/configureLibssh2.node
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/stdalloc.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/alloc.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buf_text.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_entries.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_mem.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_snapshot.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetchhead.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filebuf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/futils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filter.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/global.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/graph.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/sha1.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/ubc_check.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/collisiondetect.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hashsig.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ident.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/idxmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ignore.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/index.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/indexer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mailmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/message.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mwindow.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/net.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/netops.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/notes.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object_api.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_loose.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_mempack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/offmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oid.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidarray.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/mbedtls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/registry.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/path.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pathspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pool.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/posix.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pqueue.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/proxy.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/push.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reader.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/rebase.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb_fs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reflog.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/regexp.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/remote.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/repository.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reset.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revert.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revparse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revwalk.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/settings.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sha1_lookup.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/signature.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/socket.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sortedcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/stash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/status.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/submodule.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sysdir.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tag.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/thread-utils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trace.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trailer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transaction.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred_helpers.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/local.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_pkt.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_protocol.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/ssh.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree-cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tsort.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/util.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/varint.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/vector.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/wildmatch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/worktree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xdiffi.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xemit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xhistogram.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xmerge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xpatience.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xprepare.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xutils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/zstream.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/stransport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/http.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_negotiate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_ntlm.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/tls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/map.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/realpath.o
LIBTOOL-STATIC Release/git2.a
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/adler32.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/crc32.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/deflate.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inffast.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inflate.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inftrees.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/trees.o
CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/zutil.o
LIBTOOL-STATIC Release/zlib.a
CC(target) Release/obj.target/http_parser/vendor/http_parser/http_parser.o
LIBTOOL-STATIC Release/http_parser.a
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/bcrypt_pbkdf.o
../vendor/libssh2/src/bcrypt_pbkdf.c:84:46: warning: expression does not compute the number of elements in this array; element type is 'uint32_t' (aka 'unsigned int'), not 'uint64_t' (aka 'unsigned long long') [-Wsizeof-array-div]
blf_enc(&state, cdata, sizeof(cdata) / sizeof(uint64_t));
                                      ~~~~~  ^
../vendor/libssh2/src/bcrypt_pbkdf.c:65:14: note: array 'cdata' declared here
    uint32_t cdata[BCRYPT_BLOCKS];
             ^
../vendor/libssh2/src/bcrypt_pbkdf.c:84:46: note: place parentheses around the 'sizeof(uint64_t)' expression to silence this warning
        blf_enc(&state, cdata, sizeof(cdata) / sizeof(uint64_t));
                                             ^
1 warning generated.
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/blowfish.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/crypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/keepalive.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/libgcrypt.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/openssl.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/publickey.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/sftp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/version.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/channel.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/global.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/kex.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/mac.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/packet.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/scp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/transport.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/comp.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/hostkey.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/knownhost.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/misc.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/pem.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/session.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
LIBTOOL-STATIC Release/ssh2.a
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/ntlm.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/unicode_builtin.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/util.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/crypt_commoncrypto.o
LIBTOOL-STATIC Release/ntlmclient.a
CXX(target) Release/obj.target/nodegit/src/async_baton.o
In file included from ../src/async_baton.cc:1:
In file included from ../src/../include/async_baton.h:5:
In file included from ../../nan/nan.h:56:
In file included from /Users/quanchuan/.node-gyp/16.3.0/include/node/node.h:63:
In file included from /Users/quanchuan/.node-gyp/16.3.0/include/node/v8.h:30:
/Users/quanchuan/.node-gyp/16.3.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
!std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/nodegit/src/async_baton.o] Error 1
gyp
ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/quanchuan/.config/yarn/global/node_modules/node-gyp/lib/build.js:262:23)
gyp
ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/opt/homebrew/Cellar/node/16.3.0/bin/node" "/Users/quanchuan/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp
ERR! cwd /Users/quanchuan/.config/yarn/global/node_modules/nodegit
gyp ERR! node -v v16.3.0
gyp
ERR! node-gyp -v v4.0.0
gyp ERR!
not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/16.3.0/bin/node /Users/quanchuan/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack
at ChildProcess.<anonymous> (/Users/quanchuan/.config/yarn/global/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR!
stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp
ERR! System Darwin 20.5.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/16.3.0/bin/node" "/Users/quanchuan/.config/yarn/global/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/quanchuan/.config/yarn/global/node_modules/nodegit
node-pre-gyp
ERR! node -v v16.3.0
node-pre-gyp
ERR! node-pre-gyp -v v0.13.0
node-pre-gyp
ERR! not ok
Failed to execute '/opt/homebrew/Cellar/node/16.3.0/bin/node /Users/quanchuan/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/quanchuan/.config/yarn/global/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
</code></pre>
</details>

**Comment by xavortm** [comment]
Very the same error as well, Only posting in case someone has found a solution maybe? Just to test, `arch -x86_64 npm i -g nodegit` didn't work out as well. Tested with v16.6.1 (node installed with their official docs, not via brew). Tested in Rosetta terminal and standard one.

**Comment by Garfield550** [comment]
@0x1af2aec8f957 Hi, your error message is:

```
/Users/quanchuan/.node-gyp/16.3.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
```

Plz follow this StackOverflow post: https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove
