### ISSUE TITLE
Fails to build on Node v17

### ISSUE THREAD

**Issue by luca-viggiani** [nodegit/nodegit#1880]
## System information
  - node version: v17.1.0
  - npm or yarn version: 8.1.3
  - OS/version/architecture: ArchLinux 5.15.4-arch1-1
  - Applicable nodegit version: latest

```npm install node-git``` fails, is there any workaround? (I cannot downgrade node):

```
npm ERR! code 1
npm ERR! path /home/luca/Progetti/quiddis/birdcage/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! make: ingresso nella directory «/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build»
npm ERR! SOLINK_MODULE(target) Release/obj.target/acquireOpenSSL.node
npm ERR! COPY Release/acquireOpenSSL.node
npm ERR! ACTION binding_gyp_configureLibssh2_target_configure .
npm ERR! [nodegit] Configuring libssh2.
npm ERR! SOLINK_MODULE(target) Release/obj.target/configureLibssh2.node
npm ERR! COPY Release/configureLibssh2.node
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/stdalloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/alloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buf_text.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_entries.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_mem.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_snapshot.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
npm ERR! make: uscita dalla directory «/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build»
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp
npm ERR! info using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@17.1.0 | linux | x64
npm ERR! node-pre-gyp WARN
npm ERR! Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp http GET
npm ERR! https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! node-pre-gyp http 404
npm ERR! https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v102-linux-x64.tar.gz 
npm ERR! node-pre-gyp
npm ERR! WARN Pre-built binaries not found for nodegit@0.27.0 and node@17.1.0 (node-v102 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v102-linux-x64.tar.gz
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.2.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp info
npm ERR! ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info using
npm ERR! node-gyp@8.2.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp info
npm ERR! find Python using Python version 3.9.7 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args
npm ERR! 'binding.gyp',
npm ERR! gyp info
npm ERR! spawn args   '-f',
npm ERR! gyp
npm ERR! info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info
npm ERR! spawn args   '/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info
npm ERR! spawn args   '-I',
npm ERR! gyp info spawn args   '/home/luca/.cache/node-gyp/17.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp
npm ERR! info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/luca/.cache/node-gyp/17.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/luca/.cache/node-gyp/17.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info
npm ERR! spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp
npm ERR! 
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.2.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp info spawn
npm ERR! make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /home/luca/.cache/node-gyp/17.1.0/include/node/openssl/././archs/linux-x86_64/asm/include/openssl/ssl.h:21,
npm ERR!                  from /home/luca/.cache/node-gyp/17.1.0/include/node/openssl/./ssl_asm.h:11,
npm ERR!                  from /home/luca/.cache/node-gyp/17.1.0/include/node/openssl/ssl.h:4,
npm ERR!                  from ../vendor/libgit2/src/netops.h:17,
npm ERR!                  from ../vendor/libgit2/src/fetch.h:14,
npm ERR!                  from ../vendor/libgit2/src/fetch.c:8:
npm ERR! /home/luca/.cache/node-gyp/17.1.0/include/node/openssl/macros.h:155:4: error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
npm ERR!   155 | #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
npm ERR!       |    ^~~~~
npm ERR! make: *** [vendor/libgit2.target.mk:309: Release/obj.target/libgit2/vendor/libgit2/src/fetch.o] Errore 1
npm ERR! gyp
npm ERR! ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR!
npm ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.15.4-arch1-1
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp
npm ERR! ERR! cwd /home/luca/Progetti/quiddis/birdcage/node_modules/nodegit
npm ERR! gyp ERR! node -v v17.1.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp
npm ERR! ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp
npm ERR! ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/luca/Progetti/quiddis/birdcage/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/luca/Progetti/quiddis/birdcage/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR!
npm ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.4-arch1-1
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/luca/Progetti/quiddis/birdcage/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/luca/Progetti/quiddis/birdcage/node_modules/nodegit
npm ERR! node-pre-gyp ERR! node -v v17.1.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luca/.npm/_logs/2021-11-25T10_01_09_547Z-debug.log
```

**Comment by luca-viggiani** [comment]
Solved by removing all, then ```npm install @mapbox/node-pre-gyp --save``` and then re installing ```node-git```

**Comment by luca-viggiani** [comment]
I still cannot install

**Comment by mahmoudwork** [comment]
Any updates on this ?

**Comment by MikeJerred** [comment]
The problem might be that you are using python 3. I have only had success using python2 to build. You can `npm config set python <path_to_python2>` to do this.

**Comment by darkMark1999** [comment]
> The problem might be that you are using python 3. I have only had success using python2 to build. You can `npm config set python <path_to_python2>` to do this.

It didn't work, the library is still only compiled for version 14

**Comment by axkibe** [comment]
Any updates on this? Dependency issues start piling up (I can't use node v16 since it segfaults with dynamic imports needed to include ES modules into commonJS)

**Comment by swxk19** [comment]
still broken? (on node v16)
