### ISSUE TITLE
Errors when trying to install nodegit on windows

### ISSUE THREAD

**Issue by Fab-is-insane** [nodegit/nodegit#1881]
## System information
  - node version: v16.3.1
  - npm or yarn version: npm v8.1.2
  - OS/version/architecture: Windows 10
  - Applicable nodegit version: 0.27.0

Error thrown after running `npm install nodegit`

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```

```
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! win_delay_load_hook.cc
npm ERR! Generating code
npm ERR! All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
npm ERR! Finished generating code
npm ERR! acquireOpenSSL.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\acquireOpenSSL.node
npm ERR! C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): warning MSB8017: A circular dependency has been detected while executing custom build commands for item ".". This may cause incremental build to work incorrectly. [C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\configureLibssh2.vcxproj]
npm ERR! configure
npm ERR! [nodegit] Configuring libssh2.
npm ERR! win_delay_load_hook.cc
npm ERR! Generating code
npm ERR! All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
npm ERR! Finished generating code
npm ERR! configureLibssh2.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\configureLibssh2.node
npm ERR! http_parser.c
npm ERR! win_delay_load_hook.cc
npm ERR! http_parser.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\http_parser.lib
npm ERR! stdalloc.c
npm ERR! commit.c
npm ERR! alloc.c
npm ERR! annotated_commit.c
npm ERR! apply.c
npm ERR! attr_file.c
npm ERR! attr.c
npm ERR! attrcache.c
npm ERR! blame_git.c
npm ERR! blame.c
npm ERR! blob.c
npm ERR! branch.c
npm ERR! buf_text.c
npm ERR! buffer.c
npm ERR! cache.c
npm ERR! checkout.c
npm ERR! cherrypick.c
npm ERR! clone.c
npm ERR! commit_list.c
npm ERR! config_cache.c
npm ERR! config_entries.c
npm ERR! config_file.c
npm ERR! config_mem.c
npm ERR! config_parse.c
npm ERR! config_snapshot.c
npm ERR! config.c
npm ERR! crlf.c
npm ERR! date.c
npm ERR! delta.c
npm ERR! diff_driver.c
npm ERR! diff_file.c
npm ERR! diff_generate.c
npm ERR! diff_parse.c
npm ERR! diff_print.c
npm ERR! diff_stats.c
npm ERR! diff_tform.c
npm ERR! diff_xdiff.c
npm ERR! diff.c
npm ERR! errors.c
npm ERR! fetch.c
npm ERR! fetchhead.c
npm ERR! filebuf.c
npm ERR! futils.c
npm ERR! filter.c
npm ERR! global.c
npm ERR! graph.c
npm ERR! hash.c
npm ERR! sha1.c
npm ERR! ubc_check.c
npm ERR! collisiondetect.c
npm ERR! hashsig.c
npm ERR! ident.c
npm ERR! idxmap.c
npm ERR! ignore.c
npm ERR! index.c
npm ERR! indexer.c
npm ERR! iterator.c
npm ERR! mailmap.c
npm ERR! merge_driver.c
npm ERR! merge_file.c
npm ERR! merge.c
npm ERR! message.c
npm ERR! mwindow.c
npm ERR! net.c
npm ERR! netops.c
npm ERR! notes.c
npm ERR! object_api.c
npm ERR! object.c
npm ERR! odb_loose.c
npm ERR! odb_mempack.c
npm ERR! odb_pack.c
npm ERR! odb.c
npm ERR! offmap.c
npm ERR! oid.c
npm ERR! oidarray.c
npm ERR! oidmap.c
npm ERR! mbedtls.c
npm ERR! openssl.c
npm ERR! registry.c
npm ERR! pack-objects.c
npm ERR! pack.c
npm ERR! parse.c
npm ERR! patch_generate.c
npm ERR! patch_parse.c
npm ERR! patch.c
npm ERR! path.c
npm ERR! pathspec.c
npm ERR! pool.c
npm ERR! posix.c
npm ERR! pqueue.c
npm ERR! proxy.c
npm ERR! push.c
npm ERR! reader.c
npm ERR! rebase.c
npm ERR! refdb_fs.c
npm ERR! refdb.c
npm ERR! reflog.c
npm ERR! refs.c
npm ERR! refspec.c
npm ERR! regexp.c
npm ERR! remote.c
npm ERR! repository.c
npm ERR! reset.c
npm ERR! revert.c
npm ERR! revparse.c
npm ERR! revwalk.c
npm ERR! settings.c
npm ERR! sha1_lookup.c
npm ERR! signature.c
npm ERR! socket.c
npm ERR! sortedcache.c
npm ERR! stash.c
npm ERR! status.c
npm ERR! strmap.c
npm ERR! submodule.c
npm ERR! sysdir.c
npm ERR! tag.c
npm ERR! thread-utils.c
npm ERR! trace.c
npm ERR! trailer.c
npm ERR! transaction.c
npm ERR! transport.c
npm ERR! cred_helpers.c
npm ERR! cred.c
npm ERR! git.c
npm ERR! local.c
npm ERR! smart_pkt.c
npm ERR! smart_protocol.c
npm ERR! smart.c
npm ERR! ssh.c
npm ERR! tree-cache.c
npm ERR! tree.c
npm ERR! tsort.c
npm ERR! util.c
npm ERR! varint.c
npm ERR! vector.c
npm ERR! wildmatch.c
npm ERR! worktree.c
npm ERR! xdiffi.c
npm ERR! xemit.c
npm ERR! xhistogram.c
npm ERR! xmerge.c
npm ERR! xpatience.c
npm ERR! xprepare.c
npm ERR! xutils.c
npm ERR! zstream.c
npm ERR! winhttp.c
npm ERR! dir.c
npm ERR! error.c
npm ERR! findfile.c
npm ERR! map.c
npm ERR! path_w32.c
npm ERR! posix_w32.c
npm ERR! precompiled.c
npm ERR! thread.c
npm ERR! utf-conv.c
npm ERR! w32_buffer.c
npm ERR! w32_util.c
npm ERR! win_delay_load_hook.cc
npm ERR! libgit2.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\libgit2.lib
npm ERR! agent.c
npm ERR! bcrypt_pbkdf.c
npm ERR! blowfish.c
npm ERR! crypt.c
npm ERR! keepalive.c
npm ERR! libgcrypt.c
npm ERR! openssl.c
npm ERR! publickey.c
npm ERR! sftp.c
npm ERR! version.c
npm ERR! channel.c
npm ERR! global.c
npm ERR! kex.c
npm ERR! mac.c
npm ERR! packet.c
npm ERR! scp.c
npm ERR! transport.c
npm ERR! comp.c
npm ERR! hostkey.c
npm ERR! knownhost.c
npm ERR! misc.c
npm ERR! pem.c
npm ERR! session.c
npm ERR! c:\users\wim\onedrive\documents\github\fab\node_modules\nodegit\vendor\libssh2\src\session.c(519): warning C4068: unknown pragma [C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\vendor\libssh2.vcxproj]
npm ERR! c:\users\wim\onedrive\documents\github\fab\node_modules\nodegit\vendor\libssh2\src\session.c(520): warning C4068: unknown pragma [C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\vendor\libssh2.vcxproj]
npm ERR! c:\users\wim\onedrive\documents\github\fab\node_modules\nodegit\vendor\libssh2\src\session.c(568): warning C4068: unknown pragma [C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\vendor\libssh2.vcxproj]
npm ERR! userauth.c
npm ERR! win_delay_load_hook.cc
npm ERR! libssh2.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\libssh2.lib
npm ERR! pcre_byte_order.c
npm ERR! pcre_chartables.c
npm ERR! pcre_compile.c
npm ERR! pcre_config.c
npm ERR! pcre_dfa_exec.c
npm ERR! pcre_exec.c
npm ERR! pcre_fullinfo.c
npm ERR! pcre_get.c
npm ERR! pcre_globals.c
npm ERR! pcre_jit_compile.c
npm ERR! pcre_maketables.c
npm ERR! pcre_newline.c
npm ERR! pcre_ord2utf8.c
npm ERR! pcreposix.c
npm ERR! pcre_printint.c
npm ERR! pcre_refcount.c
npm ERR! pcre_string_utils.c
npm ERR! pcre_study.c
npm ERR! pcre_tables.c
npm ERR! pcre_ucd.c
npm ERR! pcre_valid_utf8.c
npm ERR! pcre_version.c
npm ERR! pcre_xclass.c
npm ERR! win_delay_load_hook.cc
npm ERR! pcre.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\pcre.lib
npm ERR! adler32.c
npm ERR! crc32.c
npm ERR! deflate.c
npm ERR! inffast.c
npm ERR! inflate.c
npm ERR! inftrees.c
npm ERR! trees.c
npm ERR! zutil.c
npm ERR! win_delay_load_hook.cc
npm ERR! zlib.vcxproj -> C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\\zlib.lib
npm ERR! async_baton.cc
npm ERR! c:\users\wim\appdata\local\node-gyp\cache\16.13.1\include\node\node.h(63): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\nodegit.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp
npm ERR! info using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@16.13.1 | win32 | x64
npm ERR! node-pre-gyp WARN
npm ERR! Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info
npm ERR! check checked for "C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp http
npm ERR! 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz       
npm ERR! node-pre-gyp WARN
npm ERR! Pre-built binaries not found for nodegit@0.27.0 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)       
npm ERR! node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! gyp
npm ERR!
npm ERR! info it worked if it ends with ok
npm ERR! gyp
npm ERR! info
npm ERR! using node-gyp@8.3.0
npm ERR! gyp
npm ERR! info using
npm ERR! node@16.13.1 | win32 | x64
npm ERR! gyp
npm ERR! info
npm ERR! ok
npm ERR! gyp
npm ERR! info
npm ERR! it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info
npm ERR! find Python
npm ERR! using Python version 3.9.9 found at "C:\Users\wim\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp
npm ERR! info find VS using VS2017 (15.9.28307.1745) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp
npm ERR! info spawn C:\Users\wim\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
npm ERR! gyp
npm ERR! info
npm ERR! spawn args
npm ERR! [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info
npm ERR! spawn args   'C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\nodegit\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\wim\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info
npm ERR! spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\wim\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info
npm ERR! spawn args   '-Dnode_lib_file=C:\\\\Users\\\\wim\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp
npm ERR! info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\nodegit\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info
npm ERR! ok
npm ERR! gyp
npm ERR!
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using
npm ERR! node-gyp@8.3.0
npm ERR! gyp
npm ERR! info using node@16.13.1 | win32 | x64
npm ERR! gyp
npm ERR! info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp
npm ERR! info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp
npm ERR! info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info
npm ERR! spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info
npm ERR! spawn args ]
npm ERR! gyp
npm ERR! ERR! build error
npm ERR! gyp ERR!
npm ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp
npm ERR! ERR!
npm ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp
npm ERR! ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp
npm ERR! ERR! System Windows_NT 10.0.19044
npm ERR! gyp
npm ERR! ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\nodegit\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp
npm ERR! ERR! build error
npm ERR! node-pre-gyp ERR!
npm ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp
npm ERR! ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR!
npm ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command
npm ERR! "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wim\\OneDrive\\Documents\\GitHub\\Fab\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp
npm ERR! ERR! cwd C:\Users\wim\OneDrive\Documents\GitHub\Fab\node_modules\nodegit
npm ERR! node-pre-gyp ERR! node -v v16.13.1
npm ERR! node-pre-gyp
npm ERR! ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wim\AppData\Local\npm-cache\_logs\2021-12-08T13_16_34_936Z-debug.log

```

**Comment by MikeJerred** [comment]
What version of visual studio build tools did you use? I didn't manage to get it working with VS2019, but 2017 works. You can try: `npm config set msvs_version 2017`

**Comment by Fab-is-insane** [comment]
> What version of visual studio build tools did you use? I didn't manage to get it working with VS2019, but 2017 works. You can try: `npm config set msvs_version 2017`

Thanks for your reply but I already fixed this issue :)

**Comment by rmd1710714107** [comment]
> > What version of visual studio build tools did you use? I didn't manage to get it working with VS2019, but 2017 works. You can try: `npm config set msvs_version 2017`
> 
> Thanks for your reply but I already fixed this issue :)

Could u tell me how did u fix it? I encounter the same problem.

**Comment by aprilmintacpineda** [comment]
I'm also getting this error on my MacOS 12.6.3

<details>
<summary>full logs</summary>

```
╰─$ yarn add nodegit
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
warning nodegit > node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning nodegit > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/2] ⠠ core-js
error myproject/node_modules/nodegit: Command failed.
Exit code: 1
Command: node lifecycleScripts/preinstall && node lifecycleScripts/install
Arguments: 
Directory: myproject/node_modules/nodegit
Output:
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp info
using node-pre-gyp@0.13.0
node-pre-gyp info using node@19.5.0 | darwin | x64
node-pre-gyp WARN
Using request for node-pre-gyp https download
node-pre-gyp info
check checked for "myproject/node_modules/nodegit/build/Release/nodegit.node" (not found)
node-pre-gyp http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v111-darwin-x64.tar.gz
node-pre-gyp http
404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v111-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v111-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@19.5.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v111-darwin-x64.tar.gz
gyp
info it worked if it ends with
ok
gyp info
using node-gyp@4.0.0
gyp

info using node@19.5.0 | darwin | x64
gyp
info ok

gyp
info it worked if it ends with
ok
gyp
info using node-gyp@4.0.0
gyp
info using node@19.5.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v19.5.0/node-v19.5.0-headers.tar.gz
gyp http 200
https://nodejs.org/download/release/v19.5.0/node-v19.5.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.5.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v19.5.0/SHASUMS256.txt
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [
gyp
info spawn args   'myproject/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info
spawn args   '-I',
gyp info spawn args   'myproject/node_modules/nodegit/build/config.gypi',
gyp info spawn args   '-I',
gyp
info spawn args   'myproject/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp
info spawn args   '/Users/aprilmintacpineda/.node-gyp/19.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp
info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aprilmintacpineda/.node-gyp/19.5.0',
gyp info
spawn args   '-Dnode_gyp_dir=myproject/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aprilmintacpineda/.node-gyp/19.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=myproject/node_modules/nodegit',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info
spawn args ]
gyp: Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp
gyp ERR!
configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (myproject/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/aprilmintacpineda/.nvm/versions/node/v19.5.0/bin/node" "myproject/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=myproject/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=myproject/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
gyp ERR! cwd myproject/node_modules/nodegit
gyp ERR!
node -v v19.5.0
gyp ERR! node-gyp -v v4.0.0
gyp
ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/aprilmintacpineda/.nvm/versions/node/v19.5.0/bin/node myproject/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=myproject/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=myproject/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
node-pre-gyp ERR!
stack     at ChildProcess.<anonymous> (myproject/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/Users/aprilmintacpineda/.nvm/versions/node/v19.5.0/bin/node" "myproject/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd myproject/node_modules/nodegit
node-pre-gyp ERR! node -v
v19.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp
ERR! not ok
Failed to execute '/Users/aprilmintacpineda/.nvm/versions/node/v19.5.0/bin/node myproject/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=myproject/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=myproject/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```
</details>

> What version of visual studio build tools did you use? I didn't manage to get it working with VS2019, but 2017 works. You can try: `npm config set msvs_version 2017`

I'm afraid doing this can mess with other dependencies I have installed or will install in the future, is there a better fix?
