### ISSUE TITLE
Can't be installed for Node v16

### ISSUE THREAD

**Issue by LiST-GIT** [nodegit/nodegit#1902]
## System information
  - node version: v16.13.2
  - npm or yarn version: yarn 1.22.17
  - OS/version/architecture: darwin 21.4.0 x64
  - Applicable nodegit version: 0.28.0-alpha.11

```
➜  nodegit yarn install                               
yarn install v1.22.17
warning ../../package.json: No license field
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning aws-sdk > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning babel-cli > babel-register > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning babel-cli > babel-polyfill > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning babel-cli > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning babel-cli > chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning babel-cli > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning babel-cli > chokidar > readdirp > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning babel-cli > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning babel-cli > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning babel-cli > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning coveralls > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning istanbul@0.4.5: This module is no longer maintained, try this instead:
  npm i nyc
Visit https://istanbul.js.org/integrations for other alternatives.
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ node lifecycleScripts/preinstall && node lifecycleScripts/install
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@16.13.2 | darwin | x64
node-pre-gyp WARN
Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/xxxxxxx/node_modules/nodegit/build/Release/nodegit.node" (not found)
node-pre-gyp http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.11-node-v93-darwin-x64.tar.gz
node-pre-gyp http
404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.11-node-v93-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.11-node-v93-darwin-x64.tar.gz 
node-pre-gyp WARN
Pre-built binaries not found for nodegit@0.28.0-alpha.11 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.11-node-v93-darwin-x64.tar.gz
gyp

info it worked if it ends with ok
gyp info
using node-gyp@7.1.2
gyp
info using
node@16.13.2 | darwin | x64
gyp
info ok
gyp
info it worked if it ends with ok
gyp info
using node-gyp@7.1.2
gyp info using
node@16.13.2 | darwin | x64
gyp info
find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
(node:50749) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp
info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args
[
gyp info spawn args   '/Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info
spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp
info spawn args   '/Users/xxxxxxx/node_modules/nodegit/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/addon.gypi',
gyp
info spawn args   '-I',
gyp info spawn args   '/Users/xxxxxxx/Library/Caches/node-gyp/16.13.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/xxxxxxx/Library/Caches/node-gyp/16.13.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/xxxxxxx/Library/Caches/node-gyp/16.13.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/xxxxxxx/node_modules/nodegit',
gyp info
spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp
info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp
info it worked if it ends with ok
gyp info
using node-gyp@7.1.2
gyp info using node@16.13.2 | darwin | x64
gyp
info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
SOLINK_MODULE(target) Release/acquireOpenSSL.node
ACTION binding_gyp_configureLibssh2_target_configure .
[nodegit] Configuring libssh2.
SOLINK_MODULE(target) Release/configureLibssh2.node
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/failalloc.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/stdalloc.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_graph.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/custom_tls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/alloc.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buf_text.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_entries.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_mem.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_snapshot.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetchhead.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filebuf.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/futils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filter.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/graph.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/sha1.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/ubc_check.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/collisiondetect.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hashsig.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ident.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/idxmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ignore.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/index.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/indexer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/libgit2.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mailmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/midx.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_driver.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_file.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/message.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mwindow.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/net.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/netops.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/notes.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object_api.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_loose.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_mempack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/offmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oid.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidarray.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/path.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pathspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pool.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/posix.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pqueue.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/proxy.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/push.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reader.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/rebase.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb_fs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reflog.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refs.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refspec.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/regexp.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/remote.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/repository.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reset.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revert.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revparse.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revwalk.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/runtime.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/signature.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/socket.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sortedcache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/stash.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/status.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strarray.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/mbedtls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/registry.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strmap.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/submodule.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sysdir.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tag.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/thread.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/threadstate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trace.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trailer.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transaction.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/credential_helpers.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/credential.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/git.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/local.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/httpclient.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_pkt.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_protocol.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/ssh.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree-cache.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tsort.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/util.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/varint.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/vector.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/wildmatch.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/worktree.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xdiffi.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xemit.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xhistogram.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xmerge.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xpatience.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xprepare.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xutils.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/zstream.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/stransport.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/http.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_negotiate.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_ntlm.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/tls.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/map.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/pthread.o
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/realpath.o
LIBTOOL-STATIC Release/git2.a
env: python: No such file or directory
make: *** [Release/git2.a] Error 127
gyp
ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR!
stack     at ChildProcess.onExit (/Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/xxxxxxx/.nvm/versions/node/v16.13.2/bin/node" "/Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/xxxxxxx/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/xxxxxxx/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp
ERR! cwd /Users/xxxxxxx/node_modules/nodegit
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR!
build error
node-pre-gyp ERR!
stack Error: Failed to execute '/Users/xxxxxxx/.nvm/versions/node/v16.13.2/bin/node /Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxxxxxx/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/xxxxxxx/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxxxxxx/node_modules/nodegit/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR!
System Darwin 21.4.0
node-pre-gyp ERR! command
"/Users/xxxxxxx/.nvm/versions/node/v16.13.2/bin/node" "/Users/xxxxxxx/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/Users/xxxxxxx/node_modules/nodegit
node-pre-gyp ERR! node -v v16.13.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/xxxxxxx/.nvm/versions/node/v16.13.2/bin/node /Users/xxxxxxx/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxxxxxx/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/xxxxxxx/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  nodegit 

```

**Comment by ianhattendorf** [comment]
> env: python: No such file or directory

Looks like there's an issue with python. What happens when you run `which python` and `python --version`?

Also try `alpha.13` instead of `alpha.11`, you can see here that CI is passing on Node 16 so most likely there's an issue with your setup (possibly an undocumented build dependency).

https://github.com/nodegit/nodegit/runs/5645777421?check_suite_focus=true

It's possible the default version of Python installed on macOS is too outdated for node-gyp, you could try installing a newer version of python.

**Comment by ArtGangsta** [comment]
I'm honestly shocked.  Never in a million years did I think that this module would not work on macOS.  Current LTS version is Node 16, and this module simply doesn't work on macOS.

I mean, that's fine, if you don't want to support it.  But why make your audience think you are?   Just be up front so we don't waste time if we need cross-platform support.

By the way it works great on Windows.
