### ISSUE TITLE
Supports yarn berry?

### ISSUE THREAD

**Issue by nnnnoel** [nodegit/nodegit#1907]
## System information
  - node version: 14.18.2
  - npm or yarn version: yarn 3.2.0
  - OS/version/architecture: macOS M1 / 12.2 / arm64
  - Applicable nodegit version: 0.27.0

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/noel/Desktop/querypie-yarn-berry/packages/querypie-middleware/node_modules/node-pre-gyp/bin/node-pre-gyp
    at new NodeError (internal/errors.js:322:7)
    at defaultGetFormat (internal/modules/esm/get_format.js:71:15)
    at getFormat$1 (file:///Users/noel/Desktop/querypie-yarn-berry/.pnp.loader.mjs:157:10)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

I got this error. any supports for yarn berry?

**Comment by ianhattendorf** [comment]
Try the latest alpha `0.28.0-alpha.13`, but this isn't something we've ever looked into so I wouldn't be surprised if there were issues.
