### ISSUE TITLE
electron-rebuild fails

### ISSUE THREAD

**Issue by nikwen** [nodegit/nodegit#1954]
## System information
  - node version: 18.2.1
  - Electron version: 21.2.2
  - npm or yarn version: npm 8.18.0
  - OS/version/architecture: macOS 13.0 arm64
  - Applicable nodegit version: 0.28.0-alpha.18

## How to reproduce

1. `cd myElectronProject`
2. `npm i nodegit@0.28.0-alpha.18`
3. `electron-rebuild`

## Error message

From the `electron-rebuild logs` during OpenSSL compilation:

```
⠧ Building module: nodegit, Completed: 0../test/recipes/80-test_ocsp.t ..................... ok
⠏ Building module: nodegit, Completed: 0../test/recipes/80-test_pkcs12.t ................... ok
⠴ Building module: nodegit, Completed: 0../test/recipes/80-test_ssl_new.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/29 subtests 
⠦ Building module: nodegit, Completed: 0../test/recipes/80-test_ssl_old.t .................. ok
⠏ Building module: nodegit, Completed: 0../test/recipes/80-test_ssl_test_ctx.t ............. ok
```

```
Test Summary Report
-------------------
../test/recipes/80-test_ssl_new.t                (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=158, Tests=2425, 96 wallclock secs ( 0.38 usr  0.22 sys + 40.07 cusr 20.79 csys = 61.46 CPU)
Result: FAIL
make[2]: *** [_tests] Error 1
make[1]: *** [tests] Error 2
Acquire failed:  Error: Command failed: make test
make[2]: *** [_tests] Error 1
make[1]: *** [tests] Error 2

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'make test'
}
make: *** [vendor/openssl] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/xxx/xxx/xxx/xxx/node_modules/nodegit'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/xxx/xxx/xxx/xxx/node_modules/nodegit'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/rebuild.js:112:17)
    at async /Users/xxx/xxx/xxx/xxx/node_modules/@electron/rebuild/lib/src/cli.js:158:9
```

## Upstream issue

https://github.com/openssl/openssl/issues/18456 (fixed in recent OpenSSL versions)

### Proper fix

Publish a new package version with OpenSSL `1.1.1s`

### Workaround (for now)

Manually edit `node_modules/nodegit/utils/acquireOpenSSL.js` before `electron-rebuild` and replace the OpenSSL version with `1.1.1s`

**Comment by nikwen** [comment]
Fixed in `0.28.0-alpha.19`. Thanks, @ianhattendorf!
