### ISSUE TITLE
Module install/build fails on Heroku 

### ISSUE THREAD

**Issue by bwestergard** [nodegit/nodegit#332]
Install works fine locally (OSX), though I had to change some permissions to allow the binary to be written outside the node_modules directory.

Why not just write the binary downloaded from S3 to `node_modules/nodegit`?

```
Fetching repository, done.
Counting objects: 108, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (92/92), done.
Writing objects: 100% (95/95), 12.12 KiB | 0 bytes/s, done.
Total 95 (delta 66), reused 5 (delta 2)

-----> Node.js app detected
-----> Resetting git environment
-----> Requested node range:  ^0.10.28
-----> Resolved node version: 0.10.33
-----> Downloading and installing node
-----> Restoring node_modules directory from cache
-----> Pruning cached dependencies not specified in package.json
-----> Exporting config vars to environment
-----> Installing dependencies
       npm WARN package.json formdefutils@0.0.2 No repository field.
       npm WARN package.json formdefutils@0.0.2 No README data
       npm WARN package.json us@1.0.3 No repository field.
       
       > nodegit@0.2.4 install /tmp/build_1cd14a456bfa97e314e7aa8c1a34a6c7/node_modules/nodegit
       > node install
       
       [nodegit] Fetching binary from S3.
       [nodegit] Failed to install prebuilt, attempting compile.
       [nodegit] Determining dependencies.
       [nodegit] Detecting vendor/libgit2.
       [nodegit] Removing outdated vendor/libgit2.
       [nodegit] Detecting vendor/libssh2.
       [nodegit] Removing outdated vendor/libssh2.
       [nodegit] Detecting vendor/http_parser.
       [nodegit] Removing outdated vendor/http_parser.
       [nodegit] Fetching vendor/libgit2.
       [nodegit] Fetching vendor/libssh2.
       [nodegit] Fetching vendor/http_parser.
       [nodegit] Building native node module.
       [nodegit] Failed to build and install nodegit.
       Command failed: ../vendor/libssh2/src/openssl.c: In function '_libssh2_pub_priv_keyfile':
       ../vendor/libssh2/src/openssl.c:767: warning: value computed is not used
       ../vendor/libssh2/src/transport.c: In function '_libssh2_transport_send':
       ../vendor/libssh2/src/transport.c:716: warning: suggest braces around empty body in an 'if' statement
       cc1plus: error: unrecognized command line option "-std=c++11"
       make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_1cd14a456bfa97e314e7aa8c1a34a6c7/node_modules/nodegit/node_modules/node-gyp/lib/build.js:267:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
       gyp ERR! System Linux 3.8.11-ec2
       gyp ERR! command "node" "/tmp/build_1cd14a456bfa97e314e7aa8c1a34a6c7/node_modules/nodegit/node_modules/.bin/node-gyp" "clean" "configure" "build" "--python" "/usr/local/bin/python2"
       gyp ERR! cwd /tmp/build_1cd14a456bfa97e314e7aa8c1a34a6c7/node_modules/nodegit
       gyp ERR! node -v v0.10.33
       gyp ERR! node-gyp -v v1.0.2
       gyp ERR! not ok 
```

**Comment by johnhaley81** [comment]
We'll need this now for v0.2.5

**Comment by maxkorp** [comment]
The issue with the unrecognized command line option is a problem with make. I know it doesnt work with make 4.6, and does with 4.8, not sure about 4.7.

**Comment by maxkorp** [comment]
Is this still an issue for you?

**Comment by maxkorp** [comment]
I'm closing this. Let me know if you still have an issue once you've tried a newer g++.
