### ISSUE TITLE
Can't require nodegit without building it explicitly

### ISSUE THREAD

**Issue by rbelouin** [nodegit/nodegit#340]
Hi,

After having run `npm install --save https://github.com/nodegit/nodegit/archive/master.tar.gz`, I can't require nodegit correctly. I get the following npm error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'nodegit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rbelouin/work/clever-cloud/clever-tools/src/app.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

It seems that `lib/nodegit.js` is the main file of the nodegit package, but it does not exist. I have to run a manual `BUILD_ONLY=true node install.js` to create that file. But it's annoying.

Am I doing something wrong?

**Comment by johnhaley81** [comment]
Is there a specific reason why you're doing master instead of the latest npm release? I.e. `npm install nodegit --save`

Also, we do support questions on our [gitter](https://gitter.im/nodegit/nodegit). I'm going to close this issue and we can do realtime support over there.
