### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by nkt** [nodegit/nodegit#447]
Are you going to support io.js?
I'm trying to install `nodegit` on vagrant machine, but failed with error:
```
[nodegit] Building native node module.
[nodegit] Failed to build and install nodegit.
Command failed: /bin/sh -c /home/vagrant/branch/node_modules/nodegit/node_modules/.bin/node-gyp clean configure  build --python "/usr/bin/python2"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/home/vagrant/branch/node_modules/nodegit/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/home/vagrant/branch/node_modules/nodegit/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/home/vagrant/branch/node_modules/nodegit/node_modules/.bin/node-gyp" "clean" "configure" "build" "--python" "/usr/bin/python2"
gyp ERR! cwd /home/vagrant/branch/node_modules/nodegit
gyp ERR! node -v v1.4.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

Vagrantfile:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get -y dist-upgrade
    sudo apt-get install -y software-properties-common python-software-properties
    sudo add-apt-repository -y ppa:git-core/ppa
    sudo apt-get update
    sudo apt-get install -y build-essential libssl-dev git-core
    cd /opt
    sudo wget https://iojs.org/dist/v1.4.2/iojs-v1.4.2-linux-x64.tar.gz
    sudo tar zxf iojs-v1.4.2-linux-x64.tar.gz
    sudo ln -sf /opt/iojs-v1.4.2-linux-x64/bin/* /usr/bin/
  SHELL
end
```

**Comment by tbranyen** [comment]
Yup, with the next version that will be released any day now, we're hoping to publish io.js prebuilt binaries.

**Comment by nkt** [comment]
This is great news! So, I'll be waiting.
