### ISSUE TITLE
Failed to `require` on Ubuntu 12.04LTS

### ISSUE THREAD

**Issue by dennari** [nodegit/nodegit#493]
With node v0.12.0 and npm 2.5.1, `npm install` goes through fine:
```
\
> nodegit@0.3.3 install node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.

> nodegit@0.3.3 postinstall node_modules/nodegit
> node lifecycleScripts/clean

[nodegit] Cleaning up after ourselves.
[nodegit] Deleting unneeded files.
[nodegit] Finished deleting files.
[nodegit] Pruning devdependencies.
[nodegit] Cleaning unneeded dependencies.
npm WARN uninstall not installed in node_modules/nodegit/node_modules: "for-node-webkit"
npm WARN uninstall not installed in node_modules/nodegit/node_modules: "fs-extra"
unbuild which-native-nodish@1.1.1
unbuild node-pre-gyp@0.6.4
unbuild npm@2.7.1
[nodegit] Successfully pruned devdependencies.
[nodegit] Successfully cleaned unneeded dependencies.
[nodegit] Done cleaning, enjoy!

nodegit@0.3.3 node_modules/nodegit
├── promisify-node@0.1.5
├── nodegit-promise@1.0.0 (asap@1.0.0)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0)
└── npm@2.7.1
```
But then

```
~$ node
> var git = require("nodegit")
Error: Cannot find module '../build/Debug/nodegit'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (node_modules/nodegit/lib/nodegit.js:12:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by dennari** [comment]
After installing from the repository, I got `cc1plus: error: unrecognized command line option ‘-std=c++11’`, which lead me to upgrade to [gcc 4.8](http://ubuntuhandbook.org/index.php/2013/08/install-gcc-4-8-via-ppa-in-ubuntu-12-04-13-04). Nodegit now works fine.

**Comment by johnhaley81** [comment]
Did you recompile nodegit using gcc or did you just upgrade and then it worked?

**Comment by dennari** [comment]
I recompiled using gcc

**Comment by maxkorp** [comment]
Yeah, IIRC GCC 4.6 and below don't support `-std=c++11`

 I'll make sure theres a note in the readme.

**Comment by tbranyen** [comment]
I think we have a note for that already.  The problem here was originally libgc being out-of-date though.  We need to document that in a way that isn't super confusing and easy to check.

**Comment by maxkorp** [comment]
Hrm, it seems like the build instructions are gone entirely, at least from the readme O.o

**Comment by tbranyen** [comment]
They exist in the install from source guide: http://www.nodegit.org/guides/install/from-source/
