### ISSUE TITLE
Not working with iojs

### ISSUE THREAD

**Issue by callumacrae** [nodegit/nodegit#516]
```
❯ nvm list
    iojs-v1.1.0
    iojs-v1.2.0
    iojs-v1.3.0
->  iojs-v1.6.2
       v0.10.35
       v0.10.36
        v0.12.0
default -> stable (-> v0.12.0)
node -> stable (-> v0.12.0) (default)
stable -> 0.12 (-> v0.12.0) (default)
iojs -> iojs-v1.6 (-> iojs-v1.6.2) (default)
```

I'm using iojs 1.6.2. I get the following error:

```
module.js:318
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/callumacrae/Sites/lmn/parker-pr-bot/node_modules/nodegit/lib/nodegit.js:12:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
```

It works fine with node.

What would you suggest? I'd prefer to use iojs.

Here's my nodegit install output:

```
❯ npm i -S nodegit
npm WARN package.json parker-pr-bot@0.1.0 No description
npm WARN package.json parker-pr-bot@0.1.0 No repository field.
npm WARN package.json parker-pr-bot@0.1.0 No README data
-
> nodegit@0.3.3 install /Users/callumacrae/Sites/lmn/parker-pr-bot/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.

> nodegit@0.3.3 postinstall /Users/callumacrae/Sites/lmn/parker-pr-bot/node_modules/nodegit
> node lifecycleScripts/clean

[nodegit] Cleaning up after ourselves.
[nodegit] Deleting unneeded files.
[nodegit] Finished deleting files.
[nodegit] Pruning devdependencies.
[nodegit] Cleaning unneeded dependencies.
npm WARN uninstall not installed in /Users/callumacrae/Sites/lmn/parker-pr-bot/node_modules/nodegit/node_modules: "for-node-webkit"
unbuild fs-extra@0.16.5
unbuild node-pre-gyp@0.6.4
unbuild which-native-nodish@1.1.1
unbuild npm@2.7.4
[nodegit] Successfully pruned devdependencies.
[nodegit] Successfully cleaned unneeded dependencies.
[nodegit] Done cleaning, enjoy!
nodegit@0.3.3 node_modules/nodegit
├── promisify-node@0.1.5
├── nodegit-promise@1.0.0 (asap@1.0.0)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0)
├── fs-extra@0.16.5 (jsonfile@2.0.0, rimraf@2.3.2)
└── npm@2.7.4
```

**Comment by tbranyen** [comment]
What operating system and are you running 32 or 64bit?

**Comment by callumacrae** [comment]
OS X Yosemite, so 64 bit.

**Comment by tbranyen** [comment]
Can you dig into `node_modules/nodegit/lib/nodegit.js` and inside the try/catch block at the top where we require in the raw api, log out the exception that is being caught.  That will further help diagnose what the issue is.

**Comment by callumacrae** [comment]
`Error: Module version mismatch. Expected 43, got 14.`

**Comment by johnhaley81** [comment]
This is a bug with node-pre-gyp. It should have forced a rebuild since you have a newer and incompatible version of iojs. 

In the meantime try `BUILD_ONLY=true npm install`

**Comment by callumacrae** [comment]
That worked. Thanks!

**Comment by johnhaley81** [comment]
This is related: https://github.com/mapbox/node-pre-gyp/issues/150
