### ISSUE TITLE
Issues on scientific linux 6.6

### ISSUE THREAD

**Issue by Globegitter** [nodegit/nodegit#521]
It seems when trying to require nodegit on scientific linux it does not work. I am getting the following error:

```js
module.js:318
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/code/node_modules/nodegit/lib/nodegit.js:12:12)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
```

Looking more into it now.

When I try to build I get the following error:

```js
{ [Error: Command failed: /bin/sh -c /code/nodegit/node_modules/.bin/pangyp rebuild
make: Warning: File `vendor/zlib.target.mk' has modification time 1.7 s in the future
../vendor/libssh2/src/openssl.c: In function '_libssh2_pub_priv_keyfile':
../vendor/libssh2/src/openssl.c:767: warning: value computed is not used
../vendor/libssh2/src/kex.c: In function '_libssh2_kex_exchange':
../vendor/libssh2/src/kex.c:1220: warning: dereferencing pointer 'methodlist' does break strict-aliasing rules
../vendor/libssh2/src/kex.c:1326: note: initialized from here
../vendor/libssh2/src/transport.c: In function '_libssh2_transport_send':
../vendor/libssh2/src/transport.c:716: warning: suggest braces around empty body in an 'if' statement
../vendor/openssl/openssl/crypto/x509v3/v3_utl.c: In function 'hex_to_string':
../vendor/openssl/openssl/crypto/x509v3/v3_utl.c:368: warning: 'static' is not at beginning of declaration
../vendor/openssl/openssl/crypto/cast/c_enc.c: In function 'CAST_encrypt':
../vendor/openssl/openssl/crypto/cast/c_enc.c:65: warning: 'register' is not at beginning of declaration
../vendor/openssl/openssl/crypto/cast/c_enc.c: In function 'CAST_decrypt':
../vendor/openssl/openssl/crypto/cast/c_enc.c:98: warning: 'register' is not at beginning of declaration
cc1plus: error: unrecognized command line option "-s
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/code/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Linux 3.18.5-tinycore64
gyp ERR! command "/home/install-node-iojs/releases/iojs/linux-x64/1.6.2/bin/iojs" "/code/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /code/nodegit
gyp ERR! node -v v1.6.2
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /code/nodegit/node_modules/.bin/pangyp rebuild' }
```

**Comment by maxkorp** [comment]
Which versions of gcc and make do you have installed? We do require g++ 4.7 or newer, IIRC. The default install most likely either incorrectly detected your platform/arch as compatible or (more likely) tried building on its own already, and failed on its own and slipped under the radar.

**Comment by tgriffo** [comment]
Hi guys, also having this issue on an Amazon Linux box..

g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16)

Any other dependencies I should check if I got the right version?

**Comment by myhau** [comment]
Same issue here ( with `require('nodegit')` ):
`Error: Cannot find module '../build/Debug/nodegit'`
My specs:
`g++ (Ubuntu 4.9.1-16ubuntu6) 4.9.1`
`Ubuntu 14.10 ( xubuntu )`
`node --version` `v0.12.2`
`npm --version` `2.7.4`
Also it doesn't automatically install `fs-extra` and `npm` dependency on my system.
I mean, I need to do `npm install -g npm fs-extra` before `npm install -g nodegit`
If I can provide some additional info, please let me know :)

**Comment by tbranyen** [comment]
@myhau why do you think you need to install `npm` first? You already have NPM, when you use `-g` it's installing it into the exact same place that your command `npm` is.

**Comment by myhau** [comment]
When I type only `npm install -g nodegit`, here is what it says now:
```bash
λ npm install -g nodegit
 
> nodegit@0.3.3 prepublish /home/mihau/nodegit
> node lifecycleScripts/prepareForBuild.js

nodegit@0.3.3 /home/mihau/.npm-packages/lib/node_modules/nodegit
├── promisify-node@0.1.5
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0)
├── nodegit-promise@1.0.1 (asap@1.0.0)
├── fs-extra@0.16.5 (jsonfile@2.0.0, graceful-fs@3.0.6, rimraf@2.3.2)
├── node-pre-gyp@0.6.4
└── npm@2.8.3

npm WARN installMany node-pre-gyp was bundled with nodegit@0.3.3, but bundled package wasn't found in unpacked tree
/
> nodegit@0.3.3 install /home/mihau/.npm-packages/lib/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c npm install --ignore-scripts
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/mihau/.npm-packages/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mihau/.npm-packages/lib/node_modules/nodegit/npm-debug.log
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c npm install --ignore-scripts' }
undefined

> nodegit@0.3.3 postinstall /home/mihau/.npm-packages/lib/node_modules/nodegit
> node lifecycleScripts/clean

/home/mihau/.npm-packages/lib/node_modules/nodegit/lifecycleScripts/clean.js:13
npm.load({
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/mihau/.npm-packages/lib/node_modules/nodegit/lifecycleScripts/clean.js:13:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nodegit"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.3.3 postinstall: `node lifecycleScripts/clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.3.3 postinstall script 'node lifecycleScripts/clean'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/clean
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mihau/npm-debug.log
```
I will try to install it on some VM on clean system.

**Comment by tbranyen** [comment]
@myhau before you try on another system, can you provide the following information:

```
uname -a
```

You mentioned Ubuntu, but we need more information.

**Comment by myhau** [comment]
`Linux ubiquitous 3.16.0-36-generic #48-Ubuntu SMP Tue Apr 14 20:07:19 UTC 2015 i686 i686 i686 GNU/Linux`
Here is info, I also edited previous comment to attach it.

**Comment by tbranyen** [comment]
Yeah it's 32bit, we haven't published a binary for that yet.  I can do that in a few moments.

**Comment by myhau** [comment]
Weird thing is, I've just installed it on system that has `uname -a` output `Linux german-test 3.16.0-28-generic #37-Ubuntu SMP Mon Dec 8 17:22:00 UTC 2014 i686 i686 i686 GNU/Linux` and it fetched library succesfully.

**Comment by myhau** [comment]
I've solved it by purging `nodejs` and `npm` and installing them again properly,  using tools like `nvm`, and then simply `npm install -g nodegit` fetched binary correctly (or maybe @tbranyen did you published binary in the meantime?). But I still don't know what was the issue.

**Comment by johnhaley81** [comment]
@Globegitter @tgriffo did that work for you guys as well?

As a side note I'd HIGHLY recommend installing node/npm through nvm. Life is so much easier.

**Comment by davidfirst** [comment]
I'm using Mac, and just had the same issue.
It is working perfect with node.js v0.10.35. I tried to update node.js to v0.11.13 then I got the error:
Error: Cannot find module '../build/Debug/nodegit'

Then, tried to reinstall nodegit, but got errors similar to what myhau got.
Please let me know if you would like to see the output.

I ended up downgrading to node.js v0.10.35

**Comment by tbranyen** [comment]
Node 0.11 is unstable we don't support that.  Use 0.12 or 0.10 (as you already have).

**Comment by davidfirst** [comment]
tbranyen by "Use 0.12" you mean 0.11.12? because I just tried it, and got the same error.

The reason why I tried to update to 0.11.x, is because I have an issue when trying to clone/pull it doesn't stop for the promise and continue with the execution. When trying to debug with node-inspector I got a message "Your Node version (v0.10.35) has a partial support of profiler".

**Comment by tbranyen** [comment]
No I mean 0.12 which is the latest stable Node.js minor.

**Comment by davidfirst** [comment]
tbranyen thank you very much! it is working now. (had a small error with "npm ERR! Attempt to unlock" but chmod helped there).

**Comment by tgriffo** [comment]
Hi @johnhaley81, yes, working now. Thanks heaps!!
What I did: installed nvm, removed nodegit and reinstalled it.

**Comment by johnhaley81** [comment]
Sounds good. If something else crops up I'll be happy to re-open this issue.

**Comment by ipika** [comment]
```
npm http GET https://registry.npmjs.org/nodegit
npm http 304 https://registry.npmjs.org/nodegit
npm http GET https://registry.npmjs.org/promisify-node
npm http GET https://registry.npmjs.org/which-native-nodish
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/nodegit-promise
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/promisify-node
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/nodegit-promise
npm http 304 https://registry.npmjs.org/which-native-nodish
npm http 304 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/find-parent-dir
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/asap
npm http GET https://registry.npmjs.org/asap
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/find-parent-dir
npm http 304 https://registry.npmjs.org/asap
npm http 304 https://registry.npmjs.org/asap
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/balanced-match

> nodegit@0.4.1 install /usr/local/lib/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: npm http request GET https://registry.npmjs.org/which-native-nodish
npm http request GET https://registry.npmjs.org/fs-extra
npm http request GET https://registry.npmjs.org/nodegit-promise
npm http request GET https://registry.npmjs.org/promisify-node
npm http request GET https://registry.npmjs.org/npm
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! path npm-debug.log.c2ce5cfcef3de005e0743ff24276d024
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open 'npm-debug.log.c2ce5cfcef3de005e0743ff24276d024'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './_stream_duplex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/nodegit/npm-debug.log
] killed: false, code: 1, signal: null }
undefined
nodegit@0.4.1 /usr/local/lib/node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── npm@2.11.2
└── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
```

`uname -a` gives following 
`Linux XoXo 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
