### ISSUE TITLE
Unable to compile or install with npm install nodegit

### ISSUE THREAD

**Issue by weikinhuang** [nodegit/nodegit#536]
I am trying to get nodegit installed on windows (7, 8.1 x64) and iojs 1.6.x. I am getting the following errors. And I've tried the different build options specified in the docs. I am able to compile other modules such as `sqlite` without issues.

```
> nodegit@0.3.3 install D:\Documents\Projects\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "D:\Documents\Projects\node_modules\nodegit\node_modules\.bin\pangyp rebuild"
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Documents\Projects\node_modules\nodegit\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "D:\\Documents\\Projects\\node_modules\\nodegit\\node_modules\\pangyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\Projects\node_modules\nodegit
gyp ERR! node -v v1.6.4
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "D:\\Documents\\Projects\\node_modules\\nodegit\\node_modules\\.bin\\pangyp rebuild"' }
undefined

> nodegit@0.3.3 postinstall D:\Documents\Projects\node_modules\nodegit
> node lifecycleScripts/clean

[nodegit] Cleaning up after ourselves.
[nodegit] Deleting unneeded files.
[nodegit] Finished deleting files.
[nodegit] Pruning devdependencies.
[nodegit] Cleaning unneeded dependencies.
npm WARN uninstall not installed in D:\Documents\Projects\node_modules\nodegit\node_modules: "for-node-webkit"
unbuild fs-extra@0.16.5
unbuild node-pre-gyp@0.6.4
unbuild which-native-nodish@1.1.1
unbuild npm@2.7.6
[nodegit] Successfully cleaned unneeded dependencies.
unbuild lodash@3.6.0
unbuild nan@1.7.0
unbuild request@2.55.0
unbuild istanbul@0.3.13
unbuild jshint@2.6.3
unbuild combyne@0.6.5
unbuild js-beautify@1.5.5
unbuild mocha@2.1.0
unbuild nw-gyp@0.12.4
unbuild pangyp@2.1.0
[nodegit] Successfully pruned devdependencies.
[nodegit] Done cleaning, enjoy!
nodegit@0.3.3 node_modules\nodegit
├── promisify-node@0.1.5
├── nodegit-promise@1.0.0 (asap@1.0.0)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0)
├── fs-extra@0.16.5 (jsonfile@2.0.0, graceful-fs@3.0.6)
└── npm@2.7.6
```

**Comment by johnhaley81** [comment]
With building nodegit on windows there are a lot of things that can go wrong. When using MSBUILD from the command line the order you install Visual Studio will dramatically effect the C++ libraries built and linked against.

What version of VS are you currently running?

**Comment by weikinhuang** [comment]
I have VS Express 2012 for Desktop on one computer and VS Express 2013 for Desktop on another and they are both failing with the same error.

**Comment by johnhaley81** [comment]
I just published a binary for x64 of iojs. Try installing it again.

**Comment by weikinhuang** [comment]
working now, thanks alot!
