### ISSUE TITLE
Doesn't work with io.js 2.x

### ISSUE THREAD

**Issue by arturadib** [nodegit/nodegit#573]
Using Mac OS X 10.10.3, io.js 2.0.2:

```
$ npm install nodegit
|
> nodegit@0.4.0 install /Users/aadib/temp/t/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /Users/aadib/temp/t/node_modules/nodegit/node_modules/.bin/pangyp rebuild
../vendor/libgit2/src/attr.c:10:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/attr.c:10:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:88:1: note: expanded from here
kh_del_str
^
2 warnings generated.
../vendor/libgit2/src/attrcache.c:8:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/attrcache.c:8:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:88:1: note: expanded from here
kh_del_str
^
2 warnings generated.
../vendor/libgit2/src/clone.c:479:20: warning: unused function 'repository_base' [-Wunused-function]
static const char *repository_base(git_repository *repo)
                   ^
1 warning generated.
../vendor/libgit2/src/config_file.c:24:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/config_file.c:24:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:88:1: note: expanded from here
kh_del_str
^
2 warnings generated.
../vendor/libgit2/src/diff_driver.c:20:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/diff_driver.c:20:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:88:1: note: expanded from here
kh_del_str
^
2 warnings generated.
../vendor/libgit2/src/mwindow.c:17:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:121:1: note: expanded from here
kh_clear_str
^
1 warning generated.
../vendor/libgit2/src/odb_mempack.c:21:1: warning: unused function 'kh_destroy_oid' [-Wunused-function]
GIT__USE_OIDMAP;
^
../vendor/libgit2/src/oidmap.h:30:2: note: expanded from macro 'GIT__USE_OIDMAP'
        __KHASH_IMPL(oid, static kh_inline, const git_oid *, void *, 1, git_oidmap_hash, git_oid_equal)
        ^
../vendor/libgit2/src/khash.h:198:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_destroy_##name(kh_##name##_t *h)                                          \
                   ^
<scratch space>:67:1: note: expanded from here
kh_destroy_oid
^
../vendor/libgit2/src/odb_mempack.c:21:1: warning: unused function 'kh_clear_oid' [-Wunused-function]
../vendor/libgit2/src/oidmap.h:30:2: note: expanded from macro 'GIT__USE_OIDMAP'
        __KHASH_IMPL(oid, static kh_inline, const git_oid *, void *, 1, git_oidmap_hash, git_oid_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:70:1: note: expanded from here
kh_clear_oid
^
../vendor/libgit2/src/odb_mempack.c:21:1: warning: unused function 'kh_del_oid' [-Wunused-function]
../vendor/libgit2/src/oidmap.h:30:2: note: expanded from macro 'GIT__USE_OIDMAP'
        __KHASH_IMPL(oid, static kh_inline, const git_oid *, void *, 1, git_oidmap_hash, git_oid_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:84:1: note: expanded from here
kh_del_oid
^
3 warnings generated.
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_init_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:195:23: note: expanded from macro '__KHASH_IMPL'
        SCOPE kh_##name##_t *kh_init_##name(void) {                                                     \
                             ^
<scratch space>:124:1: note: expanded from here
kh_init_str
^
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_destroy_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:198:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_destroy_##name(kh_##name##_t *h)                                          \
                   ^
<scratch space>:129:1: note: expanded from here
kh_destroy_str
^
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_clear_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:132:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_get_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:213:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key)        \
                      ^
<scratch space>:135:1: note: expanded from here
kh_get_str
^
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_put_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:291:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_put_##name(kh_##name##_t *h, khkey_t key, int *ret) \
                      ^
<scratch space>:141:1: note: expanded from here
kh_put_str
^
../vendor/libgit2/src/refdb_fs.c:29:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:146:1: note: expanded from here
kh_del_str
^
6 warnings generated.
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_init_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:195:23: note: expanded from macro '__KHASH_IMPL'
        SCOPE kh_##name##_t *kh_init_##name(void) {                                                     \
                             ^
<scratch space>:124:1: note: expanded from here
kh_init_str
^
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_destroy_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:198:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_destroy_##name(kh_##name##_t *h)                                          \
                   ^
<scratch space>:129:1: note: expanded from here
kh_destroy_str
^
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_clear_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:132:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_get_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:213:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key)        \
                      ^
<scratch space>:135:1: note: expanded from here
kh_get_str
^
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_put_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:291:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_put_##name(kh_##name##_t *h, khkey_t key, int *ret) \
                      ^
<scratch space>:141:1: note: expanded from here
kh_put_str
^
../vendor/libgit2/src/refs.c:27:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:146:1: note: expanded from here
kh_del_str
^
6 warnings generated.
../vendor/libgit2/src/submodule.c:86:1: warning: unused function 'kh_clear_str' [-Wunused-function]
__KHASH_IMPL(
^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
1 warning generated.
../vendor/libgit2/src/transaction.c:20:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP;
^
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:206:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
<scratch space>:74:1: note: expanded from here
kh_clear_str
^
../vendor/libgit2/src/transaction.c:20:1: warning: unused function 'kh_del_str' [-Wunused-function]
../vendor/libgit2/src/strmap.h:23:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:333:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x)                           \
                   ^
<scratch space>:88:1: note: expanded from here
kh_del_str
^
2 warnings generated.
../vendor/libssh2/src/misc.c:214:19: warning: unused variable 'base64_table' [-Wunused-const-variable]
static const char base64_table[] =
                  ^
../vendor/libssh2/src/misc.c:223:19: warning: unused variable 'base64_pad' [-Wunused-const-variable]
static const char base64_pad = '=';
                  ^
2 warnings generated.
../vendor/openssl/openssl/ssl/d1_srtp.c:147:7: warning: missing field 'id' initializer [-Wmissing-field-initializers]
    {0}
      ^
1 warning generated.
../vendor/openssl/openssl/crypto/asn1/x_bignum.c:85:1: warning: missing field 'prim_print' initializer [-Wmissing-field-initializers]
};
^
1 warning generated.
../vendor/openssl/openssl/crypto/cmac/cm_ameth.c:96:2: warning: missing field 'item_verify' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/dh/dh_ameth.c:500:2: warning: missing field 'old_priv_decode' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/dsa/dsa_ameth.c:650:3: warning: missing field 'pem_str' initializer [-Wmissing-field-initializers]
                },
                ^
../vendor/openssl/openssl/crypto/dsa/dsa_ameth.c:656:3: warning: missing field 'pem_str' initializer [-Wmissing-field-initializers]
                },
                ^
../vendor/openssl/openssl/crypto/dsa/dsa_ameth.c:662:3: warning: missing field 'pem_str' initializer [-Wmissing-field-initializers]
                },
                ^
../vendor/openssl/openssl/crypto/dsa/dsa_ameth.c:668:3: warning: missing field 'pem_str' initializer [-Wmissing-field-initializers]
                },
                ^
../vendor/openssl/openssl/crypto/dsa/dsa_ameth.c:702:3: warning: missing field 'item_verify' initializer [-Wmissing-field-initializers]
                }
                ^
5 warnings generated.
../vendor/openssl/openssl/crypto/ec/ec_ameth.c:660:2: warning: missing field 'item_verify' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/ec/ec_lib.c:71:19: warning: unused variable 'EC_version' [-Wunused-const-variable]
static const char EC_version[] = "EC" OPENSSL_VERSION_PTEXT;
                  ^
1 warning generated.
../vendor/openssl/openssl/crypto/engine/eng_dyn.c:117:30: warning: unused variable 'dynamic_cmd_defns_empty' [-Wunused-const-variable]
static const ENGINE_CMD_DEFN dynamic_cmd_defns_empty[] = {
                             ^
1 warning generated.
../vendor/openssl/openssl/crypto/engine/eng_openssl.c:344:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_dss.c:94:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_dss1.c:96:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_ecdsa.c:144:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_md4.c:97:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_md5.c:96:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_mdc2.c:97:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_null.c:88:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_ripemd.c:96:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_sha.c:95:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/evp/m_sha1.c:97:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
../vendor/openssl/openssl/crypto/evp/m_sha1.c:134:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
../vendor/openssl/openssl/crypto/evp/m_sha1.c:153:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
../vendor/openssl/openssl/crypto/evp/m_sha1.c:184:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
../vendor/openssl/openssl/crypto/evp/m_sha1.c:203:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
5 warnings generated.
../vendor/openssl/openssl/crypto/evp/m_wp.c:37:2: warning: missing field 'md_ctrl' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/hmac/hm_ameth.c:166:2: warning: missing field 'item_verify' initializer [-Wmissing-field-initializers]
        };
        ^
1 warning generated.
../vendor/openssl/openssl/crypto/pem/pem_lib.c:473:6: warning: variable 'i' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
        if (o)
            ^
../vendor/openssl/openssl/crypto/pem/pem_lib.c:480:5: note: uninitialized use occurs here
        j+=i;
           ^
../vendor/openssl/openssl/crypto/pem/pem_lib.c:473:2: note: remove the 'if' if its condition is always true
        if (o)
        ^~~~~~
../vendor/openssl/openssl/crypto/pem/pem_lib.c:443:7: note: initialize the variable 'i' to silence this warning
        int i,j,o,klen;
             ^
              = 0
1 warning generated.
../vendor/openssl/openssl/crypto/rsa/rsa_ameth.c:697:3: warning: missing field 'pem_str' initializer [-Wmissing-field-initializers]
                }
                ^
1 warning generated.
../src/nodegit.cc:2:10: fatal error: 'v8.h' file not found
#include <v8.h>
         ^
1 error generated.
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aadib/temp/t/node_modules/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/aadib/.nvm/versions/io.js/v2.0.2/bin/iojs" "/Users/aadib/temp/t/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /Users/aadib/temp/t/node_modules/nodegit
gyp ERR! node -v v2.0.2
gyp ERR! pangyp -v v2.2.0
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/aadib/temp/t/node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined

> nodegit@0.4.0 postinstall /Users/aadib/temp/t/node_modules/nodegit
> node lifecycleScripts/clean

[nodegit] Cleaning up after ourselves.
[nodegit] Deleting unneeded files.
[nodegit] Finished deleting files.
[nodegit] Pruning devdependencies.
[nodegit] Cleaning unneeded dependencies.
npm WARN uninstall not installed in /Users/aadib/temp/t/node_modules/nodegit/node_modules: "for-node-webkit"
unbuild fs-extra@0.18.3
unbuild npm@2.10.0
unbuild which-native-nodish@1.1.1
unbuild node-pre-gyp@0.6.7
[nodegit] Successfully cleaned unneeded dependencies.
unbuild lodash@3.8.0
unbuild combyne@0.8.0
unbuild nan@1.7.0
unbuild request@2.55.0
unbuild tar@2.1.1
unbuild js-beautify@1.5.5
unbuild mocha@2.2.5
unbuild istanbul@0.3.14
unbuild coveralls@2.11.2
unbuild jshint@2.7.0
unbuild pangyp@2.2.0
unbuild nw-gyp@0.12.4
unbuild lcov-result-merger@1.0.2
[nodegit] Successfully pruned devdependencies.
[nodegit] Done cleaning, enjoy!
nodegit@0.4.0 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── fs-extra@0.18.3 (jsonfile@2.0.0, graceful-fs@3.0.6, rimraf@2.3.3)
└── npm@2.10.0
```

**Comment by tbranyen** [comment]
Correct, we can only support 1.x at the moment.
