### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by cjbrowne** [nodegit/nodegit#593]
I get the following error when trying to run my script that uses nodegit.

```
<snip>/node_modules/nodegit/lib/nodegit.js:13
    throw ex;
          ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<snip>/node_modules/nodegit/lib/nodegit.js:8:12)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
```

Upon googling around for the error, it suggests that this is something to do with node-webkit.  The only problem?  I'm not using node-webkit in my project.

Version info:
nodegit: 0.4.0
npm: 1.4.21 (1.4.21+ds-2)
node: v0.10.25 (0.10.25~dfsg2-2ubuntu1)

I also have iojs version 2.2.0 installed, and originally tried running it with that but got this error so I tried with nodejs instead and got the same problem.

**Comment by tbranyen** [comment]
This is an iojs issue.  If you switch to Node you need to recompile it with: `npm rebuild`.  I believe our master branch works with iojs 2 though.

**Comment by cjbrowne** [comment]
I thought I'd already done that, but it turned out 'n' didn't remove the /usr/local/bin/node -> iojs soft-link, which meant I was still using iojs anyway.

It works great now that I switched back to node *properly*, thanks.
