### ISSUE TITLE
Installation Error on Ubuntu

### ISSUE THREAD

**Issue by hegdeashwin** [nodegit/nodegit#600]
I tried to install on Ubuntu 14.04, Node.js version v0.10.37 and npm version 2.9.1
Well nodegit got installed by it was throwing below error messages at the time of installation

```
\
> nodegit@0.4.1 install /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: npm WARN package.json promisify-node@0.1.5 No repository field.
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/jshint-0b12f53e5360dd22.lock'
npm WARN locking  /home/ashwin/.npm/_locks/jshint-0b12f53e5360dd22.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/jshint-0b12f53e5360dd22.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/jshint-0b12f53e5360dd22.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/jshint, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/lodash-7545611410094605.lock'
npm WARN locking  /home/ashwin/.npm/_locks/lodash-7545611410094605.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/lodash-7545611410094605.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/lodash-7545611410094605.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/lodash, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/nan-41df618b08824cb3.lock'
npm WARN locking  /home/ashwin/.npm/_locks/nan-41df618b08824cb3.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/nan-41df618b08824cb3.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/nan-41df618b08824cb3.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/nan, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/pangyp-093449caacac5b05.lock'
npm WARN locking  /home/ashwin/.npm/_locks/pangyp-093449caacac5b05.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/pangyp-093449caacac5b05.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/pangyp-093449caacac5b05.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/pangyp, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/lcov-result-merger-88c12560712568cd.lock'
npm WARN locking  /home/ashwin/.npm/_locks/lcov-result-merger-88c12560712568cd.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/lcov-result-merger-88c12560712568cd.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/lcov-result-merger-88c12560712568cd.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/lcov-result-merger, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/mocha-07bddbf6e3197fd8.lock'
npm WARN locking  /home/ashwin/.npm/_locks/mocha-07bddbf6e3197fd8.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/mocha-07bddbf6e3197fd8.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/mocha-07bddbf6e3197fd8.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/mocha, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/js-beautify-3958ac15a9b9e8a2.lock'
npm WARN locking  /home/ashwin/.npm/_locks/js-beautify-3958ac15a9b9e8a2.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/js-beautify-3958ac15a9b9e8a2.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/js-beautify-3958ac15a9b9e8a2.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/js-beautify, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/tar-76b03ab650218eca.lock'
npm WARN locking  /home/ashwin/.npm/_locks/tar-76b03ab650218eca.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/tar-76b03ab650218eca.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/tar-76b03ab650218eca.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/tar, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/request-fe51072f5c2d152b.lock'
npm WARN locking  /home/ashwin/.npm/_locks/request-fe51072f5c2d152b.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/request-fe51072f5c2d152b.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/request-fe51072f5c2d152b.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/request, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/nw-gyp-818297e60cb94689.lock'
npm WARN locking  /home/ashwin/.npm/_locks/nw-gyp-818297e60cb94689.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/nw-gyp-818297e60cb94689.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/nw-gyp-818297e60cb94689.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/nw-gyp, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/istanbul-70618293e40b92b7.lock'
npm WARN locking  /home/ashwin/.npm/_locks/istanbul-70618293e40b92b7.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/istanbul-70618293e40b92b7.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/istanbul-70618293e40b92b7.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/istanbul, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/combyne-0420273ae5aefcf1.lock'
npm WARN locking  /home/ashwin/.npm/_locks/combyne-0420273ae5aefcf1.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/combyne-0420273ae5aefcf1.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/combyne-0420273ae5aefcf1.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/combyne, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ashwin/.npm/_locks/coveralls-08d1b7102263709f.lock'
npm WARN locking  /home/ashwin/.npm/_locks/coveralls-08d1b7102263709f.lock failed { [Error: EACCES, open '/home/ashwin/.npm/_locks/coveralls-08d1b7102263709f.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ashwin/.npm/_locks/coveralls-08d1b7102263709f.lock' }
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/coveralls, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/npm-debug.log
] killed: false, code: 1, signal: null }
undefined
nodegit@0.4.1 ../../../node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── npm@2.11.1
```

Do we need to do any other configuration or did i miss any thing other the below command
```
sudo npm install nodegit --save
```

**Comment by hegdeashwin** [comment]
After the above install i tried to execute clone.js from our home page as below:

```
node clone.js 

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

my clone.js content:
```
var git = require("nodegit");

git.Clone("https://github.com/hegdeashwin/protocore", "protocore").then(function(repository) {
  	// Work with the repository object here.
  	console.log(repository);
});
```

**Comment by maxkorp** [comment]
This appears to be a permissions error with your npm locks?? Can you make sure your permissions on `~/.npm/_locks/*` is set to something appropriate (like 644)

**Comment by hegdeashwin** [comment]
I tried changing it from
```drwxr-xr-x 72 ashwin ashwin  4096 Jun  9 00:19 .npm``` 
to
```drwxrwxrwx 72 ashwin ashwin  4096 Jun  9 00:19 .npm```

It seems like most of the error got solved but there where few remaining as below:
```
> nodegit@0.4.1 install /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh: 1: /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/.bin/pangyp: Permission denied
] killed: false, code: 126, signal: null }
undefined
nodegit@0.4.1 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── npm@2.11.1
```

after this i tried to execute node clone.js but its displaying the same error !

**Comment by maxkorp** [comment]
Yeah, if you look above, it failed to compile. Which version of gcc do you have installed? IIRC ubuntu 14.04 comes with too old of a version.

**Comment by hegdeashwin** [comment]
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)  for 64x Bit Ubuntu 14.05

**Comment by hegdeashwin** [comment]
Tried few more time got same errors but in details

```
ashwin@ashwin-ThinkPad-T410:/media/ashwin/My Passport/Storage-TB/OpenSource/Projects/$ npm install nodegit
/
> nodegit@0.4.1 install /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Something is missing, retrieving dependencies and regenerating code
nan@1.8.4 node_modules/nan

combyne@0.8.0 node_modules/combyne

js-beautify@1.5.6 node_modules/js-beautify
├── nopt@3.0.2 (abbrev@1.0.7)
├── config-chain@1.1.9 (ini@1.3.4, proto-list@1.2.4)
└── mkdirp@0.5.1 (minimist@0.0.8)

mocha@2.2.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

tar@2.1.1 node_modules/tar
├── inherits@2.0.1
├── block-stream@0.0.8
└── fstream@1.0.6 (graceful-fs@3.0.8, mkdirp@0.5.1, rimraf@2.4.0)

request@2.58.0 node_modules/request
├── caseless@0.10.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── tunnel-agent@0.4.0
├── oauth-sign@0.8.0
├── isstream@0.1.2
├── extend@2.0.1
├── json-stringify-safe@5.0.1
├── node-uuid@1.4.3
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── qs@3.1.0
├── mime-types@2.0.14 (mime-db@1.12.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── tough-cookie@2.0.0
├── form-data@1.0.0-rc1 (mime-types@2.1.1, async@1.2.1)
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.7.1 (commander@2.8.1, chalk@1.0.0, is-my-json-valid@2.12.0, bluebird@2.9.30)

coveralls@2.11.2 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (forever-agent@0.5.2, aws-sign2@0.5.0, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, qs@1.0.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, hawk@1.1.1, tough-cookie@2.0.0)
└── js-yaml@3.0.1 (argparse@0.1.16, esprima@1.0.4)

nw-gyp@0.12.4 node_modules/nw-gyp
├── graceful-fs@2.0.3
├── nopt@2.2.1 (abbrev@1.0.7)
├── osenv@0.1.2 (os-tmpdir@1.0.1)
├── semver@2.2.1
├── npmlog@0.1.1 (ansi@0.3.0)
├── minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.6.4)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8)
├── which@1.1.1 (is-absolute@0.1.7)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.8)
└── rimraf@2.4.0 (glob@4.5.3)

lodash@3.9.3 node_modules/lodash

lcov-result-merger@1.0.2 node_modules/lcov-result-merger
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, defaults@1.0.2, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6, strip-bom@1.0.0)

pangyp@2.2.1 node_modules/pangyp
├── which@1.0.9
├── rimraf@2.2.8
├── graceful-fs@3.0.8
├── osenv@0.1.2 (os-tmpdir@1.0.1)
├── nopt@3.0.2 (abbrev@1.0.7)
├── fstream@1.0.6 (inherits@2.0.1)
├── semver@4.3.6
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── npmlog@1.0.0 (ansi@0.3.0, gauge@1.0.2, are-we-there-yet@1.0.4)
└── request@2.51.0 (caseless@0.8.0, forever-agent@0.5.2, aws-sign2@0.5.0, oauth-sign@0.5.0, tunnel-agent@0.4.0, stringstream@0.0.4, json-stringify-safe@5.0.1, qs@2.3.3, node-uuid@1.4.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.4, http-signature@0.10.1, hawk@1.1.1, form-data@0.2.0, tough-cookie@2.0.0)

istanbul@0.3.15 node_modules/istanbul
├── supports-color@1.3.1
├── which@1.0.9
├── abbrev@1.0.7
├── nopt@3.0.2
├── wordwrap@0.0.3
├── once@1.3.2 (wrappy@1.0.1)
├── async@0.9.2
├── esprima@2.1.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── resolve@1.1.6
├── fileset@0.1.6 (minimatch@0.4.0, glob@5.0.10)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
├── escodegen@1.6.1 (esutils@1.1.6, estraverse@1.9.3, optionator@0.5.0, source-map@0.1.43, esprima@1.2.5)
└── handlebars@3.0.0 (source-map@0.1.43, optimist@0.6.1, uglify-js@2.3.6)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.2
├── exit@0.1.2
├── shelljs@0.3.0
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── cli@0.6.6 (glob@3.2.11)
├── lodash@3.7.0
└── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)

[nodegit] Detecting vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5.
[nodegit] Detecting vendor/libssh2/1.4.3.
[nodegit] Detecting vendor/http_parser/2.5.0.
[nodegit] Detecting generated code.
[nodegit] vendor/libssh2/1.4.3 already exists.
[nodegit] vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5 already exists.
[nodegit] Generated code is intact.
[nodegit] Removing outdated vendor/http_parser/.
[nodegit] Retrieving vendor/http_parser/.
[nodegit] Successfully updated vendor/http_parser/2.5.0.
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /media/ashwin/My\ Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/.bin/pangyp rebuild
/bin/sh: 1: /media/ashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/.bin/pangyp: Permission denied
]
  killed: false,
  code: 126,
  signal: null,
  cmd: '/bin/sh -c /media/ashwin/My\\ Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined
nodegit@0.4.1 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── npm@2.11.2

```

**Comment by johnhaley81** [comment]
We recently published pre-built binaries for nodegit 0.4.1. Can you retest and confirm that this is still broken?

Thanks!

**Comment by mcollina** [comment]
I am getting:

```
[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh: 1: /home/ubuntu/.nvm/v0.10.39/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nodegit/node_modules/.bin/pangyp: not found
] killed: false, code: 127, signal: null }
```

**Comment by tbranyen** [comment]
@mcollina what version is that? which os and what architecture? `uname -a`

**Comment by mcollina** [comment]
0.4.1, node v0.10.39 and:
```
$ uname -a
Linux ip-10-102-1-13 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

bumping to iojs solved that, but 0.10 should still be supported, right?

**Comment by tbranyen** [comment]
Oh I didn't push 0.10.

**Comment by mcollina** [comment]
Still, it should build it, right? It seems pangyp is not getting installed

**Comment by tbranyen** [comment]
Maybe, I haven't tried.  I'd recommend using the latest stable 0.12 though.

**Comment by mcollina** [comment]
Agreed on 0.12, but I need to keep support of 0.10 too :(, it is very widespread in production. Should I have a look at 0.10 and send a PR for pangyp?

**Comment by tbranyen** [comment]
Sure, if you can figure out the issue I'd definitely be okay with merging.

**Comment by mcollina** [comment]
I debugged a bit more the pangyp issue. The problem lies in the fact that we are looking for builders in the `node_modules/.bin/` folder, but if any of those has been installed globally, NPM would not install them again, so there is no binary.

The solution is to use the `require.resolve` system to figure it out where it lies.

**Comment by mcollina** [comment]
I was definitely wrong. What fails compilation is using nodegit with NPM 1.4. Somehow dev dependencies do not get installed properly.

**Comment by hegdeashwin** [comment]
@tbranyen , @maxkorp @johnhaley81 @mcollina 
Awesome! today i tried installing 0.4.1 version on  0.12.4 node.js on my new Ubuntu 15.4 LTS and it got installed successfully.

```
[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.
npm verb unsafe-perm in lifecycle true
npm info postinstall nodegit@0.4.1
npm verb unlock done using /home/hegdeashwin/.npm/_locks/nodegit-4f2832d78aa131f9.lock for /media/hegdeashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/node_modules/nodegit
npm verb validateInstall loading /media/hegdeashwin/My Passport/Storage-TB/OpenSource/Projects/gits-local-web/package.json for validation
nodegit@0.4.1 node_modules/nodegit
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── fs-extra@0.18.4 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── npm@2.12.0
npm verb save saving { nodegit: '^0.4.1' }
npm verb exit [ 0, true ]
npm info ok 
```

Also my clone.js is working as expects now.
Good news! thank you for the release that helped a lot.

**Comment by johnhaley81** [comment]
:+1: 
Closing this out as resolved then.
