### ISSUE TITLE
npm install failing when promisify-node is a dependency in my package.json

### ISSUE THREAD

**Issue by cdcarson** [nodegit/nodegit#617]
Hi --

I'm running into an issue with npm install with the following dependencies in my `package.json`: 

```
"devDependencies": {
    "async": "^1.2.1",
    "bootstrap": "^3.3.5",
    "commander": "^2.8.1",
    "express": "^4.13.0",
    "grunt": "^0.4.5",
    "lodash": "^3.9.3",
    "marked": "^0.3.3",
    "moment": "^2.10.3",
    "nodegit": "^0.4.1",
    "promisify-node": "^0.1.5",
    "rimraf": "^2.4.0",
    "stopwords": "0.0.4",
    "string": "^3.3.0",
    "swig": "^1.4.2",
    "time-grunt": "^1.2.1",
    "yaml-front-matter": "^3.2.3"
  }
```

(The full `package.json` [is here](https://gist.github.com/cdcarson/7f93a5b8a2ae73ee71b9).)

`npm install` stopped working after I added `promisify-node` to the dependencies.  After removing `promisify-node` the install succeeds. Also, perhaps interestingly, if I add promisify after installing nodegit, everything's fine.

The output from `npm install` seems to say there's an error in `lifecycleScripts/install`, and it's pretty obvious that the install script is having a problem with `promisify-node`.

```
Chris-Dev:nog chris$ npm install
-
> nodegit@0.4.1 install /Users/chris/dev/nog/node_modules/nodegit
> node lifecycleScripts/install
 
module.js:338
    throw err;
          ^
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/chris/dev/nog/node_modules/promisify-node/index.js:107:15)
    at Object.<anonymous> (/Users/chris/dev/nog/node_modules/nodegit/lifecycleScripts/retrieveExternalDependencies.js:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
 
npm ERR! nodegit@0.4.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.4.1 install script 'node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chris/dev/nog/npm-debug.log
```

The NPM debug log: [npm-debug.log](https://gist.githubusercontent.com/cdcarson/a6aff54408396f1a80d0/raw/gistfile1.txt)

I'm on OSX 10.10.3.

```
Chris-Dev:nog chris$ npm -v
2.7.5
Chris-Dev:nog chris$ node -v
v0.12.2
```

Let me know if you need any more info.  Thanks,

Chris

**Comment by johnhaley81** [comment]
Hey @cdcarson. PR #615 might solve this problem but tbh I'm not completely sure why it's failing. Lets check back after that is merged in.

**Comment by thisconnect** [comment]
I ran into the same error on travis while playing around with travis cache (https://github.com/thisconnect/nodegit-kit/commit/3f6af3f2e7521ae648a114984f178cf821f004cb)

Starting the install lifecycle script on `postinstall` might solve this issue. I personally prefer `postinstall` over `install` anytime.

https://github.com/nodegit/nodegit/blob/277110427e31a4d5f06d00e36223dcfce514c0a7/package.json#L89
