### ISSUE TITLE
binary installation fails inside docker container

### ISSUE THREAD

**Issue by briceburg** [nodegit/nodegit#644]
when `npm install nodegit` is executed inside a docker container, the binary installation fails and manual compilation is used. 

on the host (outside of the container), `npm install nodegit` uses the binary.

I have tried this in debian:jessie and node:0.12 docker containers, e.g.

```sh
docker run -it debian:jessie bash

root@1c3df1a30ec2:/# npm install nodegit
-
> nodegit@0.4.1 install /node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
...
```

uname -a
```sh
#container
root@1c3df1a30ec2:/# uname -a
Linux 1c3df1a30ec2 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux

#host
nodegit $ uname -a
Linux toshiba 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux
```

prefer the quickest build times. if binary will not work in container, can I prioritize the manual build process over fetching binary?? Also I oticed the lifecycleScripts/clean.js is not executed after it gets built manually.

Many thanks!

~ Brice

**Comment by electricmonk** [comment]
+1

**Comment by saper** [comment]
maybe there is a networking problem is it can't get out to s3 to fetch the file?

**Comment by electricmonk** [comment]
@saper I actually have no way of knowing. On the other hand, `npm install` succeeds so at least it manages to get to `registry.npmjs.org`.

**Comment by saper** [comment]
Well, I have no way of knowing, either...

**Comment by electricmonk** [comment]
I opened #758 to try and figure out why

**Comment by samkelleher** [comment]
I'm using Alpine as my Docker base image (which has minimal packages installed). If I build my project on OSX, the nodegit compile works (using a brew installed openssl, not the built in version). However, the resulting binary doesn't run within the linux container. Building the image on the linux container itself during build seems to take a long time and I'm having no success (last error `cannot find OpenSSL or Libgcrypt`, even though those packages are installed). I'm trying to find the binaries, as one must exist for linux x64?

**Comment by maxkorp** [comment]
Have you tried installing openssl-devel (or whatever the related package name for alipine is)?

**Comment by samkelleher** [comment]
Yeh I install a bunch of packages (`openssh python build-base openssl-dev file libgcrypt-dev pacman`) and get the same result. I've also tried in debian with no change.

I suspect that the compile of some dependency is what's causing the hold up. Checking out nodegit in a vanilla linux vm doesn't build for me (the build completes, but the build directory remains empty).

I have the same issue as seen in https://github.com/nodegit/nodegit/issues/728 and have dumped the build log file there.

**Comment by johnhaley81** [comment]
@briceburg @samkelleher can you guys try installing 0.6.0?

**Comment by briceburg** [comment]
alpine linux works well, binary is downloaded out-of-box ::

```sh
 docker run --rm -it alpine sh

# apk add --update nodejs
# npm install nodegit
> nodegit@0.6.0 install /root/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.
nodegit@0.6.0 node_modules/nodegit
âââ promisify-node@0.3.0
âââ nodegit-promise@4.0.0 (asap@2.0.3)
âââ fs-extra@0.26.2 (path-is-absolute@1.0.0, klaw@1.1.2, jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.4)
```

debian:jessie was unable to download the binary out of box, but compilation was successful this time:

```
docker run --rm -it debian:jessie sh
# apt-get install npm
# npm install nodegit
npm WARN engine nodegit@0.6.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
-
> nodegit@0.6.0 install /root/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.0-node-v11-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/root/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at Request.emit (events.js:117:20)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/root/node_modules/nodegit/node_modules/node-pre-gyp/node_modules/request/request.js:951:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
node-pre-gyp ERR! stack     at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
node-pre-gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:511:12)
node-pre-gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:323:10)
node-pre-gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:366:25)
node-pre-gyp ERR! System Linux 4.2.3-1-ARCH
node-pre-gyp ERR! command "node" "/root/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /root/node_modules/nodegit
node-pre-gyp ERR! node -v v0.10.29
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
] killed: false, code: 1, signal: null }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
nan@2.0.9 node_modules/nan

combyne@0.8.1 node_modules/combyne

clean-for-publish@1.0.4 node_modules/clean-for-publish
âââ glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
âââ yargs@3.29.0 (decamelize@1.1.1, camelcase@1.2.1, window-size@0.1.4, y18n@3.2.0, os-locale@1.4.0, cliui@3.1.0)

js-beautify@1.5.10 node_modules/js-beautify
âââ nopt@3.0.6 (abbrev@1.0.7)
âââ config-chain@1.1.9 (ini@1.3.4, proto-list@1.2.4)
âââ mkdirp@0.5.1 (minimist@0.0.8)

mocha@2.3.4 node_modules/mocha
âââ escape-string-regexp@1.0.2
âââ supports-color@1.2.0
âââ growl@1.8.1
âââ commander@2.3.0
âââ diff@1.4.0
âââ debug@2.2.0 (ms@0.7.1)
âââ mkdirp@0.5.0 (minimist@0.0.8)
âââ glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
âââ jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

lcov-result-merger@1.0.2 node_modules/lcov-result-merger
âââ vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
âââ through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
âââ vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)

coveralls@2.11.5 node_modules/coveralls
âââ lcov-parse@0.0.6
âââ log-driver@1.2.4
âââ js-yaml@3.0.1 (argparse@0.1.16, esprima@1.0.4)
âââ request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.1, form-data@1.0.0-rc3, mime-types@2.1.8, bl@1.0.0, http-signature@1.1.0, hawk@3.1.2, har-validator@2.0.3)

lodash@3.10.1 node_modules/lodash

node-gyp@3.0.3 node_modules/node-gyp
âââ graceful-fs@4.1.2
âââ nopt@3.0.6 (abbrev@1.0.7)
âââ semver@5.1.0
âââ which@1.2.0 (is-absolute@0.1.7)
âââ osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
âââ minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
âââ mkdirp@0.5.1 (minimist@0.0.8)
âââ fstream@1.0.8 (inherits@2.0.1)
âââ glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
âââ path-array@1.0.0 (array-index@0.1.1)
âââ rimraf@2.4.4 (glob@5.0.15)
âââ tar@1.0.3 (block-stream@0.0.8, inherits@2.0.1)
âââ npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.5, gauge@1.2.2)
âââ request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, oauth-sign@0.8.0, tunnel-agent@0.4.2, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.7, qs@5.2.0, mime-types@2.1.8, form-data@1.0.0-rc3, tough-cookie@2.2.1, bl@1.0.0, http-signature@1.1.0, har-validator@2.0.3, hawk@3.1.2)

nw-gyp@0.12.4 node_modules/nw-gyp
âââ graceful-fs@2.0.3
âââ nopt@2.2.1 (abbrev@1.0.7)
âââ which@1.2.0 (is-absolute@0.1.7)
âââ osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
âââ npmlog@0.1.1 (ansi@0.3.0)
âââ semver@2.2.1
âââ minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.7.3)
âââ mkdirp@0.5.1 (minimist@0.0.8)
âââ fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8)
âââ glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
âââ tar@0.1.20 (inherits@2.0.1, block-stream@0.0.8)
âââ rimraf@2.4.4 (glob@5.0.15)
âââ request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, oauth-sign@0.8.0, tunnel-agent@0.4.2, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.7, qs@5.2.0, mime-types@2.1.8, form-data@1.0.0-rc3, tough-cookie@2.2.1, bl@1.0.0, http-signature@1.1.0, har-validator@2.0.3, hawk@3.1.2)

jshint@2.8.0 node_modules/jshint
âââ strip-json-comments@1.0.4
âââ exit@0.1.2
âââ console-browserify@1.1.0 (date-now@0.1.4)
âââ shelljs@0.3.0
âââ minimatch@2.0.10 (brace-expansion@1.1.2)
âââ cli@0.6.6 (glob@3.2.11)
âââ htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
âââ lodash@3.7.0

istanbul@0.3.22 node_modules/istanbul
âââ abbrev@1.0.7
âââ once@1.3.3 (wrappy@1.0.1)
âââ nopt@3.0.6
âââ wordwrap@1.0.0
âââ supports-color@3.1.2 (has-flag@1.0.0)
âââ async@1.5.0
âââ esprima@2.5.0
âââ which@1.2.0 (is-absolute@0.1.7)
âââ mkdirp@0.5.1 (minimist@0.0.8)
âââ resolve@1.1.6
âââ fileset@0.2.1 (minimatch@2.0.10, glob@5.0.15)
âââ escodegen@1.7.1 (estraverse@1.9.3, esutils@2.0.2, optionator@0.5.0, source-map@0.2.0, esprima@1.2.5)
âââ js-yaml@3.4.6 (inherit@2.2.2, esprima@2.7.1, argparse@1.0.3)
âââ handlebars@4.0.5 (source-map@0.4.4, optimist@0.6.1, uglify-js@2.6.1)

[nodegit] Configuring libssh2.
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Compilation complete.
[nodegit] Completed installation successfully.
nodegit@0.6.0 node_modules/nodegit
âââ promisify-node@0.3.0
âââ nodegit-promise@4.0.0 (asap@2.0.3)
âââ fs-extra@0.26.2 (path-is-absolute@1.0.0, klaw@1.1.2, jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.4)

```

@johnhaley81 thanks for the followup and let me know if I can help.

**Comment by johnhaley81** [comment]
Glad it works now. Strange that you're getting `403` back from the server. I'm closing this out since it's resolved.

**Comment by maxkorp** [comment]
403 is because the file doesnt exist and the box denies directory listings. We don't publish for node 10, since we don't officially support node 10 (most stuff works, but there are a few weird segfaults via http_parser)

**Comment by johnhaley81** [comment]
Ahh, didn't notice node 10. Thanks@
