### ISSUE TITLE
libssh2_config.h: No such file or directory

### ISSUE THREAD

**Issue by xifeiwu** [nodegit/nodegit#650]
../vendor/libssh2/src/libssh2_priv.h:44:28: fatal error: libssh2_config.h: No such file or directory

**Comment by maxkorp** [comment]
@xifeiwu Do you still get this issue trying to build master?

**Comment by samkelleher** [comment]
Compiling `0.5 master` gives the same error. Tried on clean and latest Ubuntu and Debian.

**Comment by maxkorp** [comment]
if you cd into vendor/libssh2 and try `./configure` do you get any errors?

**Comment by samkelleher** [comment]
Yeh I just end up getting the same error as seen in #728 
```
checking for libssl... no
checking for libgcrypt... no
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH
```

```
root@36407269e7f8:/nodegit4/vendor/libssh2# which openssl
/usr/bin/openssl
root@36407269e7f8:/nodegit4/vendor/libssh2# openssl version
OpenSSL 1.0.1f 6 Jan 2014
root@36407269e7f8:/nodegit4/vendor/libssh2#
```

I've had this issue on Debian Jessie, and Alpine and Ubuntu Trusty. I've installed gcc 4.9. There must be a package missing somewhere. Trying to narrow it down.

**Comment by samkelleher** [comment]
I installed `libssl-dev` on Ubuntu and it built normally! 🎉 However, just like the other ticket, the build completes, the Release directory is empty, and config.log in the libssh2 folder is filled with errors about missing files. Fixes one error to give another.

**Comment by tbranyen** [comment]
I think we have a chicken & egg problem here. We are running the libssh2 configuration before openssl is built. I'm looking into how to do this all within GYP, because right now the libssh config is a lifecycle script.

Basically what I'm imagining we need:

- Build libssh2 (requires openssl)
- openssl builds
- libssh2 configure runs, pointing to the newly built openssl (not sure how to do this with GYP)
- libssh2 compiles
- everyone is happy

**Comment by samkelleher** [comment]
In #774 I split apart the promises that kicked off the build and forced one to wait for the previous to complete and since then the builds have been successful for me on Ubuntu.

**Comment by johnhaley81** [comment]
@samkelleher let me know if you still get this as well please.

**Comment by webjay** [comment]
This also just happened to me with `cd node_modules/nodegit && npm run-script recompile` on Heroku:

    In file included from ../vendor/libssh2/src/agent.c:40:0:
    ../vendor/libssh2/src/libssh2_priv.h:44:28: fatal error: libssh2_config.h: No such file or directory
     #include "libssh2_config.h"
                                ^
    compilation terminated.
    make: *** [Release/obj.target/libssh2/vendor/libssh2/src/agent.o] Error 1
    make: Leaving directory `/app/node_modules/nodegit/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.13.0-71-generic
    gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
    gyp ERR! cwd /app/node_modules/nodegit
    gyp ERR! node -v v5.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 

    npm ERR! Linux 3.13.0-71-generic
    npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "run-script" "recompile"
    npm ERR! node v5.1.1
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! nodegit@0.11.1 recompile: `node-gyp configure build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the nodegit@0.11.1 recompile script 'node-gyp configure build'.

**Comment by maxkorp** [comment]
I bet there was an error in your initial install. `npm install` inside that directory should either fix it, or replay the error. That's our best bet at figuring out what died.

**Comment by webjay** [comment]
I tried again: `heroku run "npm install && cd node_modules/nodegit && npm install && npm run-script recompile"`:

    In file included from ../vendor/libssh2/src/agent.c:40:0:
    ../vendor/libssh2/src/libssh2_priv.h:44:28: fatal error: libssh2_config.h: No such file or directory
     #include "libssh2_config.h"
                                ^
    compilation terminated.
    make: *** [Release/obj.target/libssh2/vendor/libssh2/src/agent.o] Error 1
    make: Leaving directory `/app/node_modules/nodegit/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.13.0-71-generic
    gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
    gyp ERR! cwd /app/node_modules/nodegit
    gyp ERR! node -v v5.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 

    npm ERR! Linux 3.13.0-71-generic
    npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "run-script" "recompile"
    npm ERR! node v5.1.1
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! nodegit@0.11.1 recompile: `node-gyp configure build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the nodegit@0.11.1 recompile script 'node-gyp configure build'.

**Comment by maxkorp** [comment]
What about without the `npm run-script recompile`
