### ISSUE TITLE
diff-commits.js example is broken

### ISSUE THREAD

**Issue by asgeirbirkis** [nodegit/nodegit#673]
It appears the `diff-commits.js` example is broken on v0.4.1. When I clone a fresh copy of nodegit, and try running it, this is the output:

```
node diff-commits.js 
commit 59b20b8d5c6ff8d09518454d4dd8b7b30f095ab5
Author: tbranyen <tim@tabdeveloper.com>
Date: Sat Apr 09 2011 01:48:49 GMT+0100 (BST)

    Updated gitignore and raw-commit test

/usr/local/lib/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/asap.js:45
                throw e;
                      ^
TypeError: undefined is not a function
    at /Users/ab/github/nodegit/examples/diff-commits.js:23:20
    at Array.forEach (native)
    at /Users/ab/github/nodegit/examples/diff-commits.js:22:12
    at /usr/local/lib/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:63:15
    at flush (/usr/local/lib/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)
```

So to summarize, it works to print info about the commit, but not the diffs.

**Comment by rcjsuen** [comment]
Is the example still broken, @asgeirbirkis? I ran `examples/diff-commits.js` today and it completed without any errors.

**Comment by johnhaley81** [comment]
I can run the example on master as well. Closing this out.
