### ISSUE TITLE
Error building on RHEL6.6

### ISSUE THREAD

**Issue by chetanddesai** [nodegit/nodegit#683]
Any idea if `nodegit@0.4.1` is RHEL6.6 compatible?  Getting the following error:
```
> nodegit@0.4.1 install /myapp/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.

{ [Error: Command failed: ../vendor/libssh2/src/openssl.c: In function ‘_libssh2_pub_priv_keyfile’:
../vendor/libssh2/src/openssl.c:767: warning: value computed is not used
../vendor/libssh2/src/transport.c: In function ‘_libssh2_transport_send’:
../vendor/libssh2/src/transport.c:716: warning: suggest braces around empty body in an ‘if’ statement
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/myapp/node_modules/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-504.23.4.el6.x86_64
gyp ERR! command "node" "/myapp/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /myapp/node_modules/nodegit
gyp ERR! node -v v0.10.36
gyp ERR! pangyp -v v2.3.0
gyp ERR! not ok 
] killed: false, code: 1, signal: null }
undefined
```

**Comment by maxkorp** [comment]
You need a newer version of GCC installed, at least 4.7. We use the chrono library from std11, which requires gcc 4.7+. We offer prebuilts for many platforms, are you running x64?

**Comment by chetanddesai** [comment]
@maxkorp that fixed it - we had to use a newer version of gcc.  Thanks for the help!
