### ISSUE TITLE
Nodegit build fails with Electron 0.31.x / 0.32.x

### ISSUE THREAD

**Issue by ssreekanth** [nodegit/nodegit#686]
Building Nodegit native module against Electron 0.31.0 fails.

```
[nodegit] Detecting vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5.
[nodegit] Detecting vendor/libssh2/1.4.3.
[nodegit] Detecting vendor/http_parser/2.5.0.
[nodegit] Detecting generated code.
[nodegit] vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5 already exists.
[nodegit] vendor/libssh2/1.4.3 already exists.
[nodegit] Generated code is intact.
[nodegit] Removing outdated vendor/http_parser/.
[nodegit] Retrieving vendor/http_parser/.
[nodegit] Successfully updated vendor/http_parser/2.5.0.
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c HOME=~/.atom-shell-gyp /home/builder/Downloads/_personal_work/bustr/app/node_modules/nodegit/node_modules/.bin/pangyp rebuild --target=0.31.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist
In file included from ../vendor/openssl/openssl/include/openssl/bio.h:1:0,
                 from ../vendor/openssl/openssl/include/openssl/../../crypto/evp/evp.h:75,
                 from ../vendor/openssl/openssl/include/openssl/evp.h:1,
                 from ../vendor/libssh2/src/openssl.h:45,
                 from ../vendor/libssh2/src/crypto.h:44,
                 from ../vendor/libssh2/src/libssh2_priv.h:132,
                 from ../vendor/libssh2/src/openssl.c:41:
../vendor/libssh2/src/openssl.c: In function ‘_libssh2_pub_priv_keyfile’:
../vendor/openssl/openssl/include/openssl/../../crypto/bio/bio.h:567:23: warning: value computed is not used [-Wunused-value]
 #define BIO_reset(b)  (int)BIO_ctrl(b,BIO_CTRL_RESET,0,NULL)
                       ^
../vendor/libssh2/src/openssl.c:767:5: note: in expansion of macro ‘BIO_reset’
     BIO_reset(bp);
     ^
../vendor/libssh2/src/transport.c: In function ‘_libssh2_transport_send’:
../vendor/libssh2/src/transport.c:716:79: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
         debugdump(session, "libssh2_transport_write plain2", data2, data2_len);
                                                                               ^
../vendor/libssh2/src/knownhost.c: In function ‘libssh2_knownhost_writefile’:
../vendor/libssh2/src/knownhost.c:1100:16: warning: ‘wrote’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         nwrote = fwrite(buffer, 1, wrote, file);
                ^
../vendor/openssl/openssl/crypto/modes/cbc128.c: In function ‘CRYPTO_cbc128_decrypt’:
../vendor/openssl/openssl/crypto/modes/cbc128.c:175:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
      *(size_t *)(tmp.c+n) ^ *(size_t *)(ivec+n);
      ^
../vendor/openssl/openssl/crypto/modes/ccm128.c: In function ‘CRYPTO_ccm128_setiv’:
../vendor/openssl/openssl/crypto/modes/ccm128.c:90:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(u32*)(&ctx->nonce.c[8]) = 0;
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_cts128_encrypt’:
../vendor/openssl/openssl/crypto/modes/cts128.c:114:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = 0;
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_nistcts128_encrypt’:
../vendor/openssl/openssl/crypto/modes/cts128.c:150:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = 0;
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_cts128_decrypt_block’:
../vendor/openssl/openssl/crypto/modes/cts128.c:181:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = *(size_t *)(tmp.c+16+n);
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c:181:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_nistcts128_decrypt_block’:
../vendor/openssl/openssl/crypto/modes/cts128.c:224:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = *(size_t *)(tmp.c+16+n);
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c:224:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_cts128_decrypt’:
../vendor/openssl/openssl/crypto/modes/cts128.c:261:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = 0;
   ^
../vendor/openssl/openssl/crypto/modes/cts128.c: In function ‘CRYPTO_nistcts128_decrypt’:
../vendor/openssl/openssl/crypto/modes/cts128.c:301:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *(size_t *)(tmp.c+n) = 0;
   ^
../vendor/openssl/openssl/crypto/modes/gcm128.c: In function ‘CRYPTO_gcm128_encrypt’:
../vendor/openssl/openssl/crypto/modes/gcm128.c:952:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(size_t *)(in+i)^*(size_t *)(ctx->EKi.c+i);
     ^
../vendor/openssl/openssl/crypto/modes/gcm128.c:972:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(size_t *)(in+i)^*(size_t *)(ctx->EKi.c+i);
     ^
../vendor/openssl/openssl/crypto/modes/gcm128.c: In function ‘CRYPTO_gcm128_decrypt’:
../vendor/openssl/openssl/crypto/modes/gcm128.c:1102:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(size_t *)(in+i)^*(size_t *)(ctx->EKi.c+i);
     ^
../vendor/openssl/openssl/crypto/modes/gcm128.c:1120:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(size_t *)(in+i)^*(size_t *)(ctx->EKi.c+i);
     ^
In file included from ../src/../include/wrapper.h:11:0,
                 from ../src/nodegit.cc:6:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/../include/wrapper.h:11,
                 from ../src/nodegit.cc:6:
/home/builder/.atom-shell-gyp/.node-gyp/0.31.0/src/node_buffer.h:38:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/builder/.atom-shell-gyp/.node-gyp/0.31.0/src/node_buffer.h:38:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/builder/.atom-shell-gyp/.node-gyp/0.31.0/src/node_buffer.h:50:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/builder/.atom-shell-gyp/.node-gyp/0.31.0/src/node_buffer.h:50:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/../include/wrapper.h:11:0,
                 from ../src/nodegit.cc:6:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/builder/Downloads/_personal_work/bustr/app/node_modules/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-62-generic
gyp ERR! command "node" "/home/builder/Downloads/_personal_work/bustr/app/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild" "--target=0.31.0" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd /home/builder/Downloads/_personal_work/bustr/app/node_modules/nodegit
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.3.0
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c HOME=~/.atom-shell-gyp /home/builder/Downloads/_personal_work/bustr/app/node_modules/nodegit/node_modules/.bin/pangyp rebuild --target=0.31.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist' }
undefined
nodegit@0.4.1 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── fs-extra@0.18.4 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.2)
└── npm@2.14.0
```

**Comment by ssreekanth** [comment]
It could be because of io.js upgrade in Electron v0.31.0.

https://github.com/atom/electron/releases/tag/v0.31.0

**Upgrade notice: (from the above link)**
   * Most native modules are broken because of io.js upgrade, modules writers need to use NAN v2 to rewrite the modules.

**Comment by ssreekanth** [comment]
Any chance to fix this?

**Comment by ssreekanth** [comment]
Any chance to bump up NAN dependency version to the latest?

**Comment by johnhaley81** [comment]
It's definitely the bump to NAN v2. We have to update our code templates to support it. I don't know when we're going to be able to get around to it but we will bump to latest NAN soon.

**Comment by neutrinog** [comment]
It would be great to get this resolved. I'm looking for a git solution that works with io.js as well.

**Comment by maxkorp** [comment]
Yeah it works with iojs2, but electron moved to iojs3. I've started trying to make the move, but more breaks than I'd hoped.

**Comment by ssreekanth** [comment]
@maxkorp Nice to hear the update from you. I can't wait to see the working nodegit with io.js 3.x. Keep us posted with more updates on this.

**Comment by johnhaley81** [comment]
#702 should hopefully get this going

**Comment by ssreekanth** [comment]
@johnhaley81 any luck in fixing this?

**Comment by johnhaley81** [comment]
Working in OSX/Linux but still not in Windows. I don't have access to a windows box right now for dev so if you are able to take a look I'd definitely appreciate it!

**Comment by ssreekanth** [comment]
I don't have windows machine either. Planning to get one in the near future.

**Comment by maxkorp** [comment]
This should be fixed with https://github.com/nodegit/nodegit/pull/702
