### ISSUE TITLE
Not working properly on Node.js 4.0.0

### ISSUE THREAD

**Issue by pandres95** [nodegit/nodegit#704]
Tried to install nodegit on v4.0.0 but couldn't fetch binary. Also, there wasn't binding settings to manually build libraries.

```
> nodegit@0.4.1 install /Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Something is missing, retrieving dependencies and regenerating code
combyne@0.8.1 node_modules/combyne

nan@1.9.0 node_modules/nan

tar@2.2.1 node_modules/tar
├── inherits@2.0.1
├── block-stream@0.0.8
└── fstream@1.0.8 (graceful-fs@4.1.2, mkdirp@0.5.1, rimraf@2.4.3)

request@2.61.0 node_modules/request
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── caseless@0.11.0
├── oauth-sign@0.8.0
├── tunnel-agent@0.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.3
├── qs@4.0.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── form-data@1.0.0-rc3 (async@1.4.2)
├── mime-types@2.1.6 (mime-db@1.18.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.2)
├── tough-cookie@2.0.0
├── hawk@3.1.0 (cryptiles@2.0.5, sntp@1.0.9, boom@2.8.0, hoek@2.15.0)
└── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, is-my-json-valid@2.12.2, bluebird@2.10.0)

js-beautify@1.5.10 node_modules/js-beautify
├── config-chain@1.1.9 (ini@1.3.4, proto-list@1.2.4)
├── nopt@3.0.4 (abbrev@1.0.7)
└── mkdirp@0.5.1 (minimist@0.0.8)

lcov-result-merger@1.0.2 node_modules/lcov-result-merger
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, defaults@1.0.2, strip-bom@1.0.0, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)

coveralls@2.11.4 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (aws-sign2@0.5.0, forever-agent@0.5.2, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, qs@1.0.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, hawk@1.1.1, tough-cookie@2.0.0)
└── js-yaml@3.0.1 (argparse@0.1.16, esprima@1.0.4)

nw-gyp@0.12.4 node_modules/nw-gyp
├── graceful-fs@2.0.3
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nopt@2.2.1 (abbrev@1.0.7)
├── npmlog@0.1.1 (ansi@0.3.0)
├── semver@2.2.1
├── which@1.1.2 (is-absolute@0.1.7)
├── minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.8)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── rimraf@2.4.3 (glob@5.0.14)

lodash@3.10.1 node_modules/lodash

istanbul@0.3.19 node_modules/istanbul
├── supports-color@1.3.1
├── which@1.0.9
├── abbrev@1.0.7
├── async@1.4.2
├── wordwrap@0.0.3
├── nopt@3.0.4
├── once@1.3.2 (wrappy@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── esprima@2.5.0
├── resolve@1.1.6
├── fileset@0.2.1 (glob@5.0.14, minimatch@2.0.10)
├── js-yaml@3.4.2 (esprima@2.2.0, argparse@1.0.2)
├── escodegen@1.6.1 (esutils@1.1.6, estraverse@1.9.3, optionator@0.5.0, source-map@0.1.43, esprima@1.2.5)
└── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)

pangyp@2.3.2 node_modules/pangyp
├── which@1.0.9
├── rimraf@2.2.8
├── graceful-fs@3.0.8
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nopt@3.0.4 (abbrev@1.0.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── semver@4.3.6
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.2)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── npmlog@1.0.0 (ansi@0.3.0, gauge@1.0.2, are-we-there-yet@1.0.4)
└── request@2.51.0 (caseless@0.8.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, qs@2.3.3, node-uuid@1.4.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.4, http-signature@0.10.1, form-data@0.2.0, hawk@1.1.1, tough-cookie@2.0.0)

mocha@2.3.2 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@1.11.0 (character-parser@1.2.1, void-elements@2.0.1, commander@2.6.0, jstransformer@0.0.2, constantinople@3.0.2, with@4.0.3, clean-css@3.4.1, transformers@2.1.0, uglify-js@2.4.24)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── shelljs@0.3.0
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0

npm@2.14.3 node_modules/npm

[nodegit] Detecting vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5.
[nodegit] Detecting vendor/libssh2/1.4.3.
[nodegit] Detecting vendor/http_parser/2.5.0.
[nodegit] Detecting generated code.
[nodegit] vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5 already exists.
[nodegit] vendor/libssh2/1.4.3 already exists.
[nodegit] Generated code is intact.
[nodegit] Removing outdated vendor/http_parser/.
[nodegit] Retrieving vendor/http_parser/.
[nodegit] Successfully updated vendor/http_parser/2.5.0.
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit/node_modules/.bin/pangyp rebuild
gyp: /Users/pandres95/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/pandres95/Documents/Bool/Development/Frameworks/booljs/booljs-cli/node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined
nodegit@0.4.1 node_modules/nodegit
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
└── fs-extra@0.18.4 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.3)
```

**Comment by tbranyen** [comment]
We're working on it here: https://github.com/nodegit/nodegit/pull/702

**Comment by abd3** [comment]
See here: http://stackoverflow.com/questions/17967546/common-gypi-not-found-error-in-node-js

rm -rf ~/.node_gyp
cd myAwesomeProject
npm install
npm rebuild
