### ISSUE TITLE
Installing errors on Mac OS X El Capitan

### ISSUE THREAD

**Issue by arusakov** [nodegit/nodegit#737]
My [npm-debug.log](https://cloud.mail.ru/public/HYND/gz53u7Z6f).

index.js:
```javascript
var Git = require("nodegit");
```

And when i tried ```node index.js``` i see:
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'nodegit'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/arusakov/WebstormProjects/distbranch/index.js:1:73)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by thgaskell** [comment]
Did you `npm install nodegit`?

**Comment by arusakov** [comment]
@thgaskell yes

**Comment by saper** [comment]
It tries to compile the module from scratch and fails. Do you have Xcode installed?

**Comment by tbranyen** [comment]
We do have a prebuilt binary published, I'm wondering what version of Node?

**Comment by arusakov** [comment]
@saper I have installed XCode.
@tbranyen node.js 4.1.1

**Comment by johnhaley81** [comment]
Maybe we need to publish a binary for El Capitan?

**Comment by tbranyen** [comment]
Yeah, I haven't done that yet

**Comment by johnhaley81** [comment]
I just updated to El Capitan and what's going on is that Apple moved away from OpenSSL in lieu of their own home-rolled TLS implementation. Looking into this further.

**Comment by johnhaley81** [comment]
I just published binaries. Can you guys try again please?

**Comment by arusakov** [comment]
@johnhaley81 Installation completed without errors, it's perfect. Thank you!

**Comment by johnhaley81** [comment]
You're welcome! Glad it's working for you.
