### ISSUE TITLE
Installing nodegit@0.5.0 on Mac OS X El Capitan fails

### ISSUE THREAD

**Issue by ifoukarakis** [nodegit/nodegit#811]
Hi,

I can't install nodegit@0.5.0.  I tried:

```
$ npm i nodegit

> nodegit@0.5.0 install /Users/smarttv/tmp/temp/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Regenerating and configuring code
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/Users/smarttv/tmp/temp/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.1

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/smarttv/tmp/temp/node_modules/nodegit/npm-debug.log

temp@1.0.0 /Users/smarttv/tmp/temp
└── nodegit@0.5.0  extraneous

npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.

$ node index.js
module.js:340
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/username/tmp/temp/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

index.js looks like:
```
var Git = require("nodegit");
```

Here's my node and npm versions:
```
$ node -v
v5.1.0

$ npm -v
3.5.1
```

**Comment by dijam** [comment]
I have the same issue. Also this page is also failing: https://tonicdev.com/npm/nodegit

**Comment by johnhaley81** [comment]
Can you guys try with 0.6.0 and see if it's working now?

**Comment by johnhaley81** [comment]
Since this is working in #737 now I'm closing this out. Feel free to re-open if you still are having issues.

**Comment by maxkorp** [comment]
I don't believe they'll be able to reopen since one of us closed it and not them, but comment and we can reopen.

**Comment by ifoukarakis** [comment]
Still the same issue. I tried on a clean repo
npm i nodegit@0.5.0 and then the rest of the previous ticket.

**Comment by johnhaley81** [comment]
Try on NodeGit 0.6.3
