### ISSUE TITLE
DLL initialisation routine failed in Electron on Windows - nodegit v0.6.0, Electron v0.36.0

### ISSUE THREAD

**Issue by RichardLewin87** [nodegit/nodegit#828]
I have followed the instructions to successfully install nodegit for Electron. However, upon starting the Electron App nodegit fails to initialise with a DLL initialisation error. Please find below what I get.

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Richard\Documents\ElectronAppv36\electron-v0.36.0-win32-x64\resources\app\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Richard\Documents\ElectronAppv36\electron-v0.36.0-win32-x64\resources\app\node_modules\nodegit\lib\nodegit.js:8:12)
    at Module._compile (module.js:425:26)

After searching the web plus the issue list here on GitHub I have been unable to figure out a solution. Has anyone had this issue themselves and know the reason and solution?

Thanks in advance.

**Comment by maxkorp** [comment]
The docs are most likely out of date at this point, and you probably have a vanilla node build. I'll get you some config for npm that should fix it.

**Comment by maxkorp** [comment]
you need to install nodegit with the following environment variables set

`npm_config_runtime`: `electron`
`npm_config_disturl`: `https://atom.io/download/atom-shell`
`npm_config_target`: `0.36.0` (or whichever version you're using)
`npm_config_target_arch`: `x64` or `ia32` (the arch that your electron app runs in). 

Doing things this way will actually make all* of your modules compile for electron

* by all, I mean any that don't do something weird that would prevent them from following the default node-gyp compile timeline.

**Comment by RichardLewin87** [comment]
Hi Maxkorp,

Sorry to not reply over the weekend. Internet connection went down. Thanks for the reply and I'll try what you suggest today.

**Comment by RichardLewin87** [comment]
Maxkorp,

I have set the environment variables as you suggested via:

npm config set <key> <value> --global

Please let me know if this in oncorrect.

End result is that it is still coming up with the same DDL error when Electron starts up.

**Comment by RevillWeb** [comment]
Hi @maxkorp I am also having very similar issues, eagerly waiting a reply to @RichardLewin87's questions. Thanks for your time!

**Comment by fogaztuc** [comment]
Having same issue as documented in #795 - may want to close that as a duplicate now (started different but now looks to be the same).

**Comment by maxkorp** [comment]
I would definitely not do it globally, as that would prevent other modules from installing normally elsewhere on the machine. The way i do it is with an `.npmrc` file in my project

```
runtime = electron
target = 0.36.0 
target_arch = x64
dist_url = https://atom.io/download/atom-shell
```

**Comment by RichardLewin87** [comment]
Hi @maxkorp, just tried your suggestion by adding a .npmrc but i'm still getting a DLL error. @fogaztuc, have you had any luck if you've had a chance to try the .npmrc file route?

**Comment by fogaztuc** [comment]
In a meeting - will try and soon as I get out (will test on two different machines Windows 7 / 8).  Will see if I can get someone to test on Windows 10.

**Comment by maxkorp** [comment]
Oof, just republished the builds, can you pretty please try again?

**Comment by RichardLewin87** [comment]
@maxkorp thank you for the quick response. Just tried again but unfortunately still have the same issue. Am I still to aim at v0.6.0 in package.json? I've run out of time my side i'm afraid but will be back on it first thing tomorrow morning. I'm in GMT.

**Comment by maxkorp** [comment]
Yeah, I don't think we had binaries up for electron 0.36.0

**Comment by fogaztuc** [comment]
On it again... but I think the electron that is coming for me is 0.35.4 (even though I downloaded the latest - will try again)... may be a bit because I need to try the environment thing as well.

**Comment by maxkorp** [comment]
Yeah, those variables set via the npm configs will set what gets pulled, not your installed version of electron

**Comment by fogaztuc** [comment]
Downloaded Electron 0.36.0 directly via download (versus cloning quick-start which is still at 0.35.4).  Created a directory for the project.  Put some files in it including .npmrc as listed about. Did npm install nodegit.  Ran with a require("nodegit") in the base HTML file.  Now I get the DLL initialization error twice.  I am using node 5.1.1. Chrome 47.0.2526.73 and Electron 0.36.0.

**Comment by maxkorp** [comment]
Hrm, weird. I'm able to do it just fine :/

**Comment by fogaztuc** [comment]
@maxkorp can you give me the steps you are following?  Could be user error on my side ;-) I feel as though I must be missing some step our something.  Also are you on Windows 8 x64?

**Comment by maxkorp** [comment]
Windows 10 x64. 

So to strip it down to bare essentials, in a new project folder I have an `.npmrc` like i listed above. Then I run `npm install nodegit`. Then I run electron, with `require('nodegit')` in the script.

**Comment by fogaztuc** [comment]
Okay that appears to be what I am doing. We have a Windows difference let me try and eliminate that variable.

**Comment by tylerchurch** [comment]
I am seeing the same DLL loading error, and I am on Windows 10.

My exact steps:
1. `cd C:\`
2. `git clone https://github.com/atom/electron-quick-start`
3. `cd electron-quick-start`
4. Open `package.json` and change electron's version from 0.35.0 to 0.36.0.
5. `npm install`
6. Create `C:\electron-quick-start\.npmrc` with the following:
```
runtime = electron
target = 0.36.0 
target_arch = x64
dist_url = https://atom.io/download/atom-shell
```
7. `npm install nodegit@0.6.0`
8. Add `<script>require('nodegit');</script>` to `C:\electron-quick-start\index.html`
9. `npm start`

The error I get in the electron console:
```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\electron-quick-start\node_modules\nodegit\build\Release\nodegit.node
module.(anonymous function) @ ATOM_SHELL_ASAR.js:140
Module._extensions..node @ module.js:450
module.(anonymous function) @ ATOM_SHELL_ASAR.js:140
Module.load @ module.js:356
Module._load @ module.js:313
Module.require @ module.js:366
require @ module.js:385
(anonymous function) @ C:\electron-quick-start\node_modules\nodegit\lib\nodegit.js:8
Module._compile @ module.js:425
Module._extensions..js @ module.js:432
Module.load @ module.js:356
Module._load @ module.js:313
Module.require @ module.js:366
require @ module.js:385
(anonymous function) @ index.html:12
```

I am on Windows 10 x64 (Version 1511, build 10586.29)
Nodejs is v4.2.3
npm is v3.5.0

A zip of the folder I'm working with will be available here once my Dropbox syncs if anyone wants to take a look: https://dl.dropboxusercontent.com/u/108847970/electron-quick-start.zip

Note that if I just do `npm install nodegit` instead of `npm install nodegit@0.6.0` it fails to download the prebuilt binaries and I end up with an `npm-debug.log` file with this error in it:

```
8940 verbose stack TypeError: Cannot read property 'target' of null
8940 verbose stack     at module.exports (C:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\install\filter-invalid-actions.js:24:35)
8940 verbose stack     at Array.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8940 verbose stack     at LOOP (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8940 verbose stack     at C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8940 verbose stack     at Object.Installer.computeLinked (C:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\install.js:411:41)
8940 verbose stack     at Array.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8940 verbose stack     at LOOP (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8940 verbose stack     at C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8940 verbose stack     at module.exports (C:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\install\diff-trees.js:50:3)
8940 verbose stack     at Array.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8941 verbose cwd C:\electron-quick-start\node_modules\nodegit
8942 error Windows_NT 10.0.10586
8943 error argv "C:\\Program Files (x86)\\Nodist\\v-x64\\nodev4.2.3\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts"
```

Let me know if it sounds like I am doing anything wrong here, or if there is any more info I can provide.

**Comment by tylerchurch** [comment]
Here is what is printed to the console for just plain `npm install nodegit`:

```
C:\electron-quick-start>npm install nodegit@0.6.1

> nodegit@0.6.1 install C:\electron-quick-start\node_modules\nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\electron-quick-start\node_modules\nodegit\node_modules\.bin\node-pre-gyp install --fallback-to-build=false"
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.1-electron-v0.36-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\electron-quick-start\node_modules\nodegit\node_modules\node-pre-gyp\lib\install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\electron-quick-start\node_modules\nodegit\node_modules\node-pre-gyp\node_modules\request\request.js:951:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\nodev4.2.3\\node.exe" "C:\\electron-quick-start\\node_modules\\nodegit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\electron-quick-start\node_modules\nodegit
node-pre-gyp ERR! node -v v4.2.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "C:\\electron-quick-start\\node_modules\\nodegit\\node_modules\\.bin\\node-pre-gyp install --fallback-to-build=false"' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\nodev4.2.3\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.0

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\electron-quick-start\node_modules\nodegit\npm-debug.log

electron-quick-start@1.0.0 C:\electron-quick-start
└── nodegit@0.6.1  extraneous
```

**Comment by maxkorp** [comment]
Man, wtf. One odd idea, can you try installing with npm 2?

**Comment by maxkorp** [comment]
Ooh, well first off, yours failed to download, and then it looks like it failed to compile.

**Comment by maxkorp** [comment]
Man,s omething appears to be swallowing peoples build errors, and thats whats really behind this I think >.<

**Comment by tylerchurch** [comment]
Just an update from my side, I found something that seems to work.

Instead of installing directly into my electron app, I built nodegit separately, and then copied the built files into the `node_modules` folder of my electron app.

These are the exact commands I ran:

```
cd C:\
git clone https://github.com/nodegit/nodegit.git nodegit
cd nodegit
set npm_config_disturl=https://atom.io/download/atom-shell
set npm_config_target=0.36.0
set npm_config_arch=x64
set npm_config_runtime=electron
set HOME="C:\Users\Tyler Church\.electron-gyp"
npm install
```

And then I copied `C:\nodegit` to `C:\electron-quick-start\node_modules\nodegit`

Not sure why doing things this way would make any difference, but perhaps this will help someone.

**Comment by fogaztuc** [comment]
I can confirm that the above works for me on Windows 7.  Be sure to use command prompt versus Powershell (or set the variables appropriately using Powershell).

**Comment by fogaztuc** [comment]
When I was doing some copying in Windows was getting a path length error.  Wonder if the issue may have to do with what directory people build in and that directory causing path lengths to be exceeded during the build process.  I know that is one of the reasons Tyler switched to NPM 3.

**Comment by fogaztuc** [comment]
I can confirm this also works on Windows 8 (x64).

**Comment by RichardLewin87** [comment]
I have now got it building as suggested by @tylerchurch and running in Electron with success. So thanks for that one.

However, my call to the Clone function that works on my OSX Electron App is not working in the Windows Shell. To be more specific once asked to clone a public repository the promise to return the repository is not fired. I also kept an eye on the network activity when I asked for the clone and there is no activity in there.

Could someone try the clone command now that we appear to have got past the DLL issue and see if it is successful?

**Comment by tylerchurch** [comment]
Cloning appears to be successful for me.

I just used the example on nodegit's homepage:

```js
var Git = require("nodegit");

Git.Clone("https://github.com/nodegit/nodegit", "nodegit").then(function(repository) {
  // Work with the repository object here.
});
```

Perhaps there is an issue with the specific repo you are cloning or something?

**Comment by RichardLewin87** [comment]
@tylerchurch I must apologies, turns out the internet connection was being ridiculously slow when I tried earlier. Just tried again and yep, all is good now. So happy days now. Thanks again for the help guys. Unless it needs to be fixed so that it can be installed in the Electron project folder I consider this issue now closed for me.

**Comment by maxkorp** [comment]
So I may have found the issue. It seems that build errors aren't exiting properly, so the build for you guys is actually failing. The issue is related to gitignores, and when cloning, won't be present. Was able to repro locally with a coworker. nodegit 0.6.2 should have the fix, which went out this morning.

**Comment by tbranyen** [comment]
@maxkorp should we be using an .npmignore file to avoid issues with .gitignore?

**Comment by tylerchurch** [comment]
Just did an `npm install nodegit` in an electron project, and it seems to be working without any issues now!

So I think this issue can be closed.

**Comment by johnhaley81** [comment]
Awesome! Thanks for the fix confirmation @tylerchurch

**Comment by maxkorp** [comment]
@tbranyen yeah, the issue is with nested .gitignores when you have a root npmignore :(

**Comment by imor** [comment]
In my electron app, I was getting the same error on windows 10 and visual studio 2015, until I built against the electron headers. Just to document for others' (am my own future self) benefit, these were the steps that worked for me:

1. git clone https://github.com/nodegit/nodegit.git nodegit
2. cd nodegit
3. From advanced system settings, set the HOME environment variable to C:\Users\<YourUsernameHere>\.electron-gyp
4. Open visual studio 2015 command prompt
5. run npm install. It will fail with an error like: Macro definition of snprintf conflicts with Standard Library function declaration.
6. Open nodegit/vendor/libssh2/win32/libssh2_config.h file and replace this:

#ifdef _MSC_VER
#define snprintf _snprintf
#if _MSC_VER < 1500
#define vsnprintf _vsnprintf
#endif
#define strdup _strdup
#define strncasecmp _strnicmp
#define strcasecmp _stricmp
#else
#define strncasecmp strnicmp
#define strcasecmp stricmp
#endif /* _MSC_VER */


with this:

#ifdef _MSC_VER
#if _MSC_VER < 1900
#define snprintf _snprintf
#if _MSC_VER < 1500
#define vsnprintf _vsnprintf
#endif
#define strdup _strdup
#define strncasecmp _strnicmp
#define strcasecmp _stricmp
#endif
#else
#ifndef __MINGW32__
#define strncasecmp strnicmp
#define strcasecmp stricmp
#endif /* __MINGW32__ */
#endif /* _MSC_VER */

For details about why this works, see this: https://github.com/libssh2/libssh2/commit/ded55537acbfda9756667e054c22972842633cf4
7. Run the command: node-gyp rebuild --target=0.37.8 --arch=x64 --dist-url=https://atom.io/download/atom-shell
Remember to replace --target value with the version of your electron and --arch value with your architecture. This should build the project.
8. Copy the nodegit directory under the node_modules directory of your electron app. In the copied nodegit directory rename the lib folder to dist.
9. Enjoy!

**Comment by darkguy2008** [comment]
I can confirm this issue exists with Electron 1.6.5 and nodegit 0.18.1. @imor 's instructions worked great for my project. Thanks!
