### ISSUE TITLE
Error when using nodegit on linux

### ISSUE THREAD

**Issue by callmemagnus** [nodegit/nodegit#886]
Hi,

I have a simple script:
```js
var Git = require('nodegit');
```

I run it
```shell
$ node index.js

/home/callmemagnus/src/project/node_modules/nodegit/lib/nodegit.js:12
    throw ex;
    ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/callmemagnus/src/project/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/callmemagnus/src/project/node_modules/nodegit/lib/nodegit.js:7:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Digging a little:
```sh
$ dpkg -S /usr/lib/x86_64-linux-gnu/libstdc++.so.6
libstdc++6:amd64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6

$ npm list --depth=0
project@1.0.0 /home/callmemagnus/src/project
└── nodegit@0.9.0
```
And, I'm on an ubuntu 14.04 derivative
```sh
$ apt-cache show libstdc++6
Package: libstdc++6
Priority: important
Section: libs
Installed-Size: 1288
Maintainer: Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Architecture: amd64
Source: gcc-4.8
Version: 4.8.4-2ubuntu1~14.04
Replaces: libstdc++6-4.8-dbg (<< 4.8.2-22)
Depends: gcc-4.8-base (= 4.8.4-2ubuntu1~14.04), libc6 (>= 2.18), libgcc1 (>= 1:4.1.1)
Pre-Depends: multiarch-support
Conflicts: scim (<< 1.4.2-1)
Breaks: gcc-4.1, gcc-4.3 (<< 4.3.6-1), gcc-4.4 (<< 4.4.6-4), gcc-4.5 (<< 4.5.3-2)
Filename: pool/main/g/gcc-4.8/libstdc++6_4.8.4-2ubuntu1~14.04_amd64.deb
Size: 258784
MD5sum: bfe435106e74f02e4b5377753ce8d920
SHA1: 6e87b962aeb78d3191d3a40f7f72b2dd003110f4
SHA256: 947a98833bc502d172896aaa4fb058469e6f8b2dcb88d3cd70a963f8b95b7e7e
Description-en: GNU Standard C++ Library v3
 This package contains an additional runtime library for C++ programs
 built with the GNU compiler.
 .
 libstdc++-v3 is a complete rewrite from the previous libstdc++-v2, which
 was included up to g++-2.95. The first version of libstdc++-v3 appeared
 in g++-3.0.
Description-md5: 724ab84919e0e220afb960e36463914d
Multi-Arch: same
Homepage: http://gcc.gnu.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Build-Essential: yes
Origin: Ubuntu
Supported: 5y
Task: minimal
```

Do you know what I have to do have it working ?

Thanks in advance.

**Comment by tbranyen** [comment]
Please read the README, this is explained under installing. Thanks!
