### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DaAwesomeP** [nodegit/nodegit#890]
The first time that I installed, it was missing Zlib, so I installed `zlib1g-dev`. Now I have this (I removed all of the `unused-value` and `strict-aliasing` warnings):
```log
> nodegit@0.4.1 install /home/user/project/node_modules/nodegit
> node lifecycleScripts/install

nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /home/user/project/node_modules/nodegit/node_modules/.bin/pangyp rebuild
In file included from ../vendor/openssl/openssl/include/openssl/bio.h:1:0,
                 from ../vendor/openssl/openssl/include/openssl/../../crypto/evp/evp.h:75,
                 from ../vendor/openssl/openssl/include/openssl/evp.h:1,
                 from ../vendor/libssh2/src/openssl.h:45,
                 from ../vendor/libssh2/src/crypto.h:44,
                 from ../vendor/libssh2/src/libssh2_priv.h:132,
                 from ../vendor/libssh2/src/openssl.c:41:

... REMOVED A WHOLE BUNCH OF WARNINGS ...

In file included from ../src/../include/wrapper.h:11:0,
                 from ../src/nodegit.cc:6:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/../include/wrapper.h:11,
                 from ../src/nodegit.cc:6:
/home/user/.node-gyp/4.2.6/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/user/.node-gyp/4.2.6/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/user/.node-gyp/4.2.6/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/user/.node-gyp/4.2.6/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/../include/wrapper.h:11:0,
                 from ../src/nodegit.cc:6:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/project/node_modules/nodegit/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/home/user/project/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /home/user/project/node_modules/nodegit
gyp ERR! node -v v4.2.6
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /home/user/project/node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined

> nodegit@0.4.1 prepublish /home/user/project/node_modules/nodegit
> node lifecycleScripts/prepareForBuild.js


[nodegit] Detecting vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5.
[nodegit] Detecting vendor/libssh2/1.4.3.
[nodegit] Detecting vendor/http_parser/2.5.0.
[nodegit] Detecting generated code.
[nodegit] vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5 already exists.
[nodegit] vendor/libssh2/1.4.3 already exists.
[nodegit] vendor/http_parser/2.5.0 already exists.
[nodegit] Generated code is intact.
```
Debian Jessie x86_64
GCC 4.9.2-2
libstdc++-4.9-dev 4.9.2-10

Just wondering, but shouldn't the Ubuntu prebuilt binary work on Debian just as well? How can I see what specifically failed in installing that binary? I'm sure that it's missing some dependency.

Thanks!

**Comment by johnhaley81** [comment]
Why are you installing 0.4.1 instead of the latest?

**Comment by DaAwesomeP** [comment]
I didn't notice that! The project that requires it hasn't updated its dependencies. Version `0.10.0` worked fine. I don't know if it's compatible with the project, but that issue isn't relevant here.

Thanks for your quick reply.

**Comment by johnhaley81** [comment]
Np. Thanks for the issue!
