### ISSUE TITLE
Error attempting to install on AWS Linux

### ISSUE THREAD

**Issue by andrew-dixon** [nodegit/nodegit#926]
Trying to install nodegit on AWS Linux gives the following error:

```
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.5-node-v11-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/ec2-user/testcode/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at Request.emit (events.js:117:20)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/ec2-user/testcode/node_modules/nodegit/node_modules/node-pre-gyp/node_modules/request/request.js:952:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1744:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
node-pre-gyp ERR! stack     at CleartextStream.socketOnData [as ondata] (http.js:1639:20)
node-pre-gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
node-pre-gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
node-pre-gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
node-pre-gyp ERR! System Linux 4.1.17-22.30.amzn1.x86_64
node-pre-gyp ERR! command "node" "/home/ec2-user/testcode/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/ec2-user/testcode/node_modules/nodegit
node-pre-gyp ERR! node -v v0.10.42
node-pre-gyp ERR! node-pre-gyp -v v0.6.21
node-pre-gyp ERR! not ok 
```

Any advice on how to resolve this would be greatly appreciated.

**Comment by johnhaley81** [comment]
We don't support node v10. Please upgrade and try again.

**Comment by andrew-dixon** [comment]
Shame, I was looking to use it with AWS Lambda and that is only running on version v0.10.36, so even earlier.

**Comment by hairyhenderson** [comment]
@johnhaley81 - is there a version of nodegit that did support node v0.10?

**Comment by hairyhenderson** [comment]
To answer my own question, and to help anyone else who might run across this - it looks like v0.4.0 seems to work on Node v0.10.
