### ISSUE TITLE
Error when installing: msbuild exits with 1 with no error messages, only warnings

### ISSUE THREAD

**Issue by Gum-Joe** [nodegit/nodegit#950]
When I was installing nodegit on my computer through npm, I received the following error:
```
...compiler output...
  trees.c
  zutil.c
  win_delay_load_hook.c
  zlib.vcxproj -> C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\Release\\zlib.lib
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kishan Sambhi\\Documents\\Projects\\boss\\boss\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```
It says msbuild exited with `1`, however, the msbuild output shows that compilation was successful. No red error messages were shown.

System specs:

- OS: Windows 10 Home
- NodeJS: 5.8.0
- node-gyp: 3.0.3
- Visual Studio 2015

Thanks in advance.

**UPDATE:** I have ran a manual install. Turns out 22 errors were hidden.
Errors:
```
"C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\binding.sln" (default target) (1) ->
"C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]

    380 Warning(s)
    22 Error(s)
```

**Comment by Gum-Joe** [comment]
I think I just found out why: I should get a binary from S3, but my username has a space in it so it fails to be fetched.

**Comment by Gum-Joe** [comment]
Just did a manual build of nodegit. Turns out 22 errors were hidden.
Here are the errors:
```
"C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\binding.sln" (default target) (1) ->
"C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Libr
ary function declaration [C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\nodegit\build\vendor\libssh2.vcxproj]

    380 Warning(s)
    22 Error(s)
```

**Comment by johnhaley81** [comment]
@Gum-Joe can you test building the latest on master please? That should fix your issue.

**Comment by Gum-Joe** [comment]
Ok

**Comment by Gum-Joe** [comment]
@johnhaley81 #951 did not solve this issue - it was a temporary workaround. Please re open this issue.

**Comment by Gum-Joe** [comment]
Thanks

**Comment by Gum-Joe** [comment]
Will attempt rebuild later - currently updating development tools

**Comment by Gum-Joe** [comment]
Rebuild was not successful :disappointed:. Same errors.

**Comment by Gum-Joe** [comment]
Any update on this issue ?

**Comment by tbranyen** [comment]
@Gum-Joe I think the problem here is that you aren't getting our prebuilt. We haven't published for Node 5.8.0 yet. Can you try downgrading to our listed version in [.travis.yml](https://github.com/nodegit/nodegit/blob/552e82cd6ee94841d53bb418c5602602e05bd359/.travis.yml#L18) which looks like 5.0.

Once we publish a new version you'll get the prebuilt on Node 5.8

**Comment by Gum-Joe** [comment]
@tbranyen I have download the latest master from this repo and used it to get the prebuilt for now

**Comment by Gum-Joe** [comment]
I will close this issue after your node 5.9.0 (latest stable) has been released and can build on my system.

**Comment by Gum-Joe** [comment]
I managed to get the prebuilt by fixing install.js in #951

**Comment by johnhaley81** [comment]
@Gum-Joe going to see about doing a release later this week. I want the memory leak stuff to land first and get a bit of testing in before we say it's good.

**Comment by Gum-Joe** [comment]
Thanks @johnhaley81

**Comment by Gum-Joe** [comment]
Just installed the new release. Closing for now.
